### ISSUE TITLE
Scientific Notation

### ISSUE THREAD

**Issue by david15566** [mariuszgromada/MathParser.org-mXparser#110]
Hi!
First, congratulations for your tool, is very useful!

I've a question about scientific notation...Why if I calculate 3E+27 x 4E+28 mxparser returns 1,2E+56 but if I calculate 3E-27 x 4E-28 returns 0 instead of 1,2E-56?

Thanks for all,

Regards

**Comment by mariuszgromada** [comment]
Hi,

Thx for your feedback. This was a change implemented at some point to allow i.e. sin(pi) be equal exactly 1, meaning - almost integers are rounded at the end to integers.

mXparser has built-in option `mXparser.disableUlpRounding() / mXparser.enableUlpRounding() `- unfortunately - in `v.4.1.1` - this option does not control almost int rounding behavior.

In the current code on GitHub (not released yet) `mXparser.disableUlpRounding()` controls also alsmot int rounding. So, if you want, you can compile from code, or I can compile the lib for you and provide it via email for tests.

Finally I am thinking on separation between `mXparser.disableUlpRounding()` by introduction new option `mXparser.disableAlmostIntRounding()`. Justification is that `mXparser.disableUlpRounding()` - works directly on the unit in the last place precision, where `mXparser.disableAlmostIntRounding()` would work based on the defined epsilon.

Best regards

**Comment by david15566** [comment]
Thank you so much @mariuszgromada. I will be aware for the next update

**Comment by mariuszgromada** [comment]
Done!

```
mXparser.enableAlmostIntRounding()
mXparser.disableAlmostIntRounding()
mXparser.checkIfAlmostIntRounding()
```

Almost int rounding is controlled by
```
mXparser.getEpsilon()
mXparser.setEpsilon()

```
Best regards :-)

**Comment by mariuszgromada** [comment]
Released - check nuget or maven :-)
