### ISSUE TITLE
Function.checkSyntax() always returns true

### ISSUE THREAD

**Issue by andytwidle** [mariuszgromada/MathParser.org-mXparser#111]
The following code snippet:
```
var f = new Function("f(x) = (3 + 5*x");
Console.WriteLine($"checkSyntax: {f.checkSyntax()}");
Console.WriteLine($"getErrorMessage: {f.getErrorMessage()}");
```
yields the output
```
checkSyntax: True
getErrorMessage: [ (3 + 5*x] checking ...
[ (3 + 5*x] lexical error

Encountered "<EOF>" at line 1, column 9.
Was expecting one of:
    "(" ...
```

It doesn't seem to matter what the function is, checkSyntax now always returns true.
Function.getErrorMessage() behaves as expected.
Expression.checkSyntax() also behaves as expected.

Issue discovered in 4.1.1  (build from nuget.org)
TargetFramework=net461

In 3.0.0 Function.checkSyntax() worked as expected

Absolutely brilliant library, very much appreciate your hard work!

**Comment by mariuszgromada** [comment]
This is interesting, for sure a silly bug :-) Thanks!

Thank you for your feedback!

**Comment by mariuszgromada** [comment]
If you like the library - please give a star to the repository :-)

**Comment by mariuszgromada** [comment]
As I expected, silly bug introduced with new functionality providing user function based on body implemented in C# / JAVA. Fixed.

**Comment by mariuszgromada** [comment]
Released - check nuget or maven :-)
