### ISSUE TITLE
Imaginary Number and quaternion

### ISSUE THREAD

**Issue by Thaina** [mariuszgromada/MathParser.org-mXparser#112]
I think I haven't found mention in document about many dimension number. It would be great to support parsing and solving complex and quaternion

In C# there is System.Numerics namespace support for both Complex and Quaternion struct

**Comment by mariuszgromada** [comment]
This is not easy thing as mXparser is maintained for both Java and C#. Active development is under Java, then code is ported to C#. 

mXparser supports rich library of math functions, adding complex number is a big change.

Maybe I will do it in the future, or will ask the community to develop this part If it is really important.

Best regards

**Comment by sadqiang** [comment]
I need complex number support. Mathematics without complex number is like a soup without salt.

**Comment by mariuszgromada** [comment]
I agree - but this requires rewrite.
