### ISSUE TITLE
Combinatorics function feature request

### ISSUE THREAD

**Issue by JamesGallicchio** [mariuszgromada/MathParser.org-mXparser#117]
The combinatorics functions choose and permute should be added to the default library, either as `nCr(n, r)` and `nPr(n, r)` or as `n choose r` and `n permute r`.

These are highly useful in statistics, so much so that I'm surprised that they haven't been added yet. (Though, if they have already been added and I just can't find them, please let me know!)

**Comment by mariuszgromada** [comment]
Hi

Check function C(n,k) 

I will consider adding additional function name nCk(n,k) to reference existing C(n,k).
In case of nPk or nPr - this will be added in the next release.

Best regards

**Comment by mariuszgromada** [comment]
Done. I added nCk(n,k) that works exactly the same as C(n,k), where C(n,k) was available since v.1.0. Additionally I added nPk(n,k) for permutations.

```
mXparser.consolePrintHelp("nCk(");
mXparser.consolePrintHelp("nPk(");
```


```
Help content: 

    #  key word            type                    syntax                                        since description
    -  --------            ----                    ------                                        ----- -----------
  144. nCk                 <Binary Function>       nCk(n,k)                                      4.2   Binomial coefficient function, number of k-combinations that can be drawn from n-elements set

Help content: 

    #  key word            type                    syntax                                        since description
    -  --------            ----                    ------                                        ----- -----------
  168. nPk                 <Binary Function>       nPk(n,k)                                      4.2   Number of k-permutations that can be drawn from n-elements set
```

Regards

**Comment by JamesGallicchio** [comment]
Appreciated!

**Comment by mariuszgromada** [comment]
Pls let me know when you need dll / jar for tests. Code is on GitHub, but release is still waiting for other features.

**Comment by mariuszgromada** [comment]
Last but not least - GitHub star on mXparser repo highly appreciated :-)

**Comment by mariuszgromada** [comment]
Released - check nuget or maven :-)
