### ISSUE TITLE
Negative in if statement

### ISSUE THREAD

**Issue by MartinSher** [mariuszgromada/MathParser.org-mXparser#12]
Hi 

I have 

Argument a = new Argument("a");
Argument b = new Argument("b");

 var e = new Expression("if(a=6,-b,15)", a, b);
 a.setArgumentValue(6);
 b.setArgumentValue(5);
 result = e.calculate();

This works fine and returns result = -5.

However it 
 a.setArgumentValue(1);

then this takes a long time to execute the calculate() and then returns NaN instead of 15 as a is not equal to 6.

if however the expression is "if(a=6,b,15)" then this works fine and returns 15

Also expression = if(a=6,0-b,15)" works fine

Problem seems to be if you start with a negative sign in true condition part but your condition evaluates to false

**Comment by mariuszgromada** [comment]
Thank you, I will check that, seems to be simple bug.

**Comment by mariuszgromada** [comment]
Bug found - error is directly in iff statement reduction - will be corrected.

**Comment by mariuszgromada** [comment]
Fixed
