### ISSUE TITLE
[Request] Treat element surrounded by quotes as argument

### ISSUE THREAD

**Issue by i3jjnc68emm** [mariuszgromada/MathParser.org-mXparser#125]
Following situation:

`( 5 + this+is+an+unknown+argument + 5)`

Now this cannot be parsed as mXParser does not understand the part in the middle. However getMissingUserDefinedArguments is fired on 'this' and 'is' and 'an' etc. It splits the argument on the plus symbol. How can this be avoided? My thought was:

`( 5 + "this+is+an+unknown+argument" + 5)`

By surrounding it with double quotes I give mXParser a hint that everything inside is a fix string. However this didn't worked. Is there is a workaround or can you add something like this?

Please note that I have to rely on getMissingUserDefinedArguments as I don't know what exactly is given by user. So adding something as a fix argument  before parsing does not solve my problem.

**Comment by mariuszgromada** [comment]
Unfortunately, as of now, this is against mXparser grammar ... You should get chekLexSyntax() as false....

**Comment by Symbai** [comment]
Ok thanks :-)
