### ISSUE TITLE
Arguments/Constants with a plus causes a null exception

### ISSUE THREAD

**Issue by i3jjnc68emm** [mariuszgromada/MathParser.org-mXparser#126]
- MathParser.org-mXparser verssion: 4.1.1
- Framework: .net 4.5

```
var s = "(5 + this+is+a+test + 5)";
var x = new Expression(s);
x.addConstants(new Constant("this+is+a+test", 123.0));
x.calculate();
```

Results in a null exception:
kw2.wordString was null at  org.mariuszgromada.math.mxparser.DescKwLenComparator.Compare(KeyWord kw1, KeyWord kw2)

**Comment by mariuszgromada** [comment]
According to mXparser gramma this shuld be tokenized as follows:
( , + ,  this , is , a , test , + , 5 , )

You can not add a constant that has name not according to 'typical' variable name, check the error message

```
var c = new Constant("this+is+a+test", 123.0);
Console.WriteLine(c.getErrorMessage());

```
Result:
`
[this+is+a+test] --> invalid constant name, pattern not mathes: (\s)*([a-zA-Z_])+([a-zA-Z0-9_])*(\s)*`

Best regards

**Comment by mariuszgromada** [comment]
You should name your constant differently, i.e.: this_is_a_test
