### ISSUE TITLE
Incorrect value returned by MOD function for big numbers.

### ISSUE THREAD

**Issue by manuelvcr** [mariuszgromada/MathParser.org-mXparser#128]
When I use the mod function with big numbers, as internally the library uses double types, the numbers are truncated and the result of the function is incorrect.

For example:

mod(210501700012345678131468, 97)

The first number is converted to double: 2.1050170001234567E23

The result is 66 instead of 1.

I've made a test using BigInteger and the mod function of BigInteger class and the result is the correct.

**Comment by mariuszgromada** [comment]
Unfortunately I will not be able to fix your issue as mXparser is fully based on double.

**Comment by manuelvcr** [comment]
Hi Marius, 

I've implemented a solution for my project, based on using BigIntenger mod or BigDecimal remainder function for the calculation.

If you want, I can sent you the changes for your evaluation, they are very simple.

Find attached an image with the implemented change on Expression.MODULO function.
![2018-03-22 14_08_21-mathparser org-mxparser-modulo function](https://user-images.githubusercontent.com/17416853/37772339-97357f1c-2dda-11e8-95ca-44adcdd9f589.png)

**Comment by mariuszgromada** [comment]
Can you go with pull request?

**Comment by manuelvcr** [comment]
Hi Marius, I have pushed the change to a copy of your repository:

https://github.com/manuelvcr/MathParser.org-mXparser/commit/1ab200c69ced5576827468ca271da21a7fd55b46

You can check the change.

Best regards,

**Comment by mariuszgromada** [comment]
Sorry, It was closed by mistake.
Generally speaking - Implementation could be ok, but this code will bring problems

private String getTokenValueAsString (int tokenIndex) { 
	return tokensList.get(tokenIndex).tokenStr; 
}

It will only work when user is inputting the numbers - I need to rethink that

Best regards
