### ISSUE TITLE
Is mxparser able to parse decimals without leading zero?

### ISSUE THREAD

**Issue by atorch** [mariuszgromada/MathParser.org-mXparser#129]
#### Bug / question:
I'm using mxparser 4.1.1 in an Android app. I get lots of requests from users asking for the parser to support decimals without leading zeros, e.g. .2+.5 as opposed to 0.2+0.5. Do later versions of mxparser support that functionality?

Edit:  the app is https://play.google.com/store/apps/details?id=atorch.statspuzzles (probability puzzles app on Android).  Several reviews request that ".6 should read as 0.6", "Good puzzles, doesn't recognize .5 as 0.5", etc.

**Comment by atorch** [comment]
Sorry for the poor editing, I wrote this on my phone. Can't find edit button.

**Comment by mariuszgromada** [comment]
Can you give the app name? :-)

I will add this functionality - this will not be a problem.

**Comment by jonantoine** [comment]
I am also eager for this feature. When do you think 4.2 will be released?

**Comment by mariuszgromada** [comment]
Huge part is ready, but I do not have time currently. It requires few working days to develop, but ... professional life consumes all the time I have now.

Will try to do it fast as a lot of functionalities will be added :-)

**Comment by mariuszgromada** [comment]
Added

**Comment by mariuszgromada** [comment]
Released - check maven :-)
