### ISSUE TITLE
Output issue

### ISSUE THREAD

**Issue by PaddiM8** [mariuszgromada/MathParser.org-mXparser#13]
Expression ex = new Expression(mathInput);
            Console.WriteLine(ex.calculate());

This simple code returns "¤¤¤" as output in the console.

mathInput is just 2 * 5, and outputs to just that in the console. It's a string too!
What the heck is wrong?! I am using the .NET 4.5 version as my application is using that version.

**Comment by mariuszgromada** [comment]
In my case the code:

	String mathInput = "2 * 5";
	Expression ex = new Expression(mathInput);
	Console.WriteLine(ex.calculate());

returns 10
