### ISSUE TITLE
Issue with mixed up unary/binary operator 

### ISSUE THREAD

**Issue by optodelp** [mariuszgromada/MathParser.org-mXparser#130]
### Issue content:
I must admit, that the parsing of unary and binary operators is not trivial.
Nevertheless, some programatically created formulas are leading to NaN, even if the expression is valid (in my humble opinion).

So "3+3"  should give the same result as "3--3". 
Using brackets helps here: "3-( -3)" gives 6 again. But it's not easy to teach our users to use brackets.

Is it possible to improve the parser here?

#### If bug/question:
- MathParser.org-mXparser verssion: v.4.4.1
- Framework: .net
- Problem description
- Code example

            exp = new Expression("3+3");
            Assert.AreEqual(6.0, exp.calculate(), 1e-3); // Works fine
            exp = new Expression("3--3");
            Assert.AreEqual(6.0, exp.calculate(), 1e-3); // Gives NaN
            exp = new Expression("3-(-3)");
            Assert.AreEqual(6.0, exp.calculate(), 1e-3); // Works fine

**Comment by mariuszgromada** [comment]
Pls run exp.checkSyntax() and then check exp.getErrorMessage()

3--3 is against mathematical conventions

I ave doubts about introducing syntax which is against math conventions.

**Comment by optodelp** [comment]
OK, it does not make sense to code against conventions.
Thank you for your fast reply.

**Comment by mariuszgromada** [comment]
You can print the error message to the users - then it might be easier to teach them proper syntax. Can say few words how you use mXparser? I am always interested in this.

Regards

**Comment by optodelp** [comment]
Our users are creating templates for engraving machines. They define objects and their location/rotation in a plain text file. The server loads the template and replaces placeholders due to the current jobdata.

As a new feature, we want to calculate some values at runtime:
x=%XPOS%-%XOFFSET%

And here cames the trouble...if XOFFSET is a negative value, we get the "--".

I will use the checkSyntax for logging, but because the issue happens at runtime, I cannot display it while editing.

**Comment by mariuszgromada** [comment]
I have and idea - you can add the brackets by yourself. :-) With mXparser this is extremely easy :-)

```
using System;
using System.Collections.Generic;
using org.mariuszgromada.math.mxparser;
using org.mariuszgromada.math.mxparser.parsertokens;

					
public class Program
{
	public static void Main()
	{
		Expression exp = new Expression("3+3+sin(3--3)+3--3+5");
		List<Token> tokens = exp.getCopyOfInitialTokens();
		mXparser.consolePrintTokens(tokens);
		if (tokens != null)
			if (tokens.Count > 1)
			{
				String newExpStr = tokens[0].tokenStr;
				for (int i = 1; i < tokens.Count; i++)
				{
					Token tprev = tokens[i-1];
					Token tcur = tokens[i];
					String tStr = tcur.tokenStr;
					if (tprev.tokenTypeId == Operator.TYPE_ID && tprev.tokenId == Operator.MINUS_ID)
						if (tcur.tokenTypeId == ParserSymbol.NUMBER_TYPE_ID && tcur.tokenId == ParserSymbol.NUMBER_ID)
							tStr = ParserSymbol.LEFT_PARENTHESES_STR + tStr + ParserSymbol.RIGHT_PARENTHESES_STR;
					newExpStr = newExpStr + tStr;
				}
			mXparser.consolePrintln();
			mXparser.consolePrintln("Original : " + exp.getExpressionString());
			mXparser.consolePrintln("Corrected: " + newExpStr);
			mXparser.consolePrintln();
			mXparser.consolePrintln("Now just grab the new string and create expression :-)");
			mXparser.consolePrintln("You are welocme :-)");
			mXparser.consolePrintln("Pls give a astar on GitHub :-)");
		}
	}
}

```

Best regards

**Comment by mariuszgromada** [comment]
Please let me know whether this solves your problem :-)

**Comment by optodelp** [comment]
It's working fine :)
Now, I use checkSyntax(), and if it fails I fix the expression with the token code.
Great, thank you very much.

**Comment by mariuszgromada** [comment]
In the new release I will add the option to try to fix formula :-)

**Comment by jonespm** [comment]
@mariuszgromada Do you have an issue to track for where this might be fixed? Looks like this one is closed. Thanks!
