### ISSUE TITLE
Support for .Net Standard 2.0

### ISSUE THREAD

**Issue by daunish** [mariuszgromada/MathParser.org-mXparser#133]
### Issue title:
Please add support for .Net Standard 2.0

### Issue content:
Currently there are only targets for up to .Net Standard 1.6. When used in purely .Net Standard/.Net Core 2.0 stack this library will not load. Please provide a csproj/target for .Net Standard 2.0

**Comment by mariuszgromada** [comment]
Will do that in next release.

**Comment by mariuszgromada** [comment]
Will do that - thx.

**Comment by daunish** [comment]
Thank you!

**Comment by harindaka** [comment]
Any date and time on when .net standard 2.0 support will be released? I tried to add the nuget package in my Xamarin forms project (.Net Standard 2.0 project) and I get the following error when trying to run on Android:

Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'MathParser.org-mXparser.Stand16, Version=4.0.0.2, Culture=neutral, PublicKeyToken=0fbab7add73ed6e2'. Perhaps it doesn't exist in the Mono for Android profile?

**Comment by otake1977** [comment]
Hey, +1 for .net standard support.

**Comment by mariuszgromada** [comment]
Done - few days to release 4.2.0 including .net standard 2.0 and .net core 2.0

**Comment by mariuszgromada** [comment]
Released - check nuget :-)

**Comment by daunish** [comment]
Thank you! Updated to latest version and it works great
