### ISSUE TITLE
Optimized way to executing same function multiple times

### ISSUE THREAD

**Issue by murdockcrc** [mariuszgromada/MathParser.org-mXparser#134]
Hi,

I'd like to get some guidance about what is the best performing way to use mXparser to execute geometry/trigonometry equations. I have several functions that need to be executed about 200K times. Today, I am creating `Tasks` with the calculations and awaiting them all. On each a call, I instantiate a new `Function`, like this:

```
/// Prepares the Tasks for parallel execution
for (var i = 2; i < interpolationSplits; i++)
            {
                tasks.Add(Task.Run(() =>
                {
                    Position pos = GeneratedInterpolatedDataPoint(startPosition, endPosition, i);
                    return post;
                }));
            }
await Task.WhenAll(tasks)

/// GenerateInterpolatedDataPoint depends on methods like this one:
private double Method1()
        {
            Function f = new Function("f(radius,alphalat1,alphalat2,alphalong1,alphalong2) = <complex_geometrical_function_goes_here>");
            var result = f.calculate(<params>);
            return result;
        }
```

I am running into poor performance when computing these calculations over a large data set, and I was wondering if I could define the `Functions` only **once** and reuse them by simply changing their parameters, like this:

```
    public class HelperClass
    {
        private Function @long = new Function("f(alpha, theta, alphalat1, long1, di, radius, interpolatedLat) = <math_function_to_be_reused>");

private double Method1()
        {
            var expression = new Expression(@long.getFunctionExpressionString(), @long, <objects typeof Argument>);
            var result = expression.calculate();
            return result;
        }
}
```

So I am wondering:
1. Would creating one instance of `Function` and reusing it improve performance when executing that function hundreds of thousands of times?
2. If yes, what is the guidance on the best way to declare `Functions` to be reused?

I was looking at the Regression Tests .cs file for guidance but I could not find the correct way to reuse that logic of the tests for my purpose.

**Comment by mariuszgromada** [comment]
It will dramatically improve the performance if you create a function once and then reuse it. When you instantiate the Function (new Function) there is a lot of parsing / checks done in the background. You have to create one static function object.

In your case

```
public class HelperClass
{
        private static Function f = new Function("f(radius,alphalat1,alphalat2,alphalong1,alphalong2) = <complex_geometrical_function_goes_here>");
        private double Method1()
        {
            var result = f.calculate(<params>);
            return result;
        }
}
```

Hope this helps.

Best regards

**Comment by mariuszgromada** [comment]
Additionality you create a function in a "natural langue" repeating it 200K times - this means 200K times running comlicated regexp to understand what was written. Do it once, it will be pre-compiled, and then if no changes to the formula (params might change), it will run fast.

mXparser has some other constructors that might result in your case even in better performance. I will do some tests and give you recommendation :-) This will not be then in "natural language".

**Comment by murdockcrc** [comment]
Ok thx. I tried moving the functions as private vars of the class, but kept getting index out of bounds exceptions when executing the calculations.

I will try to refactor them as static.

Thx

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by murdockcrc** [comment]
Thanks for the prompt reply. I have made the `Functioncs` static members for the class, however, I keep getting weird errors during execution (either NaN results or `index out of bounds for the collection` exceptions when doing `f.calculate()`.

I have tracked this down to the use of parallelism in the execution of the calculation. I do not iterate through a counter to execute the calculations, but I rather build a list of `Tasks` that get executed in parallel by the runtime:

```
    for (var i = 2; i < interpolationSplits; i++)
            {
                tasks.Add(Task.Run(() =>
                {
                    Position pos = GeneratedInterpolatedDataPoint(startPosition, endPosition, i);
                    return post;
                }));
            }
    await Task.WhenAll(tasks)
```

I guess this approach, combined with the static Function, runs into a race condition that makes the calculation engine crash.

I did try to refactor this logic to iterate through the actual math execution (using the static Function) instead of using the `Tasks.WhenAll` approach. However, that approach takes 20secs to complete, wheareas the `Tasks.WhenAll` approach (even though each task instantiates a new instance of `Function`) takes 8 seconds to complete.

I am wondering if you have a recommendation on how to parallelize the execution of the math formulas (using something similar to my approach with `Tasks.WhenAll`) without having to create an instance of `Function` for every `Task`. Does that make sense for you?

**Comment by mariuszgromada** [comment]
In case of parallel process remember to create static objects separately for each process, otherwise you will get strange conflicts, errors as multiple processes will change the object state. So - If 8 processes then 8 different static functions.

See this file, it might help
https://github.com/mariuszgromada/MathParser.org-mXparser/blob/master/CURRENT/c-sharp/src/org/mariuszgromada/math/mxparser/regressiontesting/PerformanceTests.cs

Best regards

**Comment by murdockcrc** [comment]
The optimizations from reusing the static function are good enough, so I don't have to use the parallel process technique any longer. Thanks for your great help, that was really useful.

**Comment by mariuszgromada** [comment]
great :-)
