### ISSUE TITLE
StringIndexOutOfBoundsException asking for tokens of empty expression

### ISSUE THREAD

**Issue by GammaCodeX** [mariuszgromada/MathParser.org-mXparser#135]
- MathParser.org-mXparser verssion: v.4.1.1
- Framework: java (jdk17)

When creating an expression with no tokens
`Expression expression = new Expression("");`

asking for the list of internal tokens
`List<Token> tokens = expression.getCopyOfInitialTokens();`

ought to return an empty list (this is not exectional behaviour although it is degenerate)
`assertEquals("list should be empty since no tokens given",0,tokens.size());`

but instead raises StringIndexOutOfBoundsException.

Full unit test (Juint4):
```
    @Test
    public void badBehaviorInMxparser() throws Exception{
        Expression expression = new Expression("");
        List<Token> tokens = expression.getCopyOfInitialTokens();

        assertEquals("list should be empty since no tokens given",0,tokens.size());
    }
```

**Comment by mariuszgromada** [comment]
Fixed

**Comment by mariuszgromada** [comment]
Released - check nuget or maven :-)
