### ISSUE TITLE
Endless loop and system crash with factorial and double equality operator

### ISSUE THREAD

**Issue by fdmoulin** [mariuszgromada/MathParser.org-mXparser#136]
### Issue title:
Endless loop and system crash when factorial is used with a double equality operator

### Issue content:
When calculating an expression that contains a factorial and evaluating with the double equality operator ==, an endless loop is triggered.

#### If bug/question:
- MathParser.org-mXparser-jdk18-4.1.1
- Framework: java 8
- Problem description

The == operator seems to be throwing factorials for a loop (pun intended).  Not sure if == is an accepted operator in this library, but it's common enough in most programming languages to make this a serious risk of being used inadvertently.  The single = operator seems to work fine, and the problem doesn't occur when the factorial is wrapped in parentheses.

- Code example:
`new Expression("5! = 120").calculate(); // OK`
`new Expression("(5!) == 120").calculate(); // OK`
`new Expression("5! == 120").calculate(); // creates endless recursion? loop draining CPU`

**Comment by mariuszgromada** [comment]
Ok, the bug was found - thx.

```
Expression e = new Expression("5! == 120");
mXparser.setConsolePrefix("");
mXparser.consolePrintTokens(e.getCopyOfInitialTokens());
```

Result:
```
 --------------------
| Expression tokens: |
 ---------------------------------------------------------------------------------------------------------------
|    TokenIdx |       Token |        KeyW |     TokenId | TokenTypeId |  TokenLevel |  TokenValue |   LooksLike |
 ---------------------------------------------------------------------------------------------------------------
|           0 |           5 |       _num_ |           1 |           0 |           0 |         5.0 |             |
|           1 |          != |          != |           2 |           3 |           0 |         NaN |             |
|           2 |           = |           = |           1 |           3 |           0 |         NaN |             |
|           3 |         120 |       _num_ |           1 |           0 |           0 |       120.0 |             |
 ---------------------------------------------------------------------------------------------------------------

```

The problem is in the tokenization, here all blanks are removed before then you have "!==" and "!=" is found first.

Will fix that - this should be simple.

:-)

**Comment by fdmoulin** [comment]
Thanks!  Great library btw...

**Comment by mariuszgromada** [comment]
Thx :-) is it worth a star? :-)

**Comment by fdmoulin** [comment]
At least one!  It's already done :)

**Comment by mariuszgromada** [comment]
Fixed :-)

**Comment by mariuszgromada** [comment]
Released - check nuget or maven :-)
