### ISSUE TITLE
Support for arguments with different data types

### ISSUE THREAD

**Issue by klinki** [mariuszgromada/MathParser.org-mXparser#137]
### Issue title:
I think it would be really great to have generic `Argument` class and support results of different types (like int and boolean).

#### Example:

```java
String stringExpression = "A && B";

Argument a = new Argument("A", true);
Argument b = new Argument("B", true);

Expression parsedExpression = new Expression(stringExpression, a, b);

mXparser.consolePrintln("Result: " + parsedExpression.getExpressionString() + "=" + parsedExpression.calculate());
```

Expected result
```java
A && B = true
```

Current result
```java
A && B = 1.0
```

**Comment by mariuszgromada** [comment]
mXparser is fully based on double - this is the only data type that is currently supported.
mXparser supports Boolean logic assuming false is coded as 0, true is coded as 1.
mXparser delivers special constants "[true]", "[false]" which are interpreted as 1 and 0.

**Comment by homam1** [comment]
Any plan or timeline for this enhancement? For example Date functions or string

**Comment by mariuszgromada** [comment]
This is a big change...
