### ISSUE TITLE
handle big number(+,-,x,/) return 2147483647

### ISSUE THREAD

**Issue by khavnu** [mariuszgromada/MathParser.org-mXparser#138]
Hi @mariuszgromada
First, thank for your mXparser-lib, it's very useful and i love it, but when i use your lib with big number, it alway return 2147483647 (2^31 -1).  Example with 1234567890*5, can you fix it?
//Sorry about my bad English !

**Comment by mariuszgromada** [comment]
Thx for your feedback. Can you give a code example? Please add also information on the framework you are using (java, .net + version).

Best regards

**Comment by khavnu** [comment]
Thank for your replies, but i've found that is my fault. I've fix it, i will remove my issue now
