### ISSUE TITLE
Do we have escape character for argument evaluation?

### ISSUE THREAD

**Issue by Thaina** [mariuszgromada/MathParser.org-mXparser#139]
What I expect is, I could write expression like this

```
var distExpr = new Expression("sqrt(($lvec.X$ - $rvec.X$)^2 + ($lvec.Y$ - $rvec.Y$)^2)");
```

And when I try to see arguments of `distExpr` I could get `lvec.X` `rvec.X` `lvec.Y` `rvec.Y`

Then I could evaluate these arguments from my program, set it to expression, and calculate it

But because in the real scenario we could have more complex string (I was thinking about JSONPath) that may contains character which could collide with mXparser

So are there escape character in mXparser system? One we can escape character or the whole string as a block

If there was none I would like to request this feature

**Comment by mariuszgromada** [comment]
In mXparser there is no such thing as escape character.

**Comment by Thaina** [comment]
@mariuszgromada Could we have it or are there issue in the parser system that don't let us able to?

**Comment by mariuszgromada** [comment]
Can you write some piece of code as an example? I think I do not understand your need. mXparser has defined grammar, nothing different than grammar will be parsed / evaluated.

**Comment by Thaina** [comment]
@mariuszgromada Suppose we try to parse this

```C#
var x0 = new Argument("$0/position/x",1);
var y0 = new Argument("$0/position/y",1);
var x1 = new Argument("$1/position/x",0);
var y1 = new Argument("$1/position/y",0);

// vector distance function
string expr = "sqrt(($0/position/x - $1/position/x)^2 + ($0/position/y - $1/position/y)^2)";
var e = new Expression(expr,x0,y0,x1,y1);
var result = e.Calculate();
```

Is it possible? I'm not sure that any character would have collision with existing math operator, in this case is `$` and `/`

So I would like to have some escape character to ensure that, any string between this character would be argument name, thus an escape character

And on the other hand I wish this would work too

```C#
// vector distance function
string expr = "sqrt(($0/position/x - $1/position/x)^2 + ($0/position/y - $1/position/y)^2)";

// Just parsing without setting argument value
var e = new Expression(expr);

foreach(var arg in e.argumentsList)
{
    /// map with value in the database
    double value = await GetValueFromName(arg.getArgumentName());
    arg.setArgumentValue(value);
}

var result = e.Calculate();
```

**Comment by mariuszgromada** [comment]
So you want use any kind of names for arguments & constants. This is against current grammar. Current grammar definition:
https://github.com/mariuszgromada/MathParser.org-mXparser/blob/master/CURRENT/c-sharp/src/org/mariuszgromada/math/mxparser/syntaxchecker/SyntaxChecker.jj
```

/*
 * Token representing identifiers
 */
TOKEN :
{
	< IDENTIFIER:	<LETTERS> ( <LETTERS> | <INTEGER> )*  										>
}
```

Identifiers are defined in the similar way as in majority of programming languages. I do not want to introduce the mess in the conventions.

Maybe you should consider renaming your arguments?

Best regards

**Comment by Thaina** [comment]
Thank you very much for your clarification

But then could you tell me, are there any symbol on english keyboard (or combination of symbols) that would never be used in mXparser? So I could make custom parser layer over mXparser with that symbol

**Comment by mariuszgromada** [comment]
Grammar forces you to use `<LETTERS> ( <LETTERS> | <INTEGER> )*`  where `LETTER = ["_","a"-"z","A"-"Z"]` and `INTEGER = <DIGIT>(<DIGIT>)*`, where `DIGIT = ["0"-"9"]`

Best regards

**Comment by Thaina** [comment]
@mariuszgromada What I means is, I could make my own parser to extract and replace my custom variable syntax before passing it to mXparser

Suppose I use `$$` as marker

```C#
var expr = "sqrt(($lvec.X$ - $rvec.X$)^2 + ($lvec.Y$ - $rvec.Y$)^2)";

var arguments = MyCustomMxArguments(ref expr);
// expr became "sqrt((a0 - a1)^2 + (a2 - a3)^2)", replacing all $$ keyword with valid grammar
// arguments contains [Argument("a0"),Argument("a1"),Argument("a2"),Argument("a3")]

var e = new Expression(expr,arguments);
```

Something like this, so I was asking for a symbol that will not be used in mXparser for anything for sure

**Comment by Thaina** [comment]
Thank you very much
