### ISSUE TITLE
Can a do argument assignment(s) with this tool?

### ISSUE THREAD

**Issue by jonantoine** [mariuszgromada/MathParser.org-mXparser#143]
### Issue title:
Can a do argument assignment(s) with this tool?

#### If bug/question:
- MathParser.org-mXparser verssion: v.4.1.1
- Framework: .net v4.6.2
- I am new to your parser. Is there a way to assign one or more arguments with the results of an equation?
- Code example 1 (I get a invalid error about the comma)

            var x = new Argument("x", 0);
            var y = new Argument("y", 0);
            var ab = new Argument("ab", 3);
            var dc = new Argument("dc", 10);
            var eval = new Expression("x=ab+dc, y=dc-ab", x, y, ab, dc);

            if (eval.checkSyntax())
            {
                Console.WriteLine(eval.calculate());
                Console.WriteLine(eval.getArgumentValue("x"));
            }
            else
            {
                Console.WriteLine(eval.getErrorMessage());
            }

- Code example 2 (single assignment, result of calc is zero and argument value of 'x' of zero)

            var x = new Argument("x", 0);
            var y = new Argument("y", 0);
            var ab = new Argument("ab", 3);
            var dc = new Argument("dc", 10);
            var eval = new Expression("x=ab+dc,", x, ab, dc);

            if (eval.checkSyntax())
            {
                Console.WriteLine(eval.calculate());
                Console.WriteLine(eval.getArgumentValue("x"));
            }
            else
            {
                Console.WriteLine(eval.getErrorMessage());
            }

**Comment by mariuszgromada** [comment]
Yes, but you need to use different constructors:

**Code 1:**

```
var ab = new Argument("ab", 3);
var dc = new Argument("dc", 10);
var x = new Argument("x=ab+dc", ab, dc);
var y = new Argument("y=dc-ab", ab, dc);
Console.WriteLine("x = " + x.getArgumentValue());
Console.WriteLine("y = " + y.getArgumentValue());
ab.setArgumentValue(4);
dc.setArgumentValue(9);
Console.WriteLine("Changing ab and dc values");
Console.WriteLine("x = " + x.getArgumentValue());
Console.WriteLine("y = " + y.getArgumentValue());
```

**Code 2:**

`var eval = new Expression("x=ab+dc", x, ab, dc);`

Here is the Boolean logic example - simply value of `x` and value of `ab+dc` are compared, if not equal (`x = 0`, `ab+dc = 13`) the `false = 0` is returned.

Bes regards
