### ISSUE TITLE
Java Precision error, 1.2-1.1 result 0.09999999..........

### ISSUE THREAD

**Issue by andrew4alive** [mariuszgromada/MathParser.org-mXparser#144]
Precision error using 

Java Code
ex=new Expression(eval);
ex.calculate()

1.2-1.0 = 0.2
**1.2-1.1 = 0.0999999999999999**

what the reason? it that a bug?

**Comment by mariuszgromada** [comment]
mXparser is based on double numbers, and this is a result of double representation - please see the code below.

```
double x = 1.2;
double y = 1.1;
double z = x - y;
System.out.println(z);
```

**Result**

`0.09999999999999987`

Best regards

**Comment by mariuszgromada** [comment]
#195
