### ISSUE TITLE
error when creating an argument

### ISSUE THREAD

**Issue by duytv14** [mariuszgromada/MathParser.org-mXparser#145]
### Issue title:
error when creating an argument

### Issue content:
I have created an argument like the example below, but when I use the checkSyntax function the result is false
example:
var argument = new Argument("AAAAA", 730000000); or 
var argument = new Argument("aaaaaa", 730000000); or 
var argument = new Argument("Aaaaaa", 730000000);
var g = argument .checkSyntax();
var ff = argument .getErrorMessage();
result:
g = false
ff = [] checking ...
[] lexical error 

Index was outside the bounds of the array.
[] errors were found.

Thank you.

**Comment by mariuszgromada** [comment]
Thx - this is a small bug. Generally speaking Argument.checkSyntax() is for dependent/recursive argument only. 
http://mathparser.org/api/org/mariuszgromada/math/mxparser/Argument.html#getArgumentType--

Will fix that tu return true in case of Argument.FREE_ARGUMENT

**Comment by mariuszgromada** [comment]
Fixed :-)

**Comment by mariuszgromada** [comment]
Released - check nuget or maven :-)
