### ISSUE TITLE
NaN returned by a Divide by Zero Calculation is Significantly Slower than if there were no Divide by Zero  

### ISSUE THREAD

**Issue by brewertl** [mariuszgromada/MathParser.org-mXparser#146]
### Issue title:
Dividing by zero in the Calculate method causes a hug performance hit on the calculation

### Issue content:
I am creating an application that will allow a user to plot measured data from a data file generated during a test. Part of what they want to do is be able to create calculations that can be plotted together with the measured data. The data file they read from can have 10's of thousands of data records each one is processed through the calculations. Sometimes during the beginning of the test, the data values being recorded will be zero and are used in the denominator of a division operator. Anytime the denominator is evaluated as a zero value, the compute time returned by the calculate method can be somewhere between 0.5 second and 0.7 second and I can visually tell there is a tremendous slow down. However, if the denominator is not zero the calculate method returns very quickly (evaluates the rest of the data in a matter of 2-3 seconds). So in my case, the first 2500 records will cause a divide by zero which takes approximately 20 minutes to run through while the remaining 17,500 records that do not cause a divide by zero take 2-3 seconds

Is there some setting that I am missing to keep this from happening? Or is there another way the divide by zero and NaN's can be handled?

BTW, I love this product. I has made my life a lot easier being able to use it. It has all the functionality that will be needed for my current project. Thanks for putting in your time and effort in creating this and supporting it.

#### If bug/question:
- MathParser.org-mXparser verssion: v.4.1.1
- Framework:  .net 4.0, C#
- Problem description: See Issue content
- Code example

**Comment by mariuszgromada** [comment]
Debug mode or release mode?

**Comment by mariuszgromada** [comment]
Strange - this should be fast. Please see the src in v.4.1.1
https://github.com/mariuszgromada/MathParser.org-mXparser/blob/v.4.1.1/CURRENT/c-sharp/src/org/mariuszgromada/math/mxparser/mathcollection/MathFunctions.cs

```
public static double div(double a, double b) {
	if (Double.IsNaN(a) || Double.IsNaN(b))
		return Double.NaN;
	double result = Double.NaN;
	if (b != 0)
		result = a / b;
	return result;
}
```

**Comment by mariuszgromada** [comment]
Can you pls prepare one example + schare src + send the log of setVerboseMode() option?

Expression e ...
e.setVerboseMode()
e.calculate()

Best regards

**Comment by brewertl** [comment]
I have attached a Visual Studio C# solution that is setup using the same data structures and code that I am using in the larger application. I have a User Interface for it so that you can run it with zero in the equation and then run again without zero in the equation depending on the button you click. I also have a changeable iteration counter as well as a checkbox to turn on/off the verbose mode. This example exhibits the slow performance that I have been seeing when you press the “Calculate with Zero” button.
[WindowsFormsApplication4.zip](https://github.com/mariuszgromada/MathParser.org-mXparser/files/2090198/WindowsFormsApplication4.zip)

**Comment by brewertl** [comment]
After running the application, both the demo and the larger application, outside of the Visual Studio Environment, the calculations run fast no matter what the denominator is. Thanks for your quick responses, I am back up and moving forward again. 

Again, great package!

**Comment by mariuszgromada** [comment]
Anyway - it should not be like that... Maybe some exceptions are thrown... Can you please check how it runs in release mode (start without debugging)?

**Comment by mariuszgromada** [comment]
@brewertl - I tried your app - In my case, using VS 2017 Community - it runs ok, no matter divided by 0 or not. It has to be some problem with your environment.

**Comment by mariuszgromada** [comment]
@brewertl - If you like the lib then please consider giving a GitHub star :-)
