### ISSUE TITLE
erratic import behavior in Jython ( due to the "org." namespace ? )

### ISSUE THREAD

**Issue by stanpetit** [mariuszgromada/MathParser.org-mXparser#147]
- MathParser.org-mXparser 4.1.1
- java, jdk16
- inside a _Jython_ embedded interpreter, application on jdk16 itself ( _Java_ 6 SE )

Hi Mariusz Gromada !

I was writing a simple maths expression parser ( RNP/shunting-yard algorithm) to use in _NodeBox_, a _Java_ open-source application dedicated to procedural graphics animations, that has a Jython interpreter.  
Googling the subject, I was sent to your very impressive _mXparser_ library ! ( and guess what : it's creator is Polish ... a nation with it's great mathematicians indeed : who cares about who began solving the Enigma machine during WW2 ? who writes the history books, The British? ).

Now , what a lots of maths ( in fact far too many, for the poor usage I will have of it : almost a shame ) ! But it is very tantalizing. _NodeBox_ has a _Jython_ scripting interface and I began to write a script to discover the API, and the first time I ran this I've been happy with :
```
mathparser_path = unicode( r"C:\some_path_to\MathParser.org-_mXparser_-jdk16-4.1.1.jar", 'utf-8')
sys.path.append( mathparser_path )
import org.mariuszgromada.math._mxparser_ as mep
from mep import *

dir( mep )
# ['Expression', 'Function', 'Tutorial', '__name__', '_mXparser_']
```  
But there is a pitfall with _NodeBox_ : to avoid colliding/polluting the local namespace (and increase the memory load), it is advised to execute expressions in some dedicated dictionary, in fact a super_local_namespace that screens the variables to be evaluated against the expression .  
In fact, this screening of variables it is exactly what _mXparser_ does, nice.  
```
expr = "a+b"
ns = { 'a': 1, 'b': 2 }
exec "from math import *" in ns
result = eval(expr, ns)
```  
The local_namespace should just hold ```expr```, ```ns``` and ```result``` and returns it to the main application : a UI component dedicated to scripting, that holds the expression strings input : ```expr``` and a string form for the args that will be fit to ```ns``` .  

So, I wanted to check if importing a _Java_ library this way ( instead of _Python_ "math" ) had a correct behavior ... and the _mxparser_ library was the first _Java_ library I tried this onto : bad idea ...  

Since then, I get the pretty bad : ```ImportError: No module named mariuszgromada```, wherever and whatever syntax I use.  

#### Python/Jython resolves imports with the logic of : the ["winner-take-all"](http://www.jython.org/jythonbook/en/1.0/ModulesPackages.html#sys-path) .  
And _Jython_ starts "preloaded" with the namespace exposed by the application. 
[Naming Python Modules and Packages](http://www.jython.org/jythonbook/en/1.0/ModulesPackages.html#naming-python-modules-and-packages) talks about this logic in the _Python_ dev point of view. The ```org.``` domain is already the base for a part of the _NodeBox_ application ( ```org.xml.sax ...``` ) and I guess that ```mariuszgromada``` is now searched inside this ```org.``` root namespace, and that I have been lucky once to get it imported ... I have searched and tried many solutions, no result except this one :  
_NodeBox_ writes temporary dlls to the ```user's Temp folder``` to cache the executable code produced by _Jython_, and the error gets stuck there.  
Getting rid of them (manually) is just a desperate fix.  

Whatever it is, _I want to get Mariusz Gromada "running in my back-yard" !_ I needed a solver to get a point's closest-distance to a quadratic curve ...  

I guess that the safest way would be to include _mXparser_ inside _NodeBox_ and compile , but I would like to experiment with importing inside _Jython_ before doing this, to be able to see the _Jython_ binding overhead. As _mXparser_ is _Java_, there shouldn't be so much once imported ... in the conventional form ...  
Also, finally _mXparser_ will always be called from _Jython_ inside _NodeBox_, as it is the place to develop the custom functions.  

My first guess for a "simple but dirty way" to overcome this import error, would be to refactor the ```org.``` package name to something that _Jython_ would clearly identify and compile _mXparser_. After all, the ```org.``` root package name is nothing more than a naming convention without any functionnal restriction in this case, is it ?  

Would you mind giving me some advice on this ?  

- Would ```mariuszgromada.``` fit as a root package name ?  
- Is ```_Java_ 6 SE ( X86 , jdk6, jre6 )``` convenient/enough for compilation ?  

Best Regards,  
Stanislas Petit.

**Comment by mariuszgromada** [comment]
Will do that for you :-)

**Comment by mariuszgromada** [comment]
Try this one :-)

[mariuszgromada.math.mxparser.jar.zip](https://github.com/mariuszgromada/MathParser.org-mXparser/files/2171529/mariuszgromada.math.mxparser.jar.zip)

**Comment by mariuszgromada** [comment]
Is it worth a github star? ;-)
