### ISSUE TITLE
It doesn’t detects explicitly a division by zero

### ISSUE THREAD

**Issue by patricioafernandes** [mariuszgromada/MathParser.org-mXparser#149]
### Issue title:
- It doesn’t detects explicitly a division by zero. It returns NaN.

### Issue content:
We would like to treat explicitly expressions with a division by 0.
Currently, the parser doesn’t detects explicitly a division by zero. It returns NaN.

#### If bug/question:
- MathParser.org-mXparser verssion: v.4.2.1
- Framework: .Net 4.6.2
- Problem description
We would like to treat explicitly expressions with a division by 0.
Currently, the parser doesn’t detects explicitly a division by zero. It returns NaN.
- Code example

#### If new feature
- Feature description
- Use case description

**Comment by mariuszgromada** [comment]
Please use if function, i.e.:
if( a = 0, b/a, <yourvalue> )
