### ISSUE TITLE
Binary Operators support

### ISSUE THREAD

**Issue by ewoks** [mariuszgromada/MathParser.org-mXparser#15]
Hi,
not sure if I missed it somewhere but seems like there is no support for binary operators.

few examples: 
```
x>>15 //shift
~x //complement
x&1 //binary AND
```
would be great additions and make this library even more useful. Let me know what you think

**Comment by mariuszgromada** [comment]
Will try to add that.

**Comment by mariuszgromada** [comment]
Bitwise was added

**Comment by mariuszgromada** [comment]
Please use:
- @~   Bitwise unary complement
- @&   Bitwise AND
- @^   Bitwise exclusive OR
- @|   Bitwise inclusive OR
- @<<  Signed left shift
- @>>  Signed right shift

**Comment by mariuszgromada** [comment]
http://mathparser.org/mxparser-tutorial/bitwise-operators/
