### ISSUE TITLE
Syntax expression error when using a negative of negative 

### ISSUE THREAD

**Issue by patricioafernandes** [mariuszgromada/MathParser.org-mXparser#150]
### Issue title:
- syntax expression error when using a negative of negative 

### Issue content:
The parser returns a syntax expression error when using a negative of negative (i.e., --10)
The workaround it is to use -(-10) expression.
 
#### If bug/question:
- MathParser.org-mXparser verssion: v.4.2.1.
- Framework: .net 4.6.2.
- Problem description
Returns a syntax expression error when using a negative of negative (i.e., --10)
- Code example

#### If new feature
- Feature description
- Use case description

**Comment by mariuszgromada** [comment]
mXparser is a math parser, in math -- is out of conventions
