### ISSUE TITLE
Syntax expression error when using a positive and negative

### ISSUE THREAD

**Issue by patricioafernandes** [mariuszgromada/MathParser.org-mXparser#151]
### Issue title:
Syntax expression error when using a positive and negative (i.e., 10 + -20 - +30)

### Issue content:
The parser returns a syntax expression error when using a positive and negative (i.e., 10 + -20 - +30)
the workaround is to use the expression 10 + (-20) - (+30)

#### If bug/question:
- MathParser.org-mXparser verssion: v.4.2.1
- Framework: .net 4.6.2
- Problem description
- Code example

#### If new feature
- Feature description
- Use case description

**Comment by mariuszgromada** [comment]
mXparser is a math parser, in math +-, -+, ++, -- is out of conventions
