### ISSUE TITLE
Endless Loop with missing initial value on plus operator, but passes checkSyntax

### ISSUE THREAD

**Issue by binaryjorgie** [mariuszgromada/MathParser.org-mXparser#153]
### Issue title:
Endless Loop with missing initial value  on plus operator, but passes checkSyntax

### Issue content:
When calculating an expression that has no initial value then an plus operator then a space and then a value, an endless loop is triggered.

#### If bug/question:
- MathParser.org-mXparser verssion: 4.2.1
- Framework: .net core 2.0
- Problem description
We are allowing users to enter formulas, and running checkSyntax before saving and executing them.  The entry of + 5 or + 1.5 passes checkSyntax and checkLexSyntax but on calculate it gets stuck in an infinite loop.  Entry of +5 works, - 5 works, -5 works.  Just with the plus operator.

- Code example
```
var e = new Expression("+ 5");
Console.WriteLine($"checkSyntax: {e.checkSyntax()}");
Console.WriteLine($"checkLexSyntax: {e.checkLexSyntax()}");
e.setVerboseMode();
mXparser.setConsolePrefix("");
mXparser.consolePrintTokens(e.getCopyOfInitialTokens());
var y = e.calculate();
```
Output:

```
checkSyntax: True
checkLexSyntax: True
 --------------------
| Expression tokens: |
 ---------------------------------------------------------------------------------------------------------------
|    TokenIdx |       Token |        KeyW |     TokenId | TokenTypeId |  TokenLevel |  TokenValue |   LooksLike |
 ---------------------------------------------------------------------------------------------------------------
|           0 |           + |           + |           1 |           1 |           0 |         NaN |             |
|           1 |           5 |       _num_ |           1 |           0 |           0 |           5 |             |
 ---------------------------------------------------------------------------------------------------------------

[][+ 5]
[][+ 5] Starting ...
[][+ 5] Parsing (0, 1)  ---> + 5  ...  ---> + 5  ...  done
[][+ 5] Parsing (0, 1)  ---> + 5  ...  ---> + 5  ...  done
[][+ 5] Parsing (0, 1)  ---> + 5  ...  ---> + 5  ...  done
[][+ 5] Parsing (0, 1)  ---> + 5  ...  ---> + 5  ...  done
[][+ 5] Parsing (0, 1)  ---> + 5  ...  ---> + 5  ...  done
[][+ 5] Parsing (0, 1)  ---> + 5  ...  ---> + 5  ...  done
[][+ 5] Parsing (0, 1)  ---> + 5  ...  ---> + 5  ...  done
[][+ 5] Parsing (0, 1)  ---> + 5  ...  ---> + 5  ...  done
[][+ 5] Parsing (0, 1)  ---> + 5  ...  ---> + 5  ...  done
```
And keeps continuing

**Comment by ArielAltamirano** [comment]
Hello,

In JAVA version 4.2.0 I found the same issue.

Also this one produces the same infinite loop:

`Expression exp = new Expression("+sqrt(1)");`

It sounds the + causes the issue because,

 ` Expression exp = new Expression("-sqrt(1)");`

works fine.

**Comment by ArielAltamirano** [comment]
I think something similar it's done with the minus, should be done with the plus. The following change fixed the problem:

`diff --git a/CURRENT/java/src/org/mariuszgromada/math/mxparser/Expression.java b/CURRENT/java/src/org/mariuszgromada/math/mxparser/Expression.java
index 1462e13..59a7146 100644
--- a/CURRENT/java/src/org/mariuszgromada/math/mxparser/Expression.java
+++ b/CURRENT/java/src/org/mariuszgromada/math/mxparser/Expression.java
@@ -5496,7 +5496,7 @@ public class Expression {
                                                        if ( (token.tokenId == Operator.MOD_ID) && (modPos < 0) && (leftIsNumber && rigthIsNumber)) {
                                                                modPos = pos;
                                                        } else
-                                                       if ( (token.tokenId == Operator.PLUS_ID)  && (plusPos < 0) && (leftIsNumber && rigthIsNumber))
+                                                       if ( (token.tokenId == Operator.PLUS_ID)  && (plusPos < 0) && (leftIsNumber))
                                                                plusPos = pos;
                                                        else
                                                        if ( (token.tokenId == Operator.MINUS_ID)  && (minusPos < 0) && (rigthIsNumber))
@@ -7521,4 +7521,4 @@ public class Expression {
                        newExp.initialTokens = createInitialTokens(0, initialTokens.size()-1, initialTokens);
                return newExp;
        }
-}
\ No newline at end of file
+}`

Thanks!

**Comment by mariuszgromada** [comment]
This will be fixed soon. Thank you!

**Comment by mpellicer** [comment]
I found the same issue evaluating this:

sin(+(1.2))

Thanks for working on this!

**Comment by mariuszgromada** [comment]
In mathematics generally +1, +2 syntax is awkward, where -1, -2 is naturally present. Anyway, I will introduce the change to support that. Additionally I will eliminate the endless loop problem for any case.

**Comment by mpellicer** [comment]
Thank you @mariuszgromada !

**Comment by emobtech** [comment]
I've also found the same problem with this simple expression: **+(1)**

Thanks for looking into this @mariuszgromada. Awesome library, btw.

**Comment by mariuszgromada** [comment]
Thx, I am currently working on something else, in a few days I will fix this problem, but I need to have some time for that

**Comment by mariuszgromada** [comment]
Fixed

**Comment by mpellicer** [comment]
Thank you so much @mariuszgromada ! Do you have in mind releasing 4.2.1 with these fixes? We integrate the library using maven.

Thanks again for the tremendous effort!

**Comment by mariuszgromada** [comment]
I will release 4.3.0 as I implemented already some additional features. Do you have any expectation in terms of date of release? Is it important to have it very fast? If not I will do that in the next few days (1-2 weeks).

Best regards

**Comment by ArielAltamirano** [comment]
Amazing!. Thanks!

**Comment by mariuszgromada** [comment]
Additionally I implemented a generic internal endless loop check - in case other similar bugs library will return Doble.NaN with proper error message in Expression e.getErrorMessage()

Additionally I introduced another option for multithreading support - mXparser.cancelCurrentCalculation(). Please refer to https://github.com/mariuszgromada/MathParser.org-mXparser/issues/162

This option, in case you start calculation in one thread, will allow to stop the calculation form another thread.

Best regards

**Comment by mariuszgromada** [comment]
I you are happy with the change, a repo star is more than welcome :-)

**Comment by emobtech** [comment]
Bravo! Thanks for taking care of it so readily. A two weeks time window for the release suits well for our sprint conclusion.

**Comment by mariuszgromada** [comment]
@mpellicer, @emobtech, @ArielAltamirano, 4.3.0 released both nuget and maven :-)

**Comment by mpellicer** [comment]
Thanks!
