### ISSUE TITLE
Spreadsheet or common place to store Arguments

### ISSUE THREAD

**Issue by YandyZaldivar** [mariuszgromada/MathParser.org-mXparser#154]
Hello, what about the Spreadsheet support mentioned in #4 ?

My use case is that I have a table and I want to associate an Argument/Expression to potentially every cell. The cells get added or removed dynamically. Besides this grid, I also have other external Arguments as variables that I want to use in the cells formula. The problem here is how to add dependent arguments in a common place that are recognized without having to pass every Argument as each other dependent Argument. In this common place I should be able to add and remove arguments as the cells get added/removed.

I am new to this library so maybe there is already a way to accomplish this.

The current workaround I am thinking of is to maintain a list of every defined argument and then after every addition/deletion update all argument dependencies with the remaining, despite if they use it or not. My fear hear is that this turn soon into a performance problem, because of the non-conventional way of doing it.

**Comment by mariuszgromada** [comment]
Still I did not started to work on that. The best way would be to have a common shared space for user defined elements. The shared space is always used when user defines new element, so there is no need to provide the references to the objects.

**Comment by YandyZaldivar** [comment]
Thanks, by a shared space are you referring to some built-in functionality? Can you point to some basic code or docs that refer to it?

**Comment by mariuszgromada** [comment]
No, rather to a change in the architecture of mXparser. Currently each expression is treated totally separately, with its own arguments, constants, functions list. The solution would have to provide common shared space..

**Comment by YandyZaldivar** [comment]
Ok, waiting for it.

**Comment by prabhakarbcrec** [comment]
how I will get the abstract syntax tree from  mxParser of given expression like: -` **add(a,b)+multi(c,add(f,z))**`

**Comment by judos** [comment]
Hi, I think I got the same issue with a possible solution:

I have an Excel sheet with 100 values q(1) - q(100) which are given from statistics. Now I want to use those as arguments.

My work around would be to define a custom function which returns the given constants:
(If useful you could even define interpolation on those values)
```java
double[] values = { 0, 1, 2, 3, 4, 5 };
Function h = ArrayFunction.build("h", values);
Argument x = new Argument("x = 1");
Expression e = new Expression("h(x)", h, x);
System.out.println("Res: " + e.getExpressionString() + " = " + e.calculate());
		
x.setArgumentValue(6); // index out of array
System.out.println("Res: " + e.getExpressionString() + " = " + e.calculate());
System.out.println(h.getErrorMessage());
```

Example output:
```
Res: h(x) = 1.0
Exception in thread "main" java.lang.RuntimeException: index 6 is disallowed for the function h which has only entries 0 - 5
```

Implementation ArrayFunction.java:
```java
import org.mariuszgromada.math.mxparser.Function;
import org.mariuszgromada.math.mxparser.FunctionExtension;

public class ArrayFunction implements FunctionExtension {

	public static Function build(String name, double[] arr) {
		ArrayFunction extension = new ArrayFunction(name, arr);
		return new Function(name, extension);
	}

	private double[] arr;
	private int param;
	private String name;

	private ArrayFunction(String name, double[] arr) {
		this.name = name;
		this.arr = arr;
	}

	@Override
	public int getParametersNumber() {
		return 1;
	}

	@Override
	public void setParameterValue(int parameterIndex, double parameterValue) {
		if (parameterIndex > 0) {
			throw new RuntimeException("Parameter index must not be greater than 0");
		}
		int p = (int) Math.floor(parameterValue);
		if (parameterValue != p || Double.isInfinite(parameterValue)) {
			throw new RuntimeException("Parameter must be an integer");
		}
		if (p >= this.arr.length) {
			throw new RuntimeException("index " + p + " is disallowed for the function " + this.name
				+ " which has only entries 0 - " + (this.arr.length - 1));
		}
		this.param = p;
	}

	@Override
	public String getParameterName(int parameterIndex) {
		return "arrIndex";
	}

	@Override
	public double calculate() {
		return this.arr[this.param];
	}

	@Override
	public FunctionExtension clone() {
		return new ArrayFunction(this.name, this.arr);
	}
}

```

**Comment by mariuszgromada** [comment]
Yes, great, this is why function extension was created for :-)
