### ISSUE TITLE
Using "," and "." in the same equation

### ISSUE THREAD

**Issue by patricioafernandes** [mariuszgromada/MathParser.org-mXparser#155]
### Issue title:
using "," and "." in the same equation

### Issue content:
Is it possbile to use "'" and/or "." in the same equation? 
Example: (5,1)+(2.3)

#### If bug/question:
- MathParser.org-mXparser verssion: v.X.Y.Z
- Framework: .net
- Problem description
- Code example

#### If new feature
- Feature description
- Use case description

**Comment by mariuszgromada** [comment]
No, comma is the function parameter separator.
