### ISSUE TITLE
Matrix Operations

### ISSUE THREAD

**Issue by Olloxan** [mariuszgromada/MathParser.org-mXparser#156]
Is there any possible way to extend the functionality of this parser to matrix operations? I have been trying this for the past weeks but it´s not easy make changes to the source code without damaging the functionality of the parser.

**Comment by mariuszgromada** [comment]
Hi, unfortunately this is not an easy thing. Parser was designed for real data types only. The whole match collection is prepared just for that. This is not a problem to parse the strings passed by the user, but then you need to have all the functions implemented for real double type and for the matrix data types. In fact it would mean the assumption that everything is a matirx, even a single real number.

**Comment by Olloxan** [comment]
As of right now I am trying to refactor the code and split it into multiple classes to separate the different steps of computing the Expressionstring. My plan is to have one class for task, like checking syntax, tokenize expressionstring and evaluate the result. I then want to derive the evaluation class to get it for matrix operations to work. Unfortunately there are many dependencies to fields within the class that have to be resolved first. I added a unittest project from the examples to keep track of any possible damaging refactorings.
