### ISSUE TITLE
Nuget package adds HTML documentation

### ISSUE THREAD

**Issue by Cronan** [mariuszgromada/MathParser.org-mXparser#157]
Adding the Nuget package adds a lot of HTML documentation into the project. This is especially unfriendly if the package is brought in as a dependency.
Can this approach be rethought please, with a view to removing the help?

**Comment by mariuszgromada** [comment]
It cna be remooves preatty easly, but please note that mXparser is created in Javam then ported to .net direclty. In the C# src there are no xml comments.

The help is also provided at mathparser.org - so maybe it is enough

I would like to have point of view from other users. 

Best regards

**Comment by Cronan** [comment]
Thanks for the quick response

**Comment by mariuszgromada** [comment]
Nuget package updated, not html doc included

**Comment by Cronan** [comment]
Great, thank you
