### ISSUE TITLE
Solving Linear equations with one variable

### ISSUE THREAD

**Issue by kishor-p** [mariuszgromada/MathParser.org-mXparser#159]
#### Question:
- MathParser.org-mXparser verssion: v.4.2.0
- Framework: java
- Hello I have been trying to use this library for solving a simple algebraic equation to find value of one variable.
For Example:
x*1/40+5=12

None of  the demo or documentations are clear enough to solve this simple equation. May the library is capable of solving this. But there is no clear documentation. Please point me to right direction if it can do this already. 
-  Here are some other similar expressions:

-     x*1/40+5 = 12.45
-     x*635/(27*1024) = 52
-     x^2-3.4/6 = 43
-     3+logx-13 = 15

**Comment by mariuszgromada** [comment]
mXparser implements numerical solving, there is a section in the tutorial
http://mathparser.org/mxparser-tutorial/solving-equation-fx-0/

**Comment by kishor-p** [comment]
> 
> 
> mXparser implements numerical solving, there is a section in the tutorial
> http://mathparser.org/mxparser-tutorial/solving-equation-fx-0/

Hello, glad to hear from you.
The example you pointed out solves the function where there could be 2 possible values for x.

Not sure how to apply this to my equation. For Example:
x*1/40+5 = 12

After solving the value for x would be 280.

Please advise.

**Comment by mariuszgromada** [comment]
Just a simple hint
`f(x) = a`
is equivalent to
`f(x) - a = 0`

Best regards

**Comment by mariuszgromada** [comment]
```
		Expression e1 = new Expression("solve( x/40 + 5 - 12.45, x, -10000, 10000 )");
		Expression e2 = new Expression("solve( x*635/(27*1024) - 52, x, -10000, 10000 )");
		Expression e3 = new Expression("solve( x^2-3.4/6 - 43, x, -100, 100 )");
		mXparser.consolePrintln(e1.getExpressionString() + " = " + e1.calculate());
		mXparser.consolePrintln(e2.getExpressionString() + " = " + e2.calculate());
		mXparser.consolePrintln(e3.getExpressionString() + " = " + e3.calculate());
```
