### ISSUE TITLE
 Negative sign missing when is right of operators

### ISSUE THREAD

**Issue by xchunzhao** [mariuszgromada/MathParser.org-mXparser#16]
I think this is a bug.
I try to test '1<-2' , it should return 0/false, but it return 1.00/true

**Comment by mariuszgromada** [comment]
Bug found and fixed - new version will be released soon

**Comment by mariuszgromada** [comment]
This is doe to the "<-        <Boolean Operator>      converse implication (CIMP)"

1<-2 is interpreted as 1 CIMP 2

**Comment by xchunzhao** [comment]
Thanks ! Wish to see the new version
