### ISSUE TITLE
NaN for expression: x*2/(5-(x*3))-12.0

### ISSUE THREAD

**Issue by kishor-p** [mariuszgromada/MathParser.org-mXparser#160]
### Issue title:
- Getting Nan for Expression Res: x*2/(5-(x*3))-12.0

#### If bug/question:
- MathParser.org-mXparser verssion: v.4.2.0
- Framework: java
- Getting NaN when calculating value from Expression 
- Code Sample
```
Expression e = new Expression("solve(x*2/(5-(x*3))-12.0,x,-10000,100000)");
System.out.println("Res: " + e.getExpressionString() + " = " + e.calculate());
```

**Comment by mariuszgromada** [comment]
This is because `f(x)=x*2/(5-(x*3))-12.0` is negative in `f(-10000)` and negative in `f(100000)`, so numerical algorithm can not solve that. You need to adjust the range from and range to parameters, so that the signs are different, to be sure the function root is inside

try
```
Expression e = new Expression("solve(x*2/(5-(x*3))-12.0,x,0,2)");
System.out.println("Res: " + e.getExpressionString() + " = " + e.calculate());
```

**Comment by kishor-p** [comment]
It works.
Again I am really glad and humbled that you are responding to my questions.

Just one questions tho. I know it's a math question but I just cant help it.
How do I choose the dynamic function roots based on expression?

**Comment by mariuszgromada** [comment]
I think I do not understand the question. What do you mean by dynamic function roots?
