### ISSUE TITLE
Add support for user defined units, or allow constants to have square brackets

### ISSUE THREAD

**Issue by zeelux** [mariuszgromada/MathParser.org-mXparser#161]
### Issue title:
- I would like to be able to extend the built-in units by adding my own.

### Issue content:
Built-in units use the syntax `[unit]`. I would like to add my own units following that syntax (including the square brackets) for consistency. This could be implemented as the ability to add custom units, or as simply allowing square brackets around custom constants.

- MathParser.org-mXparser version: v 4.2.2
- Framework: .net core 2.1

Ideally I think it would be nice to have a new method on Expression class to add a unit to the expression. Something like:
```C#
    void Expression.addUnits(params Unit[] units);
```
or perhaps on mXparser class.
```C#
    void mXparser.addCustomUnits(params Unit[] units);
```
**Assuming a Unit class exists or is created :)

My use case specifically is that we need a constant for year that does not count for leap days. The built-in unit for years `[yearj]` = 365.25 days, but for my purposes a value of 365 days would be preferred in some cases. I don't want to override the value of the built-in constant as I'd like to have both available.

I tried mimicking this functionality by simply adding the units as constants but when adding a constant where the name is surrounded by square brackets, the parser throws an InvalidOperationException.
```c#
    // note "[years]" is not a built-in constant "[yearj]" is.
    var expression = new Expression("( 1 * [years] ) / [h]");

    Constant years = new Constant("[years]", 60 * 60 * 24 * 365);
    expression.addConstants(years);
    // the next line throws error
    var tokens = expression.getCopyOfInitialTokens();

    // won't get here.
    var val = expression.calculate();
```

```text
System.InvalidOperationException
  HResult=0x80131509
  Message=Failed to compare two elements in the array.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.List`1.Sort(Int32 index, Int32 count, IComparer`1 comparer)
   at org.mariuszgromada.math.mxparser.Expression.tokenizeExpressionString()
   at org.mariuszgromada.math.mxparser.Expression.getCopyOfInitialTokens()

Inner Exception 1:
NullReferenceException: Object reference not set to an instance of an object.
```

As a work around for now I can replace the token myself so the user could still use e.g. `[years]` in the calculation but then I would replace it with a different token name before running the calculation.
```C#
    var expression = new Expression("( 1 * [years] ) / [h]");

    Constant years = new Constant("__years__", 60 * 60 * 24 * 365);
    expression.addConstants(years);

    var sbRewrittenEquation = new StringBuilder();
    var tokens = expression.getCopyOfInitialTokens();
    foreach (var token in tokens)
    {
        if (token.tokenStr == "[years]")
        {
            sbRewrittenEquation.Append("__years__");
        }
        else
        {
            sbRewrittenEquation.Append(token.tokenStr);
        }
    }

    // get new list of tokens after modifications
    expression.setExpressionString(sbRewrittenEquation.ToString());

    tokens = expression.getCopyOfInitialTokens();
    mXparser.consolePrintTokens(tokens);


    var result = expression.calculate();
    Console.WriteLine($"Result: {result}");
```

**Comment by mariuszgromada** [comment]
Thx. I will aloow [] in user defined constants. This will be in the next release.

**Comment by zeelux** [comment]
Thanks that will work for me. Also thanks for the quick reply :)

**Comment by mariuszgromada** [comment]
Done :-)

**Comment by zeelux** [comment]
Awesome thanks!
