### ISSUE TITLE
Constructor Error when calling DLL from Python using Pythonnet

### ISSUE THREAD

**Issue by boustrephon** [mariuszgromada/MathParser.org-mXparser#165]
### Issue title:
Problems using DLL from Pythonnet (not a real "Issue" because I am using it in a way that it was not meant to be used). 

### Issue content:
I have compiled the DLL using Visual Studio Express 2015 for Desktop under the .NET Framework 4.5.2 (I did not choose the option to make it COM-visible).

When I load the DLL and call it from python using pythonnet, it loads without complaint, but then I get a constructor error when I call the Expression Class (which seems strange, because I am simply passing it a string):
```python
import clr  
dllpath = r'C:\...\GitHub\MathParser.org-mXparser\CURRENT\c-sharp\bin\Release\MathParser.org-mXparser.dll'
import org.mariuszgromada.math.mxparser as mx
expr_01 = mx.Expression('2 + 1')
```
`TypeError: no constructor matches given arguments`

I ran the 'tutorial' and it sent output to the console without any problem:
```
pe = mx.Tutorial()
pe.Start()
```
Do you have any idea of what I could try next?

PS Great tool - thank you for sharing it!

[Question on StackOverflow](https://stackoverflow.com/questions/53846574/constructor-error-using-mxparser-with-pythonnet)

#### If bug/question:
- MathParser.org-mXparser version: v.4.3.0
- Framework: java, .net, .net core, .net standard, Xamarin, Android, iOS ... + framework verssion
- Problem description
- Code example

#### If new feature
- Feature description
- Use case description

**Comment by mariuszgromada** [comment]
Hi,

Thank you for your feedback :-) I do not know the Pythonnet package, but maybe you are facing String problem? Have you been trying 

`mx.Expression("2 + 1")`

?

Best regards

**Comment by mariuszgromada** [comment]
So I am unable to help with python, sorry
