### ISSUE TITLE
Issue while having user-defined function and arguments [help wanted]

### ISSUE THREAD

**Issue by Uday8486** [mariuszgromada/MathParser.org-mXparser#166]
## Issue title:
Issue while having user-defined function and arguments 
### Issue content:
I have a expression which requires a user defined function and some arguments which are to be passed. I am using Java library and have written below code

When I run this I expect the output value as 400 but instead I get the value as NaN
#### If bug/question:
- Does the order in which argument and function are passed matter?
- Here is code written.
`String formulaExpression = "IF(W1R11 == 0 || W1R12 == 0,0,(DIV((W1R11 - W1R12),W1R12) * 100))";
        Argument W1R11 = new Argument("W1R11 = 10");
        Argument W1R12 = new Argument("W1R12 = 2");
        System.out.println("W1R11 = "+W1R11.getArgumentValue());
        System.out.println("W1R12 = "+W1R12.getArgumentValue());
        //IF(W:R11 == 0 || W:R12 == 0,0,(DIV((W:R11 - W:R12),W:R12) * 100))
        Expression e = new Expression(formulaExpression, W1R11, W1R12, calculationFunctions.DIV());  //defined the functions in separate java class
        System.out.println(e.calculate());`

#### If new feature
- Help Wanted
P.S: Sorry I am not sure why the code tag did not format my sample code in proper code block above.

**Comment by Uday8486** [comment]
I got the issue, IF function is to be written in lower case.

**Comment by mariuszgromada** [comment]
yes, mXparser is case specific :-)
