### ISSUE TITLE
Integer calculation help wanted

### ISSUE THREAD

**Issue by ramteke** [mariuszgromada/MathParser.org-mXparser#167]
### Issue title:
Operations for Integer values

### Issue content:
Is there any flag/option available to ensure that input dataType is maintained. Example: division between two integers produces  integer output.

In python, an integer division can be done using '//' operator. Example
>>> 1/4
0.25     <-- python floating point division

>>> 1 // 4
0         <-- python integer division
>>>

Is similar facility available with MathParser ? 

#### If bug/question:
- MathParser.org-mXparser verssion: 4.2.0
- Framework: java

#### If new feature
- Feature description
- Use case description

**Comment by mariuszgromada** [comment]
Hi,

mXparser has one data type - it is based on double

You can apply round functions, available in mXparser.

Best regards
