### ISSUE TITLE
Rounding Not Working

### ISSUE THREAD

**Issue by ZakirSheikh** [mariuszgromada/MathParser.org-mXparser#168]
### Issue title:
- Rounding

### Issue content:
After Setting mXparser.enableAlmostIntRounding();
# I am still getting sin(30 degrees) equal to 0.4999999999999...
# Their is no tutorial available about adding custom operator like sqrt √
# Their is no function available for mXparser.setGradianmode.

BTW Thanks for this parser it is great only one of its kind AFAIK.

 

#### If bug/question:
- MathParser.org-mXparser verssion: v.X.Y.Z
- Framework: java, .net, .net core, .net standard, Xamarin, Android, iOS ... + framework verssion
- Problem description
- Code example

#### If new feature
- Feature description
- Use case description

**Comment by ZakirSheikh** [comment]
Here is my Code
mXparser.setDegreesMode();
            mXparser.disableUlpRounding();
            mXparser.enableAlmostIntRounding();
            Expression e = new Expression(exp);
            Result = e.calculate();

**Comment by mariuszgromada** [comment]
Hi,

`mXparser.setRadiansMode()` is availabe

`sin(30 degress)` is in fact `sin(30 * degress2radians),` and this is a numerical implementation of sine approximation, check `Math.sin() `in java or `Math.Sin()` in .net, you will get the same results.

mXparser provides `sqrt(x)` function or `root(n,x)` function. As of now there is no option to add custom operators, but there is an option to add custom function based on your implementation, please refer to the linked example "Case 5: Implementing your own Function Extension"

http://mathparser.org/mxparser-tutorial/user-defined-functions/

Best regards

**Comment by ZakirSheikh** [comment]
Hello sir I just currently came across arity math library by Google .
It has a nice function which checks if the value to be calculated is int. May be u might find it use fulhere is the link.
https://github.com/Xlythe/Arity/blob/master/src/org/javia/arity/Util.java

**Comment by mariuszgromada** [comment]
But your value is 0.5, this is not a int. For the almost int you have an option in mXparser that you even used.

**Comment by ZakirSheikh** [comment]
It solved my issues. I found another solution to my problem. I am currently using exp4j parsr. In it I can add custom operatos functions etc. Before passing argument to sin. Cos tan I can intercept it and return special value at that anglelike 0.5 1 etc.

The Google caluatorlatest version uses Bigdecimal. They also have created a solution to this but I can figure out what they have done.

**Comment by mariuszgromada** [comment]
So - it is preatty simple to do the same in mXparser - just use FunctionExtension, please see the below example:

```
class MyOwnSin implements FunctionExtension {

	double x;

	public int getParametersNumber() {
		return 1;
	}

	public void setParameterValue(int parameterIndex, double parameterValue) {
		if (parameterIndex == 0) x = parameterValue;
	}

	public String getParameterName(int parameterIndex) {
		if (parameterIndex == 0) return "x";
		return "";
	}

	public double calculate() {
		if (x == -180) return 0;
		if (x == -150) return -0.5;
		if (x == -90) return -1;
		if (x == -30) return -0.5;
		if (x == 0) return 0;
		if (x == 30) return 0.5;
		if (x == 90) return 1;
		if (x == 150) return 0.5;
		if (x == 180) return 0;
		return Math.sin(x * Units.DEGREE_ARC);
	}

	public FunctionExtension clone() {
		return this;
	}

}

mXparser.setToOverrideBuiltinTokens();
		
Function sin = new Function("sin", new MyOwnSin());
		
Expression e0 = new Expression("sin(0)", sin);
Expression e30 = new Expression("sin(30)", sin);
Expression e90 = new Expression("sin(90)", sin);
		
mXparser.consolePrintln(e0.getExpressionString() + " = " + e0.calculate());
mXparser.consolePrintln(e30.getExpressionString() + " = " + e30.calculate());
mXparser.consolePrintln(e90.getExpressionString() + " = " + e90.calculate());
```

Result
```
[mXparser-v.4.3.0] sin(0) = 0.0
[mXparser-v.4.3.0] sin(30) = 0.5
[mXparser-v.4.3.0] sin(90) = 1.0
```

**Comment by mariuszgromada** [comment]
#194
