### ISSUE TITLE
Is there a way to disable all built in constants?

### ISSUE THREAD

**Issue by VanCoding** [mariuszgromada/MathParser.org-mXparser#169]
- MathParser.org-mXparser verssion: 4.2.2
- Framework: .net core

Is there a way to disable all built in constants, so that when calling
```cs
expression.getMissingUserDefinedArguments()
```
 returns the names of all variables, and not just the ones that are not a built in constant?

For example, 
```cs
new Expression("(r^2)*pi").getMissingUserDefinedArguments()
```
gives me ["r"], but I want it to give me ["r","pi"]. I've seen that there's a private parameter called `parserKeyWordsOnly` which in my opinion should do what I want, so I've tried setting it through reflection to true. And indeed, it now gives me the expected result, but when I call `calculate()` on the expression then, it gives me "NaN", while before setting `parserKeyWordsOnly`, it did calculate fine.

Here's the code of my test:
```cs
using System;
using System.Linq;
using org.mariuszgromada.math.mxparser;
using System.Reflection;
					
public class Program
{
	public static void Main()
	{
		var formula = new Expression("(r^2)*pi");
		Console.WriteLine(string.Join(",",formula.getMissingUserDefinedArguments()));
		typeof(Expression).GetField("parserKeyWordsOnly",BindingFlags.NonPublic|BindingFlags.GetField|BindingFlags.Instance).SetValue(formula,true);
		Console.WriteLine(string.Join(",",formula.getMissingUserDefinedArguments()));
		formula.addArguments(new Argument("r",1));
		formula.addArguments(new Argument("pi",2));
		Console.WriteLine(formula.calculate());
	}
}
```

And a link to a .NET Fiddle: https://dotnetfiddle.net/FC64E1

So my question is now: Is there a correct (less hacky) way to do this, so that calulation still works afterwards? And is it maybe possible to **only** disable built in constants, and keep built in functions?

If not, would it be hard to implement it?

**Comment by mariuszgromada** [comment]
Hi,

Indeed, you used a really hacky way :-) Please use:

`mXparser.removeBuiltinTokens(tokens)`

where tokens is a tokens list that you are going to remove. You can collect built-in constants using

`List<KeyWord> keyWordsList= mXparser.getKeyWords();`

Each key word has `wordTypeId` field, then check against 

`wordTypeId  == ConstantValue.TYPE_ID`

and pickup the `wordString`

Bes regards,
Mariusz

**Comment by VanCoding** [comment]
Thanks, that worked :)
