### ISSUE TITLE
No Operator between Argumant and Parentheses

### ISSUE THREAD

**Issue by Sourcenew** [mariuszgromada/MathParser.org-mXparser#170]
### Issue title:
- No Operator between Argumant and Parentheses

#### If bug/question:
- MathParser.org-mXparser verssion: v.X.Y.Z
- Framework:  .net, .net core
- Problem description:
i have two argumant: Salary=200,Day=2
My Expression is: Salary (Day)
checkSyntax and checkLexSyntax return true.
but is not true. no operator between salary and Parentheses

when i call  calculate, it's goes to endless proceess loop
- Code example

<img src="https://i.imgur.com/ZWqCZAnl.png" width="100%" />

**Comment by mariuszgromada** [comment]
Thank you, indeed this is a bug :-) In the version 4.3 there is no endless loop problem, it was fixed, anyway checkSyntax() should not return true.

**Comment by mariuszgromada** [comment]
Please use Nuget package - this will solve the infinite loop problem. Final fix will be soon.

**Comment by Sourcenew** [comment]
thank you for your fast response dear

**Comment by mariuszgromada** [comment]
fixed

**Comment by Sourcenew** [comment]
you are incredible. thank you

**Comment by Sourcenew** [comment]
dear. i updated my  lib to version 4.32
but it's already exist.
when you want to update nugget packages? thank you again

**Comment by mariuszgromada** [comment]
Src was fixed, now I need to prepare maven and nuget, should be tomorrow.

**Comment by mariuszgromada** [comment]
I made a present for you - Nuget package has just been published :-) Please wait 10-20 minutes - this is due to nuget indexing.

Best regards

**Comment by Sourcenew** [comment]
you are best programmer ever :-*

**Comment by mariuszgromada** [comment]
No checkSyntax should return false, where checkLexSyntax should return true :-) It was w tiny bug :-)

Please do not forget on repo star :-)

**Comment by Sourcenew** [comment]
you have my star from first day...
after selling first version of my product i will donate too for this good project

**Comment by mariuszgromada** [comment]
Thank you :-)

**Comment by Sourcenew** [comment]
thank you for you dear.

**Comment by mariuszgromada** [comment]
Maybe you will be interested

Scalar Lite: https://play.google.com/store/apps/details?id=org.mathparser.scalar.lite
Scalar Pro: https://play.google.com/store/apps/details?id=org.mathparser.scalar.pro

I made it based on mXparser

**Comment by mariuszgromada** [comment]
Please let me know if it works for you

**Comment by Sourcenew** [comment]
Its work for me dear, thank you,

But about your android application, when i want to get 5 star to it, i see this app not acceptable in your country (iraq)

**Comment by mariuszgromada** [comment]
I do not know the Google policy, it might that there are some legal issue to sell paid apps in Iraq :-(

Please check the free versions: 
Scalar Lite: https://play.google.com/store/apps/details?id=org.mathparser.scalar.lite
