### ISSUE TITLE
Wrong result for formula "x + 4 * - 2". 

### ISSUE THREAD

**Issue by AlexMatsyuk** [mariuszgromada/MathParser.org-mXparser#172]
Wrong operations order, if there is space between "-" and "2" in formula "x + 4 * - 2".

If **x=20** and formula is
**"x + 4 * - 2"**, then result is **"-48"**

If there are no space
**"x + 4 * -2"**, then result is correct **"12"**

**Comment by mariuszgromada** [comment]
Thx, this is a bug. Anyway, 4*-2 this syntax is mathematically incorrect, should be 4*(-2) - this is the correct math convention.

Best regards

**Comment by jonespm** [comment]
This looks similar to the bug on #130

**Comment by mariuszgromada** [comment]
Fixed :-)
