### ISSUE TITLE
How i will get Abstract Syntax tree of any given expression through mxParser

### ISSUE THREAD

**Issue by prabhakarbcrec** [mariuszgromada/MathParser.org-mXparser#173]
### Issue title:
- Short and meaningfull

#### If bug/question:
- MathParser.org-mXparser verssion: v.X.Y.Z
- Framework: java, .net, .net core, .net standard, Xamarin, Android, iOS ... + framework verssion
- Problem description
- Code example

#### If new feature
- Feature description
- Use case description

**Comment by prabhakarbcrec** [comment]
I want AST through mxParser of any expression
is it possible?

**Comment by mariuszgromada** [comment]
Hi, sorry for late response, I think i forgot to answer.

Please see the tutorial here - this can be used to create AST
http://mathparser.org/mxparser-tutorial/playing-with-expression-tokens/

Best regards
