### ISSUE TITLE
mXparser manage also strings ?

### ISSUE THREAD

**Issue by mtugnoli** [mariuszgromada/MathParser.org-mXparser#174]
This is your sample

Argument x = new Argument("x = 5");
Expression e = new Expression("if(sin(x) > 5, 1, 0)", x);
e.calculate();

Is it possible also ?

Argument x = new Argument("x = 5");
Expression e = new Expression("if(sin(x) > 5, "ONE", "ZERO")", x);
e.calculate();

**Comment by mariuszgromada** [comment]
Unfortunately strings are not supported, e calculate always returns double. 

Best regards
