### ISSUE TITLE
Possible wrong result from calculate function

### ISSUE THREAD

**Issue by IdanVT** [mariuszgromada/MathParser.org-mXparser#178]
### Issue title:
Possible wrong result from calculate function

#### If bug/question:
- MathParser.org-mXparser verssion: v.4.3.3
- Framework:.net, 4.6.1

Wrong boolean operators calculation order

`
Consider the following code:

                List<Argument> testArgs = new List<Argument>();
                testArgs.Add(new Argument("X1",0));
                testArgs.Add(new Argument("X2",1));
                testArgs.Add(new Argument("X3",1));
                testArgs.Add(new Argument("X4",1));
                testArgs.Add(new Argument("X5",1));
                testArgs.Add(new Argument("X6",0));
                Expression testExp = new Expression("(X1 & X2) | (X3 & X4) | X5 & X6", testArgs.ToArray()); 
                testExp.setVerboseMode();
                double ans = testExp.calculate();
                bool ans2 = (false && true) || (true && true) || true && false;

`
ans2 which is the equivalent expression return true
ans return 0 (false)

if i setVerboseMode I'm getting a wrong calculation order

Verbose output:

[][(X1 & X2) | (X3 & X4) | X5 & X6] Starting ...
[][(X1 & X2) | (X3 & X4) | X5 & X6] X1 = 0
[][(X1 & X2) | (X3 & X4) | X5 & X6] X2 = 1
[][(X1 & X2) | (X3 & X4) | X5 & X6] X3 = 1
[][(X1 & X2) | (X3 & X4) | X5 & X6] X4 = 1
[][(X1 & X2) | (X3 & X4) | X5 & X6] X5 = 1
[][(X1 & X2) | (X3 & X4) | X5 & X6] X6 = 0
[][(X1 & X2) | (X3 & X4) | X5 & X6] Starting calculation loop
[][(X1 & X2) | (X3 & X4) | X5 & X6] Parsing (0, 4)  ---> ( 0 & 1 )  ...  ---> ( 0 ) | ( 1 & 1 ) | 1 & 0  ...  done
[][(X1 & X2) | (X3 & X4) | X5 & X6] Parsing (0, 2)  ---> ( 0 )  ...  ---> 0 | ( 1 & 1 ) | 1 & 0  ...  done
[][(X1 & X2) | (X3 & X4) | X5 & X6] Parsing (2, 6)  ---> ( 1 & 1 )  ...  ---> 0 | ( 1 ) | 1 & 0  ...  done
[][(X1 & X2) | (X3 & X4) | X5 & X6] Parsing (2, 4)  ---> ( 1 )  ...  ---> 0 | 1 | 1 & 0  ...  done
[][(X1 & X2) | (X3 & X4) | X5 & X6] Parsing (0, 6)  ---> 0 | 1 | 1 & 0  ...  ---> 1 | 1 & 0  ...  done
[][(X1 & X2) | (X3 & X4) | X5 & X6] Parsing (0, 4)  ---> 1 | 1 & 0  ...  ---> 1 & 0  ...  done
[][(X1 & X2) | (X3 & X4) | X5 & X6] Parsing (0, 2)  ---> 1 & 0  ...  ---> 0  ...  done
[][(X1 & X2) | (X3 & X4) | X5 & X6] Calculated value: 0
[][(X1 & X2) | (X3 & X4) | X5 & X6] Exiting

as you can see there is a wrong order calculation in lines:
[][(X1 & X2) | (X3 & X4) | X5 & X6] Parsing (0, 6) ---> 0 | 1 | 1 & 0 ... ---> 1 | 1 & 0 ... done
[][(X1 & X2) | (X3 & X4) | X5 & X6] Parsing (0, 4) ---> 1 | 1 & 0 ... ---> 1 & 0 ... done

while it should be 
[][(X1 & X2) | (X3 & X4) | X5 & X6] Parsing (0, 6) ---> 0 | 1 | 1 & 0 ... --->  0 | 1 | 0 ... done
[][(X1 & X2) | (X3 & X4) | X5 & X6] Parsing (0, 6) ---> 0 | 1 | 0  ... ---> 1 | 0 ... done
[][(X1 & X2) | (X3 & X4) | X5 & X6] Parsing (0, 4) ---> 1 | 0 ... ---> 1 ... done
[][(X1 & X2) | (X3 & X4) | X5 & X6] Calculated value: 0
[][(X1 & X2) | (X3 & X4) | X5 & X6] Exiting

It also damage the performance, Because logically you could abort the calculation in line:
[][(X1 & X2) | (X3 & X4) | X5 & X6] Parsing (0, 6)  ---> 0 | 1 | 1 & 0  ...  ---> 1 | 1 & 0  ...  done
and return 1 as result

**Comment by mariuszgromada** [comment]
Thank you, but mXparser does not follow .net/java precedence. In general math there is no clear precedence defined for logical operators, the same is in case of natural language, thus you should always use parenthesis. I will consider precedence introduction.

Best regards

**Comment by mariuszgromada** [comment]
Fixed
