### ISSUE TITLE
Creating user-defined functions without arguments

### ISSUE THREAD

**Issue by krugman25** [mariuszgromada/MathParser.org-mXparser#179]
For our application we needed to be able to get the current time in seconds.  We currently use mXparser to build calculations and add new types of data points to our system, so it was natural to use mXparser for this purpose as well.

I created a FunctionExtension called Time.  The calculate() method then returns the DateTime.Now.Ticks converted to seconds.  This class doesn't need any parameters since it is just getting the system time.  This actually works great when I use it as a function and call time.calculate(), but it doesn't work when I use it as an expression `Expression e = new Expression("Time()", TimeFunction)`.  This express will return "NaN".  The only way I was able to get it to work was to add a dummy argument 'x' and then call the expression as `Expression e = new Expression("Time(0)", TimeFunction)`.  That is kind of a quirky solution.  Is there any way to call zero argument user-define functions in expressions.

**The class using the dummy argument**

    public class Time : FunctionExtension
    {
        private double x;

        public Time()
        {

        }

        public Time(double x)
        {
            this.x = x;
        }

        public void setParameterValue(int argumentIndex, double argumentValue)
        {
            if (argumentIndex == 1) this.x = argumentIndex;
        }

        public int getParametersNumber()
        {
            return 1;
        }

        public string getParameterName(int argumentIndex)
        {
            if (argumentIndex == 1) return "x";

            return string.Empty;
        }

        public double calculate()
        {
            return DateTime.Now.Ticks / TimeSpan.TicksPerSecond;
        }

        public FunctionExtension clone()
        {
            return new Time(this.x);
        }
    }

**Comment by mariuszgromada** [comment]
Hi,

In math there is now zero parameters functions. You defined 1-parameter function, then you call Time() - this is syntax error.

    public int getParametersNumber()
    {
        return 1;
    }

Use user defined argument to handle this case

Argument time = new Argument("time = Time(0)", TimeFunction);
Expression e = new Expression("time", time)

Best regards

**Comment by krugman25** [comment]
Marius,

That snippet is the class I had to create to make it work.  Earlier in my post I stated that I made a zero parameter class that didn’t work, it results in a NaN.

I had the code as


public int getParametersNumber()

{

    return 0;

}

I didn’t set up the argument as you have listed though, I just set it up as “Time()”, which is probably why it didn’t work,  I will test out the way you describe here.

Thank you!

-Aaron Kruger

**Comment by pci-wardeaux** [comment]
Hi Marius,
  i am new to using the mXparser, i notice you said "In math there is now zero parameters functions."... i have looked around and cant find any info on this, would you please post a code snippet? I already use the following models:
        // declare user defined Functions for Use in Formulas
        static FunExtVar gx = new FunExtVar();
        static Function funcPower = new Function("Power", "x^y", "x", "y"); // declare separate for use INSIDE another formula
        static Function[] f = new Function[] {
            funcPower,
            new Function("f", "x^2", "x"),
            new Function("y(x) = Rand(100)", new RandFunc()),
            new Function("sqr(x) = Power(x,2)", funcPower),
            new Function("AND", "x&&y","x","y"),
            new Function("g", gx),
            new Function("Or", new OrFunc()),
            new Function("And", new AndFunc()),
            new Function("Rand", new RandFunc())
        };// call user func within user func
I am looking for easy way to get variadic function Rand() to support 0 or more parameters... 
zero parameters (Rand()) currently returns NaN, 1 or more params (Rand(1), Rand(11,20) ) work correctly...
Many thanks in advance!
pci-wardeaux

**Comment by krugman25** [comment]
> Hi Marius,
> i am new to using the mXparser, i notice you said "In math there is now zero parameters functions."... i have looked around and cant find any info on this, would you please post a code snippet? I already use the following models:
> // declare user defined Functions for Use in Formulas
> static FunExtVar gx = new FunExtVar();
> static Function funcPower = new Function("Power", "x^y", "x", "y"); // declare separate for use INSIDE another formula
> static Function[] f = new Function[] {
> funcPower,
> new Function("f", "x^2", "x"),
> new Function("y(x) = Rand(100)", new RandFunc()),
> new Function("sqr(x) = Power(x,2)", funcPower),
> new Function("AND", "x&&y","x","y"),
> new Function("g", gx),
> new Function("Or", new OrFunc()),
> new Function("And", new AndFunc()),
> new Function("Rand", new RandFunc())
> };// call user func within user func
> I am looking for easy way to get variadic function Rand() to support 0 or more parameters...
> zero parameters (Rand()) currently returns NaN, 1 or more params (Rand(1), Rand(11,20) ) work correctly...
> Many thanks in advance!
> pci-wardeaux

From what I can tell you can't have zero parameter user-defined functions.  The user-defined function still needs at least one dummy variable.  What you do is create an alias of the 1 parameter function, and then call the alias.  As Marius explained, using this code `time = Time(0)` is how you can then call the Time user defined function simply using the word "Time".  This works and is what we are shipping out in our commercial product, but it still technically isn't a zero parameter user-defined function, it is a 1 parameter function that uses a zero parameter alias.  The difference may seem minor, but it does affect how you need to write your "zero parameter" user-fined function classes.

**Comment by pci-wardeaux** [comment]
Thanks for the prompt reply. I see your point, but i was reading Marius comment that said there WAS zero param functions when he said "In math there is NOW zero parameters functions."... perhaps he meant "In math there is NO zero parameters functions." :)
this work around is not going to work for us as we are building a system to read/use client-defined formulas written over the past 20+ years... so we are definitely going to have to handle "Rand()" (and all the other defined functions that have no parameters) and not force the user to go through their past 20+ years of work and change it to "Rand" or even "Rand(0)"... :) 
Also since these are client entered formulas, we cannot tell when one of these no-param functions will be loaded, it would really be bad if we had to preparse every formula just to see if one of these funcs happen to be in the formula... 
Hoping there is a better solution... 
thanks

**Comment by krugman25** [comment]
That is a good point.  I was confused when he said there is **now** zero parameter functions, and then proceeded to give a different example.  That being a typo would make sense, haha.

That is unfortunate the situation you are in.  In our case this is new development so I am writing the alias functions directly into our custom math service layer, and the end user is none the wiser.

I don't know anything about your software, but it sounds like you are ruling out parsing each formula.  That was what popped into my mind reading your comment, which would be to write a list of function names that are zero parameter functions, and then scan the formula each time they are used to find and match the functions in the formula to the functions in your list and then convert them into the zero parameter alias version that Marius showed.  That would make your older formula's work with this parser library without needed to change anything on the front end.  That sort of find and replace shouldn't take much processing power at all.

**Comment by pci-wardeaux** [comment]
Hmmm that may not be too bad an idea... though parsing a user defined string for key words is not always straight forward... so instance: in these formulas the original way to get the Pi constant is to use "Pi ()"... we cant just say "string.Replace("Pi ()", "pi") because "Pi  ()" (two spaces between instead of one, or none, or...) is also allowed because it is USER typed, and so on... and of course the formula is not JUST "Pi ()" it can be embedded in a long formula, and there can be literally thousands of these formulas to go through in one of our projects. Not a small feat but unless Marius has a better solution looks like i may be stuck with it >_<
Thanks for the dialog! :D

**Comment by mariuszgromada** [comment]
It was a typo :-) If you need I can introduce zero parameters functions :-)

**Comment by pci-wardeaux** [comment]
Yes that would be WONDERFUL!! :D when do you think could be done? if going to be a while, could i get a temp fix to use in my code?
many MANY thanks!! :D

**Comment by pci-wardeaux** [comment]
this is an incredibly flexible and powerful tool!! love it!

**Comment by krugman25** [comment]
> Hmmm that may not be too bad an idea... though parsing a user defined string for key words is not always straight forward... so instance: in these formulas the original way to get the Pi constant is to use "Pi ()"... we cant just say "string.Replace("Pi ()", "pi") because "Pi ()" (two spaces between instead of one, or none, or...) is also allowed because it is USER typed, and so on... and of course the formula is not JUST "Pi ()" it can be embedded in a long formula, and there can be literally thousands of these formulas to go through in one of our projects. Not a small feat but unless Marius has a better solution looks like i may be stuck with it >_<
> Thanks for the dialog! :D

In that case you would want your "replacement list" to include all of the variations you might expect.   It may be a pain at first to create the list and the variations of each function, but it's a one-and-done thing.   If you have access to the where the user formula's are stored, you could update the formula's themselves, that way they are updated to the new format and you never have to run the code again.  If you can't update the users formula's or don't have access you would just need to loop through that dictionary and do a string.replace() each time you run a formula.  There are a lot of ways to go about it, but using linq you can accomplish all of that in just 2 lines of code.

**Comment by krugman25** [comment]
> It was a typo :-) If you need I can introduce zero parameters functions :-)

I am not sure how many dev's out there need it, but I know I would love having the ability.  There are a number of functions that we may need to create that won't have parameters.  Two have already been mentioned here: rand() and time().

**Comment by mariuszgromada** [comment]
The examples you provided are functions with hidden parameters - time() is in seconds, as in function body you are making conversion into seconds, it should be time(unit). The random number are fully supported as of now, and the rand() is rand(seed) in fact.

In mathematics convention there is nothing like f(), it always has to have parameters.

But I understand the need as this is also becoming a bit of a programming language.

Which framework are you using? .net? java?

Best regards

**Comment by krugman25** [comment]
> The examples you provided are functions with hidden parameters - time() is in seconds, as in function body you are making conversion into seconds, it should be time(unit). The random number are fully supported as of now, and the rand() is rand(seed) in fact.
> 
> In mathematics convention there is nothing like f(), it always has to have parameters.
> 
> But I understand the need as this is also becoming a bit of a programming language.
> 
> Which framework are you using? .net? java?
> 
> Best regards

Correct, any of these zero param functions in theory could have parameters, but in our application our customers will not have parameterized versions of either time or random functions.  Sometimes theory and practicality look different.  Using the alias works good for us, but does require some extra code in our math library.  We are using .net.

**Comment by mariuszgromada** [comment]
Yes, I agree.

I will introduce zero param functions.

Best regards

**Comment by krugman25** [comment]
> Yes, I agree.
> 
> I will introduce zero param functions.
> 
> Best regards

Great, looking forward to it.  Thank you.

**Comment by pci-wardeaux** [comment]
this is awesome, thanks so much!

**Comment by pci-wardeaux** [comment]
"The random number are fully supported as of now, and the rand() is rand(seed) in fact."
by the way, i tried to run 
            Expression e12 = new Expression("rand(10)", f);
            var x12 = e12.calculate();
and x12 is NaN... what am i missing? many thanks

**Comment by mariuszgromada** [comment]
I was referring to your example rand() = rand(0) in most cases, not in mXparser.

Just hit: `mXparser.consolePrintHelp("rand");`

```
Help content: 

    #  key word            type                    syntax                                        since description
    -  --------            ----                    ------                                        ----- -----------
  153. rUni                <Binary Function>       rUni(a, b)                                    3.0   Random variable - Uniform continuous distribution U(a,b), usage example: 2*rUni(2,10)
  154. rUnid               <Binary Function>       rUnid(a, b)                                   3.0   Random variable - Uniform discrete distribution U{a,b}, usage example: 2*rUnid(2,100)
  156. rNor                <Binary Function>       rNor(mean, stdv)                              3.0   Random variable - Normal distribution N(m,s) m - mean, s - stddev, usage example: 3*rNor(0,1)
  198. rList               <Variadic Function>     rList(a1, ..., an)                            3.0   Random number from given list of numbers
  313. [Uni]               <Random Variable>       [Uni]                                         3.0   Random variable - Uniform continuous distribution U(0,1)
  314. [Int]               <Random Variable>       [Int]                                         3.0   Random variable - random integer
  315. [Int1]              <Random Variable>       [Int1]                                        3.0   Random variable - random integer - Uniform discrete distribution U{-10^1, 10^1}
  316. [Int2]              <Random Variable>       [Int2]                                        3.0   Random variable - random integer - Uniform discrete distribution U{-10^2, 10^2}
  317. [Int3]              <Random Variable>       [Int3]                                        3.0   Random variable - random integer - Uniform discrete distribution U{-10^3, 10^3}
  318. [Int4]              <Random Variable>       [Int4]                                        3.0   Random variable - random integer - Uniform discrete distribution U{-10^4, 10^4}
  319. [Int5]              <Random Variable>       [Int5]                                        3.0   Random variable - random integer - Uniform discrete distribution U{-10^5, 10^5}
  320. [Int6]              <Random Variable>       [Int6]                                        3.0   Random variable - random integer - Uniform discrete distribution U{-10^6, 10^6}
  321. [Int7]              <Random Variable>       [Int7]                                        3.0   Random variable - random integer - Uniform discrete distribution U{-10^7, 10^7}
  322. [Int8]              <Random Variable>       [Int8]                                        3.0   Random variable - random integer - Uniform discrete distribution U{-10^8, 10^8}
  323. [Int9]              <Random Variable>       [Int9]                                        3.0   Random variable - random integer - Uniform discrete distribution U{-10^9, 10^9}
  324. [nat]               <Random Variable>       [nat]                                         3.0   Random variable - random natural number including 0
  325. [nat1]              <Random Variable>       [nat1]                                        3.0   Random variable - random natural number including 0 - Uniform discrete distribution U{0, 10^1}
  326. [nat2]              <Random Variable>       [nat2]                                        3.0   Random variable - random natural number including 0 - Uniform discrete distribution U{0, 10^2}
  327. [nat3]              <Random Variable>       [nat3]                                        3.0   Random variable - random natural number including 0 - Uniform discrete distribution U{0, 10^3}
  328. [nat4]              <Random Variable>       [nat4]                                        3.0   Random variable - random natural number including 0 - Uniform discrete distribution U{0, 10^4}
  329. [nat5]              <Random Variable>       [nat5]                                        3.0   Random variable - random natural number including 0 - Uniform discrete distribution U{0, 10^5}
  330. [nat6]              <Random Variable>       [nat6]                                        3.0   Random variable - random natural number including 0 - Uniform discrete distribution U{0, 10^6}
  331. [nat7]              <Random Variable>       [nat7]                                        3.0   Random variable - random natural number including 0 - Uniform discrete distribution U{0, 10^7}
  332. [nat8]              <Random Variable>       [nat8]                                        3.0   Random variable - random natural number including 0 - Uniform discrete distribution U{0, 10^8}
  333. [nat9]              <Random Variable>       [nat9]                                        3.0   Random variable - random natural number including 0 - Uniform discrete distribution U{0, 10^9}
  334. [Nat]               <Random Variable>       [Nat]                                         3.0   Random variable - random natural number
  335. [Nat1]              <Random Variable>       [Nat1]                                        3.0   Random variable - random natural number - Uniform discrete distribution U{1, 10^1}
  336. [Nat2]              <Random Variable>       [Nat2]                                        3.0   Random variable - random natural number - Uniform discrete distribution U{1, 10^2}
  337. [Nat3]              <Random Variable>       [Nat3]                                        3.0   Random variable - random natural number - Uniform discrete distribution U{1, 10^3}
  338. [Nat4]              <Random Variable>       [Nat4]                                        3.0   Random variable - random natural number - Uniform discrete distribution U{1, 10^4}
  339. [Nat5]              <Random Variable>       [Nat5]                                        3.0   Random variable - random natural number - Uniform discrete distribution U{1, 10^5}
  340. [Nat6]              <Random Variable>       [Nat6]                                        3.0   Random variable - random natural number - Uniform discrete distribution U{1, 10^6}
  341. [Nat7]              <Random Variable>       [Nat7]                                        3.0   Random variable - random natural number - Uniform discrete distribution U{1, 10^7}
  342. [Nat8]              <Random Variable>       [Nat8]                                        3.0   Random variable - random natural number - Uniform discrete distribution U{1, 10^8}
  343. [Nat9]              <Random Variable>       [Nat9]                                        3.0   Random variable - random natural number - Uniform discrete distribution U{1, 10^9}
  344. [Nor]               <Random Variable>       [Nor]                                         3.0   Random variable - Normal distribution N(0,1)
```

**Comment by mariuszgromada** [comment]
Done, ArgumentExtension interface introduced allowing to add Arguments based on source code implementation, below example:

JAVA

```
class PiMultArgExt implements ArgumentExtension {
	private int multiple = 0;
	public double getArgumentValue() {
		multiple++;
		return  MathConstants.PI * multiple;
	}
	public PiMultArgExt clone() {
		return new PiMultArgExt();
	}
}
Argument x = new Argument("x", new PiMultArgExt());
Expression e = new Expression("x + x - 3*p", x);
mXparser.consolePrintln(e.calculate());
```
JAVA result:
`[mXparser-v.4.4.0] 0.0`

C#
```
internal class PiMultArgExt : ArgumentExtension
{
	private int multiple = 0;
	public double getArgumentValue()
	{
		multiple++;
		return MathConstants.PI * multiple;
	}
	public ArgumentExtension clone()
	{
		return new PiMultArgExt();
	}
}

Argument x = new Argument("x", new PiMultArgExt());
Expression e = new Expression("x + x - 3*pi", x);
mXparser.consolePrintln(e.calculate());
```

Result - C#
`[mXparser-v.4.4.0] 0`

Best regards
