### ISSUE TITLE
Wrong derivative result

### ISSUE THREAD

**Issue by i0xHeX** [mariuszgromada/MathParser.org-mXparser#180]
Function `der()` gives wrong result.

MathParser.org-mXparser version: v.4.3.3 (from Maven Repo)
Java

Code:
```
Argument x = new Argument("x = 3");
Expression exp = new Expression("der(x^2, x)", x);
exp.setVerboseMode();
System.out.println(exp.calculate());
```
Output:
```
[mXparser-v.4.3.0] 
[][der(x^2, x)] 
[][der(x^2, x)] Starting ...
[][der(x^2, x)] x = 3.0
[][der(x^2, x)] Starting calculation loop
 ---> 5.999999999999979  ...  done
[][der(x^2, x)] Calculated value: 5.999999999999979
[][der(x^2, x)] Exiting

5.999999999999979
```
Desired result: `6.0` (as `der(x^2, x) = 2x`)

Okay, let's assume we can round previous result, but let's try something bigger:
X = 100'000 -> 200020.0
X = 1'000'000 -> 1999360.0
X = 10'000'000 -> 2.00000003125E7

Precision is too small for accurace computations.

**Comment by mariuszgromada** [comment]
Hi

Thank you. Derivative function is a numerical derivative. In case of 10000000 you get the 0.0000015625% error - so quite small.

Best regards
