### ISSUE TITLE
Why did you use Double instead of BigDecimal and BigInterger for the Math operations?

### ISSUE THREAD

**Issue by Novaax** [mariuszgromada/MathParser.org-mXparser#182]
Hello,
could you explain, why did you use Double instead of BigDecimal or BigInteger in your Math operations?

**Comment by mariuszgromada** [comment]
Dear @Novaax,

There are many reasons:

1) This is a scientific parser - you do not need to specify precision, you can work in the same time on a very small and a very big numbers.
2) mXparser is a cross-platform library - i.e. java and .net, Double is implemented almost in the same way in both platforms. BigDecimal, BigInteger does not exits on the other frameworks.
3) There are a bunch of  math functions implemented already for Double in the standard libraries, that are not available for BigInteger, BigDecimal.

Best regards

**Comment by mariuszgromada** [comment]
#195
