### ISSUE TITLE
C# conventions - no documentation

### ISSUE THREAD

**Issue by pie-flavor** [mariuszgromada/MathParser.org-mXparser#183]
As far as I can tell, the C# version of this project adheres to absolutely zero C# conventions of any kind - lowercased namespaces, camel case methods, getters instead of properties. If I wanted to write Java, I'd write Java. But I'm just naturally a rules person; it doesn't really *matter*. What *does* matter is that the C# code is *also* annotated with Javadoc syntax, rather than XmlDoc, and this means that tools designed to show documentation just show this library as having zero documentation.

**Comment by mariuszgromada** [comment]
Dear @pie-flavor,

I know perfectly C# conventions, but ... this is a direct port of java code. Project is developed in java, then ported to C#.  Fixing the conventions would create huge additional future effort on maintaining the code and making it equal to the java source of the truth.

Are there any other benefits from changing conventions?

Best regards

**Comment by pie-flavor** [comment]
There aren't any usage benefits as far as I can tell, no. It's just a style thing. I would however dispute the 'huge additional future effort' thing - so long as there's a fixed set of things that get changed, like changing names to TitleCase or changing getters/setters to properties, then mapping between the two stays just as easy.

I do recognize however that an *actual* concern would be breaking downstream code. So for the time being my chief complaint is only about the documentation.

**Comment by mariuszgromada** [comment]
I am happy to accept documentation PR :-)

**Comment by pie-flavor** [comment]
#184
