### ISSUE TITLE
Memory leakage

### ISSUE THREAD

**Issue by iv4512** [mariuszgromada/MathParser.org-mXparser#185]
Memory leakage on 
Expression.addArguments
or
Expression.checkSyntax

Test code:

                var args = new Argument[] { new Argument("G",0)};
                while (true)
                {
                    for (int i = 0; i < 500; i++)
                    {
                        Expression ex = new Expression("max(0,G/2)+1");
                        ex.addArguments(args[0]);
                        ex.checkSyntax();
                    }
                    GC.Collect();
                }

There is no memory leakage if change line 
ex.addArguments(args[0]);
to:
ex.addArguments(new Argument("G", 0));
or delete ex.checkSyntax();

**Comment by mariuszgromada** [comment]
Wwhat you do is:
- you create 500 different expressions
- you create a reference from those expressions to the same instance of argument 
- by doing that at that instance of argument there is a list that keeps all the expressions that this argument is connected with
- basically, all the expressions are reachable from the argument args[0]
- this is a correct behavior as mXparser was designed to check syntax only once, and If there was a definition change (i.e. modification of the argument) all expressions that depends on that argument will be put into a state SYNTAX_STATUS_UNKNOWN, check my code below


```
			Argument x = new Argument("x = 2");
			Argument y = new Argument("y = 2*x", x);
			Argument z = new Argument("z = y^2", y);
			Expression e1 = new Expression("2*z", z);
			Expression e2 = new Expression("3*z", z);
			Console.WriteLine("01. e1 syntax status = " + e1.getSyntaxStatus());
			Console.WriteLine("02. e2 syntax status = " + e2.getSyntaxStatus());
			e1.checkSyntax();
			e2.checkSyntax();
			/* now we know systax status and it is kept in expression */
			Console.WriteLine("03. e1 syntax status = " + e1.getSyntaxStatus());
			Console.WriteLine("04. e2 syntax status = " + e2.getSyntaxStatus());
			Console.WriteLine("05. e1 value = " + e1.calculate());
			Console.WriteLine("06. e2 value = " + e2.calculate());
			x.setArgumentValue(3);
			/* just change int te argument value does not affect syntax status */
			Console.WriteLine("07. e1 syntax status = " + e1.getSyntaxStatus());
			Console.WriteLine("08. e2 syntax status = " + e2.getSyntaxStatus());
			Console.WriteLine("09. e1 value = " + e1.calculate());
			Console.WriteLine("10. e2 value = " + e2.calculate());
			/* but let's change 'y' definition, not the value */
			y.setArgumentExpressionString("3*x");
			/* here all elements that depends on 'y' are update to syntax status unknown */
			Console.WriteLine("11. e1 syntax status = " + e1.getSyntaxStatus());
			Console.WriteLine("12. e2 syntax status = " + e2.getSyntaxStatus());
			Console.WriteLine("13. e1 value = " + e1.calculate());
			Console.WriteLine("14. e2 value = " + e2.calculate());
			/* but after caluclation it syntax status is known again */
			Console.WriteLine("15. e1 syntax status = " + e1.getSyntaxStatus());
			Console.WriteLine("16. e2 syntax status = " + e2.getSyntaxStatus());

```

Plus the code result

```
01. e1 syntax status = False
02. e2 syntax status = False
03. e1 syntax status = True
04. e2 syntax status = True
05. e1 value = 32
06. e2 value = 48
07. e1 syntax status = True
08. e2 syntax status = True
09. e1 value = 72
10. e2 value = 108
11. e1 syntax status = False
12. e2 syntax status = False
13. e1 value = 162
14. e2 value = 243
15. e1 syntax status = True
16. e2 syntax status = True
```

Is that clear for you?

Best regards

**Comment by iv4512** [comment]
Thanks for your answer. Yes, it's clear.
Can I clear argument's list that keeps all the expressions? Or I should create new instance of argument when create new expression?

**Comment by mariuszgromada** [comment]
In case you create many different instances of argument "G", then you will face a problem on changing argument value - simply, despite of the same name, such arguments are different objects.

My proposal is as follows

Write a method

```
public static void ClearExpression(Expression e)
{
   if (e == null) return;
   e.removeAllArguments();
   e.removeAllConstants();
   e.removeAllFunctions();
}

```

Add call to this method inside the loop after expression was created. This will remove dependency between argument and expression, but it needs to be called at the expression level as the expression object depends on argument, not the opposite.

Best regards

**Comment by mariuszgromada** [comment]
This is how this "remove...." methods are implemented inside the Expression class

```
	/**
	 * Removes all arguments associated with the expression.
	 *
	 * @see        Argument
	 * @see        RecursiveArgument
	 */
	public void removeAllArguments() {
		for (Argument arg : argumentsList)
			arg.removeRelatedExpression(this);
		argumentsList.clear();
		setExpressionModifiedFlag();
	}

	/**
	 * Removes all functions
	 * associated with the expression.
	 *
	 * @see        Function
	 */
	public void removeAllFunctions() {
		for (Function f : functionsList)
			f.removeRelatedExpression(this);
		functionsList.clear();
		setExpressionModifiedFlag();
	}

	/**
	 * Removes all constants
	 * associated with the expression
	 *
	 * @see        Constant
	 */
	public void removeAllConstants() {
		for (Constant c : constantsList)
			c.removeRelatedExpression(this);
		constantsList.clear();
		setExpressionModifiedFlag();
	}

```

Methods "removeRelated..." are not visible in public, they are internal

**Comment by mariuszgromada** [comment]
Thanks to this structure, the beautifull recursion works, even more, it allows to create recursive function as well :-)
Check some examples here

https://mathparser.org/mxparser-tutorial/user-defined-recursion-not-limited/

**Comment by iv4512** [comment]
Thank you.
Best regards.

**Comment by herme063** [comment]
I have the following pattern
```
Parallel.ForEach(...partitioner..., (range) =>
{
   var arguments = ...create argument...
   var expression = new Expression(formula, arguments.Concat(constants))
   var data = new Dictionary<DateTime, double>();
   foreach (var r in range)
   {
        foreach (var a in arguments)
        {
             a.setArgumentValue(...);
        }
        
        data[r] = expression.Calculate();
   }
});
```
Basically, I am calculating time series data using one expression and updating the argument values for each interval in the range. Arguments are mixed with global "constant" arguments.

I am running into an issue where the jdk memory usage is very high.
Is there a potential issue in the above pattern to cause for such high memory usage?
Can I use the suggested clear expression pattern and where should I put it?
