### ISSUE TITLE
Increasing Calculation Speed

### ISSUE THREAD

**Issue by krugman25** [mariuszgromada/MathParser.org-mXparser#187]
We are going to be processing tens or hundreds of millions of calculations per day (large IIoT project).  I noticed when I run any sort of simple expression "((x - y) / x) * 100" or "x > y", the calculate() method usually takes about 3000-8000 ticks (occasionally much more 20,000 - 30,000 ticks) to run.  On a small number of calculations that is plenty fast, but on a few million it can add up to hours of processing time, which is way too slow for us.  That many ticks to do simple math or simple logic check seems way to high.  I just want to make sure I am using your library properly and if not, what things could I do to speed up calculations.

Currently we take a string which contains the expression, create a new Expression() object using it, and then call calculation on it. An example of one of those real life expression strings may be "((1.92746 / 12.423) / 1.92746) * 100" or "45.25 > 47.12".

I am running this code in Visual Studio and using the System.Stopwatch to calculate the ticks.  I also have Just My Code enabled.

**The code**
```                  
var e = new Expression(expressionStr);
calculatedValue = e.calculate();
```

**Comment by mariuszgromada** [comment]
Hi,

In case you create new expression then total parsing has to be done, and mXparser has a lot of built-in tokens.

What I can recommend is to:
- Create expression with arguments
- Pre-compile it
- change argument value and calculate

Then it is going to be much faster, see the code below:

```
Argument x = new Argument("x");
Argument y = new Argument("y");
Expression e1 = new Expression("((x - y) / x) * 100", x, y);;
Expression e2 = new Expression("x > y", x, y);

for (int ix = 1; ix <= 1000; ix++)
{
   for (iy = 1; iy <= 1000; iy++)
   {
      x.setArgumentValue(ix);
      y.setArgumentValue(iy);
      e1.calculate();
   }
}
 
for (int ix = 1; ix <= 1000; ix++)
{
   for (int iy = 1; iy <= 1000; iy++)
   {
      x.setArgumentValue(ix);
      y.setArgumentValue(iy);
      e2.calculate();
   }
}
```

Please let me know whether it helps.

Best regarrds

**Comment by mariuszgromada** [comment]
This can help as well

```
mXparser.disableAlmostIntRounding();
mXparser.disableUlpRounding();
mXparser.setExactComparison();

```

Read more here:
https://mathparser.org/api/org/mariuszgromada/math/mxparser/mXparser.html

**Comment by mariuszgromada** [comment]
mXparser is a class library, but you can execute performance tests.
- Open Power Shell
- Load Assembly
- Execute tests

```
[Reflection.Assembly]::LoadFile("D:\full\exact\path\to\MathParser.org-mXparser.dll")
[org.mariuszgromada.math.mxparser.regressiontesting.RunTest]::Start("perf")

```
Can you share the results?

Best regards

**Comment by krugman25** [comment]
Thank you for all of this.  I am taking the approach of creating the expression and expression arguments ahead of time, and then just calling them when I need them.  I tested this idea out in a test project and the results were phenomenal.  The calculation went from taking roughly 5,000 ticks to about 30 ticks, so greater than 99% improvement.  That also means this will shave hours or days off of running millions of calculations.  It is a real game changer.

But... here is the issue I am running into.  We store all of this in a json file, which means we take the class instances and serialize them into json files, and then when we are ready to process we deseserialize those json files back into c# class instances and get to work.  The problem is your Argument class doesn't have a default constructor so it won't deserialize.  What are the chances I could get you to create a parameterless constructor for that class.  It can even be private because I can add the "ConstructorHandling.AllowNonPublicDefaultConstructor" setting to my json serializer.

**Comment by krugman25** [comment]
The same is true for the Expression class as well.

**Comment by krugman25** [comment]
I grabbed your source code as I was going to give the private parameter-less constructor a go, just to see if it would get me over this hurdle, but when I try to compile it throws an MD5 checksum error.  I am not familiar with re-building open source code from another dev.

**Comment by krugman25** [comment]
A quick update - I removed the signing of the application and was able to compile the parser with changes.  The changes I made were to add private default (parameter-less) constructors to the Argument and Expression classes.  The good news is that the classes are now deserializing properly.  I am going to continue with my testing to see if it all works end-to-end and I am able to realize the speed gains by have the Expression and Arguments pre-compiled and serialized.

Do you see any negative adverse effects from having a private parameter-less constructor in those classes?  The can't be called by a client DLL, and only serve to make the serializer happy.

**Comment by mariuszgromada** [comment]
Private default constructor - no problem. I can even add it in the next release.

I am wondering why you need to serialize Expression / Argument class? Recreating expression based on expression string is really fast. What I want to say, you just need to preserve expression string and argument names.

Anyway - making classes serializable is a good idea and I am going to introduce necessary constructors.

Best regards

**Comment by krugman25** [comment]
I have been running some tests today and can tell you it is much faster now.  Exactly the modification I did was create a public parameterless constructor for the PrimitiveElement class and then created a private parameterless constructor for both the Arguments and Expression class.

The speed tests that I ran show that having the entire Expression class instance already built and ready to calculation is much faster than re-using an Expression instance and just changing the expression string.  But both of those methods are much faster than newing up an expression on the fly.

Here are the results I was seeing for simple math functions on roughly 600 calculations (All tests were ran on a multi-threaded loop)

-Newing up the Expression and Arguments each iteration was taking on average 250ms
-Re-using an expression and inserting the expression string was taking on average 70ms
-Having the Expression and arguments pre-build and ready to calculate was taking on average 20ms

Test #3 I ran on an isolated test program.  I am still working on getting the entire Expression instance pre-built, populated, and serialized to realize that last bit of speed.  But as it stands right now, the 70ms speed is much faster than the 900ms it was taking when I was newing everything up on-the-fly and also running on a single thread.

**Comment by krugman25** [comment]
> Private default constructor - no problem. I can even add it in the next release.

That would be great.  For now I will run the modified version I created and then switch it over to the public release once you have it added.

Also, I noticed that when I add more than 4 arguments to an Expression it throws an error.  Is 4 arguments a hard limit or am I doing something wrong?  I basically have Argument ArgA("a"), Argument ArgB("b"), Argument ArgC("c"), etc.  then have new Expression("a + b + c + d + e", ArgA, ArgB, ArgC, ArgD, ArgE), or something like that.

**Comment by mariuszgromada** [comment]
mXparser support as many arguments as you want. Most probably you have a names conflict with built-in tokens, mXparser have 500 keywords reserved :-) This is a big math engine.

Just set the option:
mXparser.setToOverrideBuiltinTokens();

Your use case is very interesting, you might share the changes you did as PR :-)

**Comment by mariuszgromada** [comment]
Try mXparser.consolePrintHelp() :-)

**Comment by mariuszgromada** [comment]
In Expression class familiarize yourself with the following

- `checkLexSyntax()` - grammar correctness, gives true even if you use not defined argument or function
- `checkSyntax()` - full syntax check, grammar + assigned user defined elements

So, if checkLexSyntax() = true and checkSyntax() = false, most probably there are missing user defined arguments or user defined functions, then mXparser provides some hints :-)

- `String[] getMissingUserDefinedArguments()`
- `String[] getMissingUserDefinedFunctions()`
 
Best regards

**Comment by mariuszgromada** [comment]
Additionally read this
https://github.com/mariuszgromada/MathParser.org-mXparser/issues/185

**Comment by krugman25** [comment]
> Just set the option:
> `mXparser.setToOverrideBuiltinTokens();`

Will this disable some of the built in functions like "abs()" or will that stuff continue to work?  We do use some of those built in functions.

**Comment by mariuszgromada** [comment]
It can disable only in case you define your own "abs" keyword. This is just to avoid conflicts. For instance:

- Default options - this will generate an error

Argument abs = new Argument("abs = 2");
Expression e = New Expression("2*abs", abs);

- if you set to override built-in tokens, above example is going to work

**Comment by krugman25** [comment]
Please consider adding an overload to setArgumentValue(), of setArgumentValue(int, double).  The int being the index for the array of Arguments in the expression.

In our specific case we don't want to store each Argument in it's own object, it is good enough to new up those arguments when the Expression is instantiated.  For efficiency purposes, we would like to loop through that Expression's list of argument and populate each one with it's respective double.

**Comment by mariuszgromada** [comment]
Ok, might be. As of now you have


```
getArgumentsNumber()
getArgument(int i).setArgumentValue(double value)

```

**Comment by krugman25** [comment]
> Ok, might be. As of now you have
> 
> ```
> getArgumentsNumber()
> getArgument(int i).setArgumentValue(double value)
> ```

Great!  Thank you, that should work!

**Comment by mariuszgromada** [comment]
Read more on mXparser in the Tutorial: http://mathparser.org/mxparser-tutorial/
And the API: http://mathparser.org/api/overview-summary.html
