### ISSUE TITLE
Best way to dynamically evaluate arguments?

### ISSUE THREAD

**Issue by znerd** [mariuszgromada/MathParser.org-mXparser#188]
### Issue title:
What is the best way to dynamically evaluate arguments?

### Issue content:
- MathParser.org-mXparser version: v4.3.3
- Framework: java (using Maven dependency)

I'd like to dynamically evaluate arguments used in an `Expression`. Currently I'm doing this as follows:

```
public Number evalNumber(final ValueEvalContext context) throws ValueEvalException {
        final Expression expression = new Expression(expressionString);
        final List<String> usedKeys = new ArrayList<>();
        final List<Token> tokens = expression.getCopyOfInitialTokens();
        for (final Token token : tokens) {
            if ("argument".equals(token.looksLike)) {
                usedKeys.add(token.tokenStr);
            }
        }
        for (final String key : usedKeys) {
            final Value valueObject = context.getValue(key);
            final double numberValue = valueObject.evalNumber(context).doubleValue();
            expression.defineArguments(key);
            expression.setArgumentValue(key, numberValue);
        }
        if (!expression.checkSyntax()) {
            throw new ValueEvalException("Syntax error in expression: " + quote(expressionString) + '.');
        }
        return expression.calculate();
    }
```

This works. But is that the best way to do it, currently? Or is there a better way?

Firstly, note that I'm using the `getCopyOfInitialTokens`, which is perhaps not intended to be used like this.

And secondly, I'm accessing `token.looksLike` and then comparing it with the literal string `"argument"`, because `Expression.ARGUMENT` is `private`.

Any suggestions would be appreciated.

**Comment by mariuszgromada** [comment]
Hi,

You are doing it great, those methods were created for such cases.

You can do it a bit faster. Instead of parsing tokens, you can add to the Expression each pair key/ value that you have in your context, simply create and arguments array, then add definitions to the expression. If somebody will use that key, it will be there already defined. Then you do not need to take a hint based on looksLike field.

Best regards
