### ISSUE TITLE
Comparison function appears to evaluate both terms

### ISSUE THREAD

**Issue by precisionterrain** [mariuszgromada/MathParser.org-mXparser#189]
- MathParser.org-mXparser version: v.4.3.3
- Framework:  .net
- Problem description

When evaluating an IF function like the below an incorrect answer is returned.

"if(0 > 1, NaN, 50)"

My expectation is that in the above case the expression should always evaluate to 50.

However this expression returns NaN.

Perhaps the parser cannot handle the string 'NaN', even though logically it should never need to be evaluated.

Consider the following two expressions:

if(0 > 1,-1.79769313486232E+308, 50)   
if(0 > 1,-1.7976931348623157E+308, 50)

The former returns NaN. The latter correctly returns 50.

Double precision numbers do odd things at the extremes and -1.79769313486232E+308 will not parse to a Double, despite it being created by Double.MinValue.ToString(). Oddly enough -1.7976931348623157E+308 will parse correctly to a Double.

But should either have to be parsed at all in a situation where logically they will never be evaluated?

**Comment by mariuszgromada** [comment]
### The case of "if(0 > 1, NaN, 50)" 

Try to check syntax before calculating

```
Expression e1 = new Expression("if(0 > 1, NaN, 50)");
e1.checkSyntax();
Console.WriteLine(e1.getErrorMessage());
```

The result shows than NaN is the problem here
```
[if(0 > 1, NaN, 50)] checking ...
[if(0 > 1, NaN, 50)] (NaN, 6) invalid <TOKEN>.
[if(0 > 1, NaN, 50)] errors were found.
```

To check whether NaN keyword is supported please use mXparser help
`mXparser.consolePrintHelp("NaN");`

The result:
```
Help content:

    #  key word            type                    syntax                                        since description
    -  --------            ----                    ------                                        ----- -----------
   14. ~&                  <Boolean Operator>      p ~& q                                        1.0   NAND - Sheffer stroke
   15. ~&&                 <Boolean Operator>      p ~&& q                                       1.0   NAND - Sheffer stroke
   16. ~/\                 <Boolean Operator>      p ~/\ q                                       1.0   NAND - Sheffer stroke
  130. isNaN               <Unary Function>        isNaN(x)                                      4.1   Returns true = 1 if value is a Not-a-Number (NaN), false = 0 otherwise - usage example: isNaN(x)
  199. coalesce            <Variadic Function>     coalesce(a1, ..., an)                         4.1   Returns the first non-NaN value
  312. [NaN]               <Constant Value>        [NaN]                                         4.1   Not-a-Number
  377. [n]                 <Unit>                  [n]                                           4.0   <Metric prefix> Billionth / Nano = 10^-9
```

As you can see mXparser uses [NaN] keyword.
```
Expression e1 = new Expression("if(0 > 1, [NaN], 50)");
e1.checkSyntax();
Console.WriteLine(e1.getErrorMessage());
Console.WriteLine(e1.getExpressionString() + " = " + e1.calculate());
```

The result:
```
[if(0 > 1, [NaN], 50)] checking ...
[if(0 > 1, [NaN], 50)] no errors.
if(0 > 1, [NaN], 50) = 50
```

### In terms od "if(0 > 1,-1.79769313486232E+308, 50)"

mXparser deliver two methods for syntax checking: lexical syntax and total expression syntax - see the code below:
```
Expression e1 = new Expression("if(0 > 1,-1.79769313486232E+308, 50)");
e1.checkLexSyntax();
Console.WriteLine("Lexical syntax of " + e1.getExpressionString() + " = " + e1.checkLexSyntax());
Console.WriteLine("Expression syntax of " + e1.getExpressionString() + " = " + e1.checkSyntax());
```

The result is correct
```
Lexical syntax of if(0 > 1,-1.79769313486232E+308, 50) = True
Expression syntax of if(0 > 1,-1.79769313486232E+308, 50) = False
```

### In terms of "if(0 > 1,-1.7976931348623157E+308, 50)"
```
Expression e1 = new Expression("if(0 > 1,-1.7976931348623157E+308, 50)");
e1.checkLexSyntax();
Console.WriteLine("Lexical syntax of " + e1.getExpressionString() + " = " + e1.checkLexSyntax());
Console.WriteLine("Expression syntax of " + e1.getExpressionString() + " = " + e1.checkSyntax());
```

The result is correct
```
Lexical syntax of if(0 > 1,-1.79769313486232E+308, 50) = True
Expression syntax of if(0 > 1,-1.79769313486232E+308, 50) = False
```

Best regards

**Comment by mariuszgromada** [comment]
Both terms are not evaluated, simply syntax is verified before calculation is done, see the below

```
Expression e1 = new Expression("if(0 > 1, 0/0, 1)");
Console.WriteLine(e1.getExpressionString() + " = " + e1.calculate());
```
The result is 1

Other verification time based on the computing time - Pi(n) is the prime counting function
```
Expression e1 = new Expression("Pi(10000000)");
Console.WriteLine(e1.getExpressionString() + " = " + e1.calculate() + "   computing time = " + e1.getComputingTime() + "s");
Expression e2 = new Expression("if( 0 > 1, Pi(10000000), 1)");
Console.WriteLine(e2.getExpressionString() + " = " + e2.calculate() + "   computing time = " + e2.getComputingTime() + "s");
```

The result shows clearly that only one term is evaluated
```
Pi(10000000) = 664579   computing time = 12.55s
if( 0 > 1, Pi(10000000), 1) = 1   computing time = 0.008s
```

Best regards

**Comment by precisionterrain** [comment]
Right. That's a fantastically detailed response. Super helpful. I will digest, and re-evaluate my implementation based on these insights.

Thanks so much!
