### ISSUE TITLE
Solving equations - help wanted

### ISSUE THREAD

**Issue by brambossche** [mariuszgromada/MathParser.org-mXparser#19]
Hi, 

I have a simple expression like:  result = -6 + 125 * (value/(2^16)); where value is a runtime number.
This works perfect. What I want to do is calculate the value were result is known and the value must be calculated. Doing this in code is of course not an issue (change the function to calculate value), but this must be runtime. Also the formula is runtime created. What is the best approach ?

**Comment by mariuszgromada** [comment]
It seems like you want to solve equation. Currently this is not supported as mXparser can only calculate the expression value. Of course you can transform your formula at a runtime, then calculate value based on result - but you stated this is not you want to do.

Frankly speaking - you have a point - I can extend mXparser with the capability of numerically solving the equation f(x) = x, i.e. function solve( f(x), x ). I will consider that

**Comment by brambossche** [comment]
Hi Marius, 
Thank you for the answer.
This is exactly what I need. The customers can enter a formula, and can enter min and max ranges. That's why I need this. Any idea when you decide if you will add this ? 
Kind regards

**Comment by mariuszgromada** [comment]
Soon, very soon :-)

**Comment by brambossche** [comment]
;) Thanks :)

**Comment by mariuszgromada** [comment]
Done :-) v.4.0 will be released soon :-)

**Comment by mariuszgromada** [comment]
Please use: solve( f(x), x, a, b ) - solving f(x) = 0

**Comment by mariuszgromada** [comment]
http://mathparser.org/mxparser-tutorial/solving-equation-fx-0/
