### ISSUE TITLE
C# How to dynamically add parameters？

### ISSUE THREAD

**Issue by TotocQ** [mariuszgromada/MathParser.org-mXparser#190]
### Issue title:
- C# How to dynamically add parameters？
### Issue content:
- MathParser.org-mXparser verssion: v.4.3.3
- Framework: .net core

I want to use `Function` to calculate a result. The `Function` is `f(a,b) = add(a) + max(b)`，but how do I set values to `a` and `b`. if `Function` is `f(a,b,c) = add(a) + min(b) + mean(c)`,Then what should I do? The `a`、`b`、`c` is Array

**Comment by mariuszgromada** [comment]
#186 will help here, best regards

**Comment by TotocQ** [comment]
Thanks very much!
