### ISSUE TITLE
Wrong expression of boolean

### ISSUE THREAD

**Issue by superyouyo** [mariuszgromada/MathParser.org-mXparser#192]
### Issue title:
Wrong expression of boolean

[mXparser-v.4.2.0] 
[][a | b & c] 
[][a | b & c] Starting ...
[][a | b & c] a = 1.0
[][a | b & c] b = 0.0
[][a | b & c] c = 0.0
[][a | b & c] Parsing (0, 4)  ---> 1.0 | 0.0 & 0.0  ...  ---> 1.0 & 0.0  ...  done
[][a | b & c] Parsing (0, 2)  ---> 1.0 & 0.0  ...  ---> 0.0  ...  done
[][a | b & c] Calculated value: 0.0
[][a | b & c] Exiting

0.0

**Comment by mariuszgromada** [comment]
In math there is no clear definition on logical operator precedence, but I agree, maybe it would be more clear to introduce it anyway here in mXparser.

**Comment by mariuszgromada** [comment]
You can always use brackets

**Comment by mariuszgromada** [comment]
Fixed
