### ISSUE TITLE
Cannot use variable in right-hand side of 'if' function

### ISSUE THREAD

**Issue by znerd** [mariuszgromada/MathParser.org-mXparser#193]
#### Use Case
I would like to avoid division by zero. Therefore, I'm attempting to use the `if` function, to only divide by an argument, if and only if that argument is non-zero.

Now I'm wondering if I should create a custom function extension.

#### Steps to Reproduce
Execute this Java code:
```
final Expression e = new Expression("if( a==0, 0, 1/a)");
e.setArgumentValue("a", 1);
e.setDescription("Example - verbose mode");
e.setVerboseMode();
mXparser.consolePrintln("Res: " + e.getExpressionString() + " = " + e.calculate());
```

#### Expected Result
1. Expression is considered valid.
2. Result value is 1.0 (result of: 1 divided by 1)

#### Actual Result
1. NOK: Expression is considered invalid.
2. NOK: Result that is output is: NaN.

#### Output
```
[mXparser-v.4.3.0] 
[Example - verbose mode][if( a==0, 0, 1/a)] 
[Example - verbose mode][if( a==0, 0, 1/a)] Starting ...
syntaxStatus == SYNTAX_ERROR_OR_STATUS_UNKNOWN, returning Double.NaN
Res: if( a==0, 0, 1/a) = NaN
[mXparser-v.4.3.0] 
```

#### Extra information:
- MathParser.org-mXparser verssion: v.4.3.3 (even though the console output says 4.3.0)
- Framework: Java 8

**Comment by mariuszgromada** [comment]
Hi,

Try this code:

```
Argument a = new Argument("a");
Expression e = new Expression("if( a==0, 0, 1/a)", a);
a.setArgumentValue(1);
mXparser.consolePrintln(e.getExpressionString() + " = " + e.calculate() + ", whre " + a.getArgumentName() + " = " + a.getArgumentValue());
a.setArgumentValue(0);
mXparser.consolePrintln(e.getExpressionString() + " = " + e.calculate() + ", whre " + a.getArgumentName() + " = " + a.getArgumentValue());
```

Then this one
```
Expression e = new Expression("if( a==0, 0, 1/a)");
mXparser.consolePrintTokens(e.getCopyOfInitialTokens());
mXparser.consolePrintln(e.getMissingUserDefinedArguments());	
```

The other way
```
Expression e = new Expression("if( a==0, 0, 1/a)");
e.addArguments(new Argument("a"));
e.setArgumentValue("a", 1);
mXparser.consolePrintln(e.getExpressionString() + " = " + e.calculate() + ", whre a " + e.getArgumentValue("a"));
e.setArgumentValue("a", 0);
mXparser.consolePrintln(e.getExpressionString() + " = " + e.calculate() + ", whre a " + e.getArgumentValue("a"));
```

Best regards

**Comment by znerd** [comment]
@mariuszgromada : Thanks! That works.

But can you help me understand? Basically all that I was missing was the call to `addArguments(Argument)` – right?

So when I call `setArgumentValue(...)` the argument is not implicitly defined?

**Comment by mariuszgromada** [comment]
You need to add all user elements. This is becouse mXparser has a lot of built-in keywords.
You can use: e.getMissingUserDefinedArguments()

Please read all tutorials
http://mathparser.org/mxparser-tutorial/
http://mathparser.org/mxparser-tutorial/playing-with-expression-tokens/

Plus the API
http://mathparser.org/api/

**Comment by znerd** [comment]
Thanks a lot - all good on my end now!
