### ISSUE TITLE
[C#/Suggestion] Add Timeout for Expression.Calculate()

### ISSUE THREAD

**Issue by GHXX** [mariuszgromada/MathParser.org-mXparser#198]
## New feature
Add Timeout for Expression.Calculate(), which accepts a TimeSpan or an int to specify the number of milliseconds the Expression may run for.

### Example implementation (for the library user)
```cs
Expression e =  new Expression("C(600000,8000000000000000)");
int timeoutMs = 2000;

if (e.TryCompute(timeoutMs, out double result))
{
    Console.WriteLine("The result is: " + result);
}
else
{
    Console.WriteLine("The operation timed out after " + timeoutMs + "ms!");
}
```

### Use case

The use case here comes from keeping programs responsive if the user decides to enter an expression which takes an extraordinary long time to compute, such as computing the binomial coefficient for large values: `C(600000,8000000000000000)`

**Comment by mariuszgromada** [comment]
Hi. Thanks for the suggestion.

This is already supported. Simply run calculate in a separate thread, then, If you need to stop calculation, call for a main thread:

`mXparser.cancelCurrentCalculation()`

API spec: http://mathparser.org/api/org/mariuszgromada/math/mxparser/mXparser.html#cancelCurrentCalculation()

Additionally please take a look on:

```
mXparser.resetCancelCurrentCalculationFlag()
mXparser.isCurrentCalculationCancelled()
```

Best regards

**Comment by GHXX** [comment]
Hmmm, this however will cancel all calculations that may be running at the same time. Is there a way to cancel just one calculation?

**Comment by GHXX** [comment]
Okay, i tried using mXparser.cancelCurrentCalculation(), but it seems that calling it doesnt actually cancel the calculation, at least not in my case.

I am running the calculation in the Task a. And right before starting the calculation the Task a actually creates a Task b which waits for 5 seconds and then calls `mXparser.cancelCurrentCalculation();`

After calling mXparser.cancelCurrentCalculation(); the cpu use remains at one eigth of 100% which indicates that half a core is fully used which means that the math library is still trying to calculate the result. Furthermore, the expression.calculate() method did not return after cancellation happened, so im not sure if cancelling worked in this case.

**Comment by mariuszgromada** [comment]
What is the expression string?

**Comment by GHXX** [comment]
C(600000,8000000000000000)

**Comment by mariuszgromada** [comment]
Ok, I see - this is the case just of binomial coeeficient. Try different expression, i.e.

sum(i, 1, 10000000000, 1)

I will have to fix binomCoeff in MathFunctions.cs

I did not assume that somebody will use such a big number in binomial coefficient -)

You can see the implementation here
https://github.com/mariuszgromada/MathParser.org-mXparser/blob/master/CURRENT/c-sharp/src/org/mariuszgromada/math/mxparser/mathcollection/MathFunctions.cs

Compare
bellNumber vs binomCoeff

There is no "if (mXparser.isCurrentCalculationCancelled()) return Double.NaN;" 

But it works for a majority of heavy functions

Best regards

**Comment by mariuszgromada** [comment]
Please let me know whether other examples worked for you, I will fix the other functions soon :-) This is simple.

Best regards

**Comment by GHXX** [comment]
well, Sum should be a super quick operation, and the Bell() operation is very memory intensive rather than taking a long time to compute, so these arent good for testing unfortunately.

**Comment by GHXX** [comment]
and Bell(100000) dies because of a `System.OutOfMemoryException: Array dimensions exceeded supported range.`

**Comment by mariuszgromada** [comment]
sum can be an extremely slow operation, in math you have a lot of nested sums - you can write

sum(i, 1, 1000, i  + sum(j, 1, i, 2*j) )

Bell numbers - you have a 2 dimensional array
long[,] bellTriangle = new long[n+1, n+1];

And you put ... n = 100000

This parser is not for this kind of computation ... you are out of .net framework scope now as arrays are limited to the int size...

Why do you need bell number or combinations number that are bigger than the number of atoms in the universe?

Best regards

**Comment by GHXX** [comment]
Ah, sum(i, 1, 1000, i + sum(j, 1, i, 2*j+ sum(j, 1, i, 2*j)) ) did the trick, looks like timing out does work properly, so thats good.

And to answer the question why i am tossing in such big values, its because its a good practice to make sure the program doesnt break or lock up under any circumstances

**Comment by mariuszgromada** [comment]
You may find some cases like that, but this can happen only on arrays declaration - easy to fix. I am using this in few methods, really I was not expecting somebody will put C(n,m) for trillions :-))))

Generally speaking - mXparser is tested broadly.

Best regards

**Comment by GHXX** [comment]
Could probably come up with a unit test method which tests all math functions with values like 1 0 -HUGE and HUGE, where HUGE is a value like 10^20 or so, which should cover most of the cases where stuff could go wrong

**Comment by mariuszgromada** [comment]
I will add simply some verification and return NaN in case it does not fit.

For the recursion I have generic prevention mechanism, bot not for the arrays.

Best

**Comment by GHXX** [comment]
👍  Sounds good, and please dont forget to implement the exit check for the C function

**Comment by mariuszgromada** [comment]
Fixed :-)

The time out should be implemented via cancel current calculation

**Comment by mariuszgromada** [comment]
https://www.nuget.org/packages/MathParser.org-mXparser/4.4.2

**Comment by GHXX** [comment]
okay nice thanks

**Comment by mariuszgromada** [comment]
Expression.Calculate is not a good place to add the feature you requested. I have other idea.

There is a mXparser sealed class (c#) / final (java) class acting as a options store, etc..

In mXparser class I will add the "engine" functionally, e.g.:

```
int mXparser.startCalculationProcess(Expression e);
int mXparser.startCalculationProcess(Expression e, int timeout);
```
Above will return the process id, will start the e.calculate() in the separate thread, will keep the list of active processes, will store the result, etc..

Using process id you will be able to retrieve the value or check the state asynchronously.

I will design the API.

Generally there will an option to list all the active processes + stop the selected ones.

Best regards

**Comment by GHXX** [comment]
Will it run in a different process or thread? (You kindof mixed them)

**Comment by mariuszgromada** [comment]
Yes, separate threads + one mian thread to controll.

**Comment by 13xforever** [comment]
what happened to `.startCalculationProcess()`? it is still impossible to cancel specific expression calculation
