### ISSUE TITLE
System.format.exception - system.IO.EndOfStreamException

### ISSUE THREAD

**Issue by brambossche** [mariuszgromada/MathParser.org-mXparser#20]
Hi Marius, 

We have 2 (pc's) setups which  have  identical source code and packages.
On one pc we get System.format.exception - system.IO.EndOfStreamException several time when using
checksyntax. 
We tried playing with culturesettings but we don't find were it goes wrong. The setargument value is of type double. 

               Argument _inputArgumentValue = new Argument("value", 0);
               Expression _expresion;
                _inputArgumentValue.setArgumentValue(value); //value is a double
              
		_expresion = new Expression(mv.InvCalculationExpression, _inputArgumentValue);
				
                if (_expresion.checkSyntax())
                {
                    double temp = _expresion.calculate();
                    return double.IsNaN(temp) ? 0 : temp;
                }
                else
                {
                    return 0;
                }

Detailed window
http://imgur.com/a/BzY42

Any idea ?

Regards

**Comment by mariuszgromada** [comment]
This can be due to parser generated by CSJavaCC, which is a port of JavaCC to C# .NET. I am using it to define the mXparser's grammar. In a few days I will be releasing mXparser-v.4.0, with slight modification of grammar, and SysntaxChecker generated by CSJavaCC that includes few fixed bugs. We will se. If you want - I can share pre-release dll with you - just to check if that helps. Please let me know.

**Comment by roosek** [comment]
Hi i am working on the project toghether with bram and i linked in the code for 4.0 from github to give it a try.

The format exceptions keep occuring ( they are caught but they cause a tremendous slowdown as our main dataobject is performing calculations at every update. 

I have been looking myself at 
Expressions.cs

for (int i=pos; i<newExpressionString.Length; i++) {
					String str = newExpressionString.Substring(pos, i+1-pos);
					/*
					if (    mXparser.RegexMatch(str, ParserSymbol.NUMBER).Success )
					{
						numEnd = i;
						mXparser.consolePrintln("Regex -> |" + str + "=number" + " " + pos + ", " + i);
					}*/
					try
					{
						Double.Parse(str, NumberStyles.Float, CultureInfo.InvariantCulture);
						numEnd = i;
					}
					catch (Exception e)
					{
						errorMessage = e.Message;
						syntaxStatus = SYNTAX_ERROR_OR_STATUS_UNKNOWN;
					    i = newExpressionString.Length;
					}
				}

notice the  i = newExpressionString.Length;
when adding this into the catch we can already avoid the bulk of the exceptions being thrown as otherwise we keep trying to double parse  ( 0+ , 0+1 , 0+10 ) while we already now after the first fail that we are not dealing with a number. 

The whole method for tokenizeExpressionString seems to be quite clunky & slow in my opinion, im not sure if i would have the time but would you be intrested in my attempt at trying to get it to run faster? 

I would like to opt for a method were we first start splitting on operators, instead of scanning for values, or is there some obvious drawback to this im not seeing?

**Comment by mariuszgromada** [comment]
Ahh, I think I know the problem - is this the same as here https://github.com/mariuszgromada/MathParser.org-mXparser/issues/11

If yes - it will be corrected for sure before release.

Best regards

**Comment by mariuszgromada** [comment]
And yes - you can contribute - but pls wait a moment as I would like to rethink some issues on tokenizing, especially allowing for real constants in the scientific format t(i.e 1.2E10).

What is important - the whole project is driven form java, then ported to C# as I am not .net expert - It means that those methods should be equal in java and C#.

**Comment by mariuszgromada** [comment]
And once again - yes - the tokenizeExpressionString() is the worst written method in the whole mXparser. The whole project evolved form the idea of writing simple tokenizer. Now it is a quite big solution, especially v.4.0, and it deserve for a good tokenizer.

**Comment by roosek** [comment]
so if i were to have a btter tokenizer it you wouldnt really be able to use it as we are using generated code?

**Comment by mariuszgromada** [comment]
roosek - Unfortunately, I think my English is not good enough to understand what you meant. Can extend your thoughts?

**Comment by roosek** [comment]
I was thinking to write my own splitter especially for this , but you still wont be able to use it if the current tokenizer is autogenerated code

**Comment by roosek** [comment]
Its not that bad tbh, if only we could get rid of the try/catch

**Comment by mariuszgromada** [comment]
Current tokenizer is not autogeretaed code. Only the part of syntax checking is done based on grammar and the JavaCC auto-generated code. The tokenizeExpressionString() method was written by me 7 years ago - and for sure it can be much better. While extending mXparser I was focused on new functionalities rather on cleaning tokenizeExpressionString() method. And - frankly speaking - it might be a good time to clean it - as project evolved significantly and is used by the community.

I will we very happy if you could  do that and contribute to mXparser making it much better. You have a lot of regression tests (more than 600) to check you implementation. If it pass all of this - for sure it will be ok :-)

With cleaning tokenizer I would wait a bit to include scientific numbers representations. I did it for java based on regexp, then decided to withdraw the change as regexp's handled differently between Java and C#.

My goal is to keep API's and the whole parser working exactly the same in Java and C#.


Thanks in advance

**Comment by mariuszgromada** [comment]
I do not have try and catch in java implementation - this is only in .net as I was missing options while porting.

**Comment by mariuszgromada** [comment]
Please see this: https://github.com/mariuszgromada/MathParser.org-mXparser/commit/e78d25a5315f68739d1b5922de7c068903dcdf1e

**Comment by mariuszgromada** [comment]
For me - cleaning the tokenizeExpressionString() - means imprinting performance (i.e. limiting ranges of loops) and introducing scientific notation for real constants.

**Comment by roosek** [comment]
I was trying to commit something quite similar to this but unfortunatly im either doing it wrong ( quite new on contributing to github ) or im not allowed to push changes

**Comment by roosek** [comment]
double parsed;
                    if (double.TryParse(str.ToString(), out parsed))
                    {
                        numEnd = i;
                    }
                    else
                    {
                        errorMessage = "failed to parse number";
                        syntaxStatus = SYNTAX_ERROR_OR_STATUS_UNKNOWN;
                        i = newExpressionString.Length;
                    }


This was my solution, 

Pls note i also added the escape clause in the else, unless im mistaken we can break the for after the first failure to parse a double

**Comment by mariuszgromada** [comment]
change commited

**Comment by mariuszgromada** [comment]
In terms of "escape clause" - the goal is to find the longest sub-string, which is a number. In some cases it could be beneficial to start from the end and then perform "i--" instead of staring for the left and doing "i++".
