### ISSUE TITLE
Add keyword lg - logarithm with base 10 to Unary Functions.

### ISSUE THREAD

**Issue by Phanquan** [mariuszgromada/MathParser.org-mXparser#201]
Just found out that logarithm with base of 10 doesn't have keyword in the Unary Functions, should we include it?

- The keyword of logarithm with base of 10 is not a thing while it usually refers to log(x), lg(x) or even Log(x)
- The logarithm with base 10 should be referred to lg(x) as ISO/IEC 80000 recommends.
- Exp: 
```
// return 2.0
new Expression("lg(100)").calculate()
```

**Comment by mariuszgromada** [comment]
There is log10(x), log is binary function log(a,b).

I can consider adding lg(x) = log(10,x)

**Comment by mariuszgromada** [comment]
Done
