### ISSUE TITLE
Parsing error on 0 + 48060.774 + 0 + -172808.43 + 0

### ISSUE THREAD

**Issue by gustavolealgtz** [mariuszgromada/MathParser.org-mXparser#202]
### Issue title:
- Why this string cannot be parsed?

### Issue content:
I have this in a string `"0 + 48060.774 + 0 + -172808.43 + 0"` I get parsing error **Value was either too large or too small for a Decimal.**

I think is becasue is getting _blank_ after minus sign, how can I solve this?

**Comment by mariuszgromada** [comment]
This is a bit incorrect in terms of math conventions, you should use

"0 + 48060.774 + 0 + (-172808.43) + 0"

But I will check how to solve that

Best regards

**Comment by mariuszgromada** [comment]
What is the mXparser version do you use?

```
[mXparser-v.4.4.2 bin .NET 4.5] [0 + 48060.774 + 0 + -172808.43 + 0] checking ...
[0 + 48060.774 + 0 + -172808.43 + 0] lexical error

Encountered "+ -" at line 1, column 19.
Was expecting one of:
    <EOF>
    "+" ...
    "-" ...
    "*" ...
    "/" ...
    "^" ...
    "^^" ...
    "#" ...
    "!" ...
    "%" ...
    <EQ> ...
    <NEQ> ...
    "<" ...
    "<=" ...
    ">" ...
    ">=" ...
    <OR> ...
    <AND> ...
    "-->" ...
    "<--" ...
    "-/>" ...
    "</-" ...
    <NAND> ...
    "<->" ...
    <NOR> ...
    <BITWISE> ...
    "(+)" ...

[0 + 48060.774 + 0 + -172808.43 + 0] errors were found.
Problem with expression syntax
```

**Comment by mariuszgromada** [comment]
v 4.4.2 behaves correctly, meaning does not allow to calculate this expression

**Comment by gustavolealgtz** [comment]
I am using v 4.4.2 .NET 4.6.1 Let me know if you need more information.

**Comment by mariuszgromada** [comment]
Can you share the code?

**Comment by gustavolealgtz** [comment]
Sorry, I can't, formulas are stored in DB and the data came from Excel and the information is restricted (Sales, Volumes and those stuffs).

**Comment by mariuszgromada** [comment]
I am not able to replicate tour case. The string your provided can not be calculated, you should get syntax error and proper error message. Decimal related error should not appear.

See my test code:

```
Expression e = new Expression("0 + 48060.774 + 0 + -172808.43 + 0");
bool syntax = e.checkSyntax();
mXparser.consolePrintln("syntax = " + syntax);
mXparser.consolePrintln("error message = ");
mXparser.consolePrintln(e.getErrorMessage());
```

**Result**

```
[mXparser-v.4.4.2 bin .NET 4.6.1] syntax = False
[mXparser-v.4.4.2 bin .NET 4.6.1] error message =
[mXparser-v.4.4.2 bin .NET 4.6.1] [0 + 48060.774 + 0 + -172808.43 + 0] checking ...
[0 + 48060.774 + 0 + -172808.43 + 0] lexical error

Encountered "+ -" at line 1, column 19.
Was expecting one of:
    <EOF>
    "+" ...
    "-" ...
    "*" ...
    "/" ...
    "^" ...
    "^^" ...
    "#" ...
    "!" ...
    "%" ...
    <EQ> ...
    <NEQ> ...
    "<" ...
    "<=" ...
    ">" ...
    ">=" ...
    <OR> ...
    <AND> ...
    "-->" ...
    "<--" ...
    "-/>" ...
    "</-" ...
    <NAND> ...
    "<->" ...
    <NOR> ...
    <BITWISE> ...
    "(+)" ...

[0 + 48060.774 + 0 + -172808.43 + 0] errors were found.

```

**Comment by gustavolealgtz** [comment]
What does means "Lexical error"?, seems do not understand  + - even that the minus sign is followed by a number. I got the same issue when the formula is similar. See the next result:

`[327.1232301 + 0 + 0 + 0 + 515.71749 + 495.3492397 + -4.2768999 + 0.5999997 + 117.3832791] checking ...
[327.1232301 + 0 + 0 + 0 + 515.71749 + 495.3492397 + -4.2768999 + 0.5999997 + 117.3832791] lexical error 

Encountered "+ -" at line 1, column 51.
Was expecting one of:
    <EOF> 
    "+" ...
    "-" ...
    "*" ...
    "/" ...
    "^" ...
    "^^" ...
    "#" ...
    "!" ...
    "%" ...
    <EQ> ...
    <NEQ> ...
    "<" ...
    "<=" ...
    ">" ...
    ">=" ...
    <OR> ...
    <AND> ...
    "-->" ...
    "<--" ...
    "-/>" ...
    "</-" ...
    <NAND> ...
    "<->" ...
    <NOR> ...
    <BITWISE> ...
    "(+)" ...
    
[327.1232301 + 0 + 0 + 0 + 515.71749 + 495.3492397 + -4.2768999 + 0.5999997 + 117.3832791] **errors were found**.
`

**Comment by gustavolealgtz** [comment]
By the way I will rework to add parenthesis in the numbers to avoid this, I hope you solve this.

**Comment by mariuszgromada** [comment]
+- is not allowed in math syntax, this is deliberate., you should always bracket this. This is according to math conventions.

You may use user arguments for that.

Best regards

**Comment by mariuszgromada** [comment]
Lexical error means that this is not according to the defined grammar.

**Comment by mariuszgromada** [comment]
I will consider allowing this

**Comment by mariuszgromada** [comment]
If you have arguments that are used to build expression 
0 + 48060.774 + 0 + -172808.43 + 0

x = 0
y = 48060.774
z = 0
u = -172808.43
v = 0

simply use
x + y + z + u + v

it will be faster as expression is parsed just once, the you can change arguments value and the results is given much much faster. You will avoid this conventions problems like 0 + -100, according to math standards it should always be specified as 0 + (-100).

Best regards

**Comment by Phanquan** [comment]
I faced that issue once, It throws error due to this part:

> 0 + 48060.774 + 0 **+ -**172808.43 + 0

it should be "+" instead of "+-", still, I guess you tried to parse the value into the formula while the value was negative.

**Comment by gustavolealgtz** [comment]
@Phanquan if you use the data `0 + 48060.774 + 0 + -172808.43 + 0` in an Excel you get the result of **-124748**, as you can see Excel do not send any error and can deal with this kind of formula. But as said before I will enclose all values in parenthesis to avoid this issue. Thank you for your comment.

**Comment by mariuszgromada** [comment]
@gustavolealgtz this is not the case whether parser can deal, It is simple to allow this, even now. But I am not sure whether I should introduce something out of math conventions...

I decided to block this on the grammar level.

As I said, maybe I will reconsider.

Best regards

**Comment by gustavolealgtz** [comment]
Don´t worry @mariuszgromada fortunately there is a solution and it doesn't stop my project. :)

**Comment by mariuszgromada** [comment]
It seems you are building your expression automatically - am I right? Why not to use user arguments? It will be much mich faster, really.

Try something like this - considering tour case:

```
Argument x = new Argument("x");
Argument y = new Argument("y");
Argument z = new Argument("z");
Argument u = new Argument("u");
Argument v = new Argument("v");
Expression e = new Expression("x + y + z + u + v", x, y, z, u, v);
x.setArgumentValue(0);
y.setArgumentValue(48060.774);
z.setArgumentValue(0);
u.setArgumentValue(-172808.43);
v.setArgumentValue(0);
double r1 = e.calculate();
x.setArgumentValue(1);
y.setArgumentValue(2);
z.setArgumentValue(3);
u.setArgumentValue(4);
v.setArgumentValue(5);
double r2 = e.calculate();
```

Or, there is a nice option with user function
```
Function f = new Function("f(x, y, z, u, v) = x + y + z + u + v");
double r1 = f.calculate(0, 48060.774, 0, -172808.43, 0);
Expression e = new Expression("f(0, 48060.774, 0, -172808.43, 0)", f);
double r2 = e.calculate();
```

Most probably I will extend the grammar here and regenerate the lexer / parser.

Best regards

**Comment by gustavolealgtz** [comment]
@mariuszgromada Thank you for your suggestions.

Let me explain a little bit more about the requirements of the proyect, maybe we can find something togather.

As I said before the information comes from Excel files (from many countries) each month our department collects the information based on KPI´s (stored in a DB), each KPI have some configuration; if is a formula or is a user input and may or not depend on other KPI (this part is working fine), the "big issue" is that the each KPI can have different number of arguments ( or variables ). This is why thinking about refactoring mi proyect is not good idea for now, adding the parenthesis is working for now.

I hope this clarify any doubt regarding my negative to do some changes.

Regards

**Comment by mariuszgromada** [comment]
@gustavolealgtz of course I understand, whenever you are ready to change, use my advice on user arguments, user functions, and even dependent arguments. 

Best regards

**Comment by mariuszgromada** [comment]
v.5.0 - done

**Code:**
```
Expression e = new Expression("0 + 48060.774 + 0 + -172808.43 + 0");
mXparser.consolePrintln(e.calculate());
mXparser.consolePrintln(e.getErrorMessage());
```

**Result:**
```
[mXparser-v.5.0.0 bin JDK 8] -124747.656
[mXparser-v.5.0.0 bin JDK 8] [0 + 48060.774 + 0 + -172808.43 + 0] checking ...
[0 + 48060.774 + 0 + -172808.43 + 0] no errors.
```
