### ISSUE TITLE
Add parentheses to a mathematical expression

### ISSUE THREAD

**Issue by onkarjit** [mariuszgromada/MathParser.org-mXparser#204]
I was looking for a way in C# to add parenthesis to mathematical expression strings.

So for example: `5^2*3*5` should be turned into `((5 ^ 2) * 3) * 5`.

I tried using mXparser, and it's great at parsing mathematical expression strings, however, it doesn't have a method to add parentheses to the original expression. The only method I could find is getExpressionString() but it doesn't add parentheses to the expression.

I used to use math.js which did give the option to added parentheses to expressions. However, I have moved to C# for this project and was hoping for a C# solution. It would be really great if mXparser could transform expression to have parentheses.

**Comment by onkarjit** [comment]
@mariuszgromada

**Comment by mariuszgromada** [comment]
mXparser does not add parenthesis, mXparser follows logic of math operators without parenthesis. Parenthesis are used by the user to force different (than standard) order of operations.

Best regards
