### ISSUE TITLE
exemple on your site

### ISSUE THREAD

**Issue by w77** [mariuszgromada/MathParser.org-mXparser#210]
Hello,

Can't you just type the code instead of this animated gif ?
I must wait 10 minutes every time I want to read the last line. 
This is probably the worst way to show code.

Thanks

**Comment by mariuszgromada** [comment]
Have you tried this manual?
http://mathparser.org/mxparser-tutorial/

**Comment by mariuszgromada** [comment]
Can I close the case?

**Comment by w77** [comment]
I saw this video later. But a simple gif would be better.
Thank you for your answer.
Yes you can close it.
