### ISSUE TITLE
irregularity in the time taken evaluating the same expression

### ISSUE THREAD

**Issue by herme063** [mariuszgromada/MathParser.org-mXparser#211]
I have this code:

    using System;
    using System.Collections.Generic;
    using System.Linq;
    using Newtonsoft.Json;
    using org.mariuszgromada.math.mxparser;
    
    namespace PerfConsoleApp
    {
    	class Program
    	{
    		static void Main(string[] args)
    		{
    			var som = new DateTime(2000, 1, 1);
    			IList<DateTime> intervals = Enumerable.Range(0, 744)
    				.Select(h => som.AddHours(h))
    				.ToList();
    
    			IList<int> attributes = Enumerable.Range(0, 1250)
    				.Select(a => a)
    				.ToList();
    
    			var expressionComputeTime = new List<double>();
    			var expressionComputeSw = new List<double>();
    
    			IDictionary<string, Argument> argumentIndex = new[]
    			{
    				new Argument("X1", double.NaN),
    				new Argument("X2", double.NaN),
    				new Argument("X3", double.NaN),
    			}.ToDictionary(a => a.getArgumentName());
    
    			Expression expression = new Expression(
    				"coalesce(X1, 0) + coalesce(X2, 0) + coalesce(X3, 0)",
    				argumentIndex.Values.Cast<PrimitiveElement>().ToArray());
    
    			var calcStart = mXparser.currentTimeMillis();
    			foreach (var i in intervals)
    			{
    				foreach (var a in attributes)
    				{
    					expression.setArgumentValue("X1", a % 5 == 0 ? double.NaN : a * 5);
    					expression.setArgumentValue("X2", a % 7 == 0 ? double.NaN : a * 2);
    					expression.setArgumentValue("X3", a % 3 == 0 ? double.NaN : a * 1.5);
    					var calculateStart = mXparser.currentTimeMillis();
    					expression.calculate();
    					expressionComputeSw.Add(mXparser.currentTimeMillis() - calculateStart);
    					expressionComputeTime.Add(expression.getComputingTime());
    				}
    			}
    			var calcEnd = mXparser.currentTimeMillis();
    
    			Console.WriteLine(JsonConvert.SerializeObject(new
    			{
    				Elapsed = calcEnd - calcStart,
    				ExpressionComputeTime = new
    				{
    					Count = expressionComputeTime.Count,
    					Average = MathNet.Numerics.Statistics.Statistics.Mean(expressionComputeTime),
    					Median = MathNet.Numerics.Statistics.Statistics.Median(expressionComputeTime),
    					Min = MathNet.Numerics.Statistics.Statistics.Minimum(expressionComputeTime),
    					Max = MathNet.Numerics.Statistics.Statistics.Maximum(expressionComputeTime)
    				},
    				ExpressionComputeSw = new
    				{
    					Count = expressionComputeSw.Count,
    					Average = MathNet.Numerics.Statistics.Statistics.Mean(expressionComputeSw),
    					Median = MathNet.Numerics.Statistics.Statistics.Median(expressionComputeSw),
    					Min = MathNet.Numerics.Statistics.Statistics.Minimum(expressionComputeSw),
    					Max = MathNet.Numerics.Statistics.Statistics.Maximum(expressionComputeSw)
    				}
    			}, Formatting.Indented));
    
    			Console.Write("Press Enter...");
    			Console.ReadLine();
    		}
    	}
    }

I get the following result:

    {
      "Elapsed": 4241,
      "ExpressionComputeTime": {
        "Count": 930000,
        "Average": 4.1150537634412193E-06,
        "Median": 0.0,
        "Min": 0.0,
        "Max": 0.093
      },
      "ExpressionComputeSw": {
        "Count": 930000,
        "Average": 0.004390322580645198,
        "Median": 0.0,
        "Min": 0.0,
        "Max": 103.0
      }
    }

I have 2 questions:

1- What's with the gap between **stopwatch** and **getComputingTime()**?

2- What's with the gap between Max and Average (especially stopwatch measurement)?

Thank you,

**Comment by mariuszgromada** [comment]
Max most likely will be the first call of calculate(), where all pre-compilation is done. You are just changing argument values, so mXparser calculates it really fast after the first call of calculate() method. Remove for the stats first iteration and then rerun your test.

Best regards

**Comment by herme063** [comment]
You are correct; the first measurement was the main outlier.
