### ISSUE TITLE
canonical rounding performance

### ISSUE THREAD

**Issue by herme063** [mariuszgromada/MathParser.org-mXparser#214]
I am currently investigating performance issue in our calculation engine which is a wrapper around mxparser. 
During profiling, there are call(s) to MathFunctions.canonicalRound(Double) that are taking around 30% of the time spent by Expression.calculate().

![image](https://user-images.githubusercontent.com/13970764/95867158-75be6200-0d2e-11eb-9c0c-cf701c1f3ba0.png)

What is this for? I looked at the source code and it looks like .ToString() + .Parse().

Thanks,

**Comment by mariuszgromada** [comment]
Hi, thank you for your question.

mXparser uses double representation for numbers, so it might happen that you will see the artifact on calculation. The famous example is 0.1+0.1+0.1.

Take a look here
https://0.30000000000000004.com/

Double gives a huge flexibility - you can work both on very small and very big.

Anyway, I wanted to make some intelligent rounding to minimize the problem appearance.

At the begging I added  almostIntRounding option - this was ok, but it eliminates calculation on a very small values.
Later I added ULP rounding (Unit in The Last Place rounding) - it was slower, but worked better, but still - in many cases was producing floating point artifacts.
Recently, in the newest version I added canonical rounding, which is slow, but solves majority of artifacts.

You have all the options to request how mXparser should behave - only canonical rounding is set as default mode.

mXparser.disableAlmostIntRounding();
mXparser.disableUlpRounding();
mXparser.disableCanonicalRounding();

mXparser.enableAlmostIntRounding();
mXparser.enableUlpRounding();
mXparser.enableCanonicalRounding();

mXparser.checkIfAlmostIntRounding();
mXparser.checkIfUlpRounding();
mXparser.checkIfCanonicalRounding();

To have best performance
mXparser.disableAlmostIntRounding();
mXparser.disableUlpRounding();
mXparser.disableCanonicalRounding();


Best regards

**Comment by mariuszgromada** [comment]
Please let me know also what kind of expressions do you calculate? Do you use arguments with precompilation? mXparser is very fast for the expressions with parameters defined, then parameters changed, then expression is recalculated without the parsing/tokenization and syntax checking stuff. Just first call is slow.

**Comment by mariuszgromada** [comment]
http://mathparser.org/api/org/mariuszgromada/math/mxparser/mXparser.html#enableCanonicalRounding()

**Comment by herme063** [comment]
Thank you very much for the detailed answer.

The expressions are mainly user defined. 
We provide a formula editor where they have access to all built-in mxparser functions. 
The general pattern is as follow:
- parse the formula to identify the variables needed
- create 1 expression and as many arguments as needed (based on the 1st step)
- input data are time series, so for each interval we set the argument values, then call expression.calculate()

I previously benchmarked .calculate() and did notice the overhead in the first call.

**Comment by mariuszgromada** [comment]
Thanks. So you add arguments etc. Ok, then it should be fast.

I assume my advice helped. Shall we close the issue?

Best regrads
