### ISSUE TITLE
A+C is NaN

### ISSUE THREAD

**Issue by zhongxd26** [mariuszgromada/MathParser.org-mXparser#215]
### Issue title:
- Short and meaningfull
        Argument AA = new Argument("A = 12.0");
        Argument BB = new Argument("C = 34.0");
        Expression CC = new Expression("A+C", AA,BB);
        mXparser.consolePrintln(CC.getExpressionString() + "----" + CC.calculate());
### Issue content:
       system print:       
                 [mXparser-v.4.4.2 bin JDK 8] A+C----NaN
#### If bug/question:
- MathParser.org-mXparser verssion: mXparser-v.4.4.2 bin JDK 8
- Framework: java, .net, .net core, .net standard, Xamarin, Android, iOS ... + framework verssion
      java 
- Problem description
- Code example
 
#### If new feature
- Feature description
- Use case description

**Comment by mariuszgromada** [comment]
"C" is a reserved keyword, C is a function of two arguments. You can always analyze syntax error.
```
CC.checkSyntax();
mXparser.consolePrintln(CC.getErrorMessage());
```
The error is
```
[mXparser-v.4.4.2 bin JDK 8] [A+C] checking ...
[A+C] (C) Duplicated <KEYWORD>.
[A+C] (C, 2) <FUNCTION> expecting 2 arguments.
[A+C] errors were found.
Problem with expression syntax
```
You can list all reserved keywords here
`mXparser.consolePrintHelp();`

How to solve you problem?

- Option 1: change the name of "C" to something else.
- Option 2: remove "C" from reserved keywords.
`mXparser.removeBuiltinTokens("C");`
- Option 3: modify "C" reserved keyword renaming reserved keyword
`mXparser.modifyBuiltinToken("C", "C1");`

Please follow the tutorial of mXparser

- http://mathparser.org/mxparser-tutorial/
- http://mathparser.org/mxparser-tutorial/built-in-tokens-key-words-manipulation/
- http://mathparser.org/api/

Best regards
