### ISSUE TITLE
expecting tokens in error message

### ISSUE THREAD

**Issue by MicheleTommaso** [mariuszgromada/MathParser.org-mXparser#218]
Hi,
sorry for my English 
It would be useful to have, after a checkLexSyntax, an array of expecting tokens in addition to the error message.

**Comment by mariuszgromada** [comment]
Take a look here:
- http://mathparser.org/mxparser-tutorial/playing-with-expression-tokens/

And here
- http://mathparser.org/api/org/mariuszgromada/math/mxparser/Expression.html#getMissingUserDefinedArguments()
- http://mathparser.org/api/org/mariuszgromada/math/mxparser/Expression.html#getMissingUserDefinedFunctions()
- http://mathparser.org/api/org/mariuszgromada/math/mxparser/Expression.html#getMissingUserDefinedUnits()
