### ISSUE TITLE
MxParser is very slow when running on debian/mono/C# app

### ISSUE THREAD

**Issue by dataq-instruments** [mariuszgromada/MathParser.org-mXparser#219]
### Issue title:
- MxParser is very slow when running on debian/beagleboneblack/mono/C# app

### Issue content:
 I just put 0.23434+3434 in my equation, and perform

f1 = myxpression.calculate();
f2 = myexpression.getComputingTime();

f2 returns 82ms, in fact, when I just change the equation to 0.343421342 (meaning no calculation), it still takes 80ms to execute

Is there any switch to optimize the performance?

#### If bug/question:
- MathParser.org-mXparser verssion: v.4.4.0
- Framework: c# app running on debian/beagleboneblack/mono
- Problem description
- Code example
                                            e1 = new Expression("0.343421342 ");
                                            f1 = e1.calculate();
                                            f2 = e1.getComputingTime();

**Comment by mariuszgromada** [comment]
Whenever you change or set expression string then mXparser does string tokenization. This is quite have process as mXparser needs o recognize all the tokens, and there are a plenty of options here as mXparser is very rich. If you did not change expression string, but just only argument values were modified, then mXparser uses a pre-compiled version of expression.

```
Take a look here
Argument x = new Argument("x = 3");
Argument y = new Argument("y = 4");
Expression e = new Expression("2+x+y", x, y);
e.checkSyntax();

/* now you are ready for fast calculations */
e.calculate();
x.setArgumentValue(5);
y.setArgumentValue(6);
e.calculate();
```

There are options than can speedup the calculation process, but not the pre-compilation process.
```
mXparser.disableAlmostIntRounding();
mXparser.disableCanonicalRounding();
mXparser.disableUlpRounding();

```
Best regards

**Comment by dataq-instruments** [comment]
Thanks for the reply!

I will set up the expressions as static so that I can access them from multiple functions.  If I need to change the expression, do I just use new to create a new one or, should i use other method? do i need to somehow kill the old expression to prevent memory leak?

**Comment by mariuszgromada** [comment]
Take a look here
API spec: http://mathparser.org/api/
Tutorial: http://mathparser.org/mxparser-tutorial/

Basically it depends what you want to do ... You can use "new", you can change expression string, manage arguments, manage user defined functions. The API is really broad.

Best regards

**Comment by mariuszgromada** [comment]
Especially this one: http://mathparser.org/api/org/mariuszgromada/math/mxparser/Expression.html

**Comment by mariuszgromada** [comment]
To understand how mXparser is constructed and what are the risk of memory leaks if you do not understand the hidden layer of relations between objects, please read this topic: https://github.com/mariuszgromada/MathParser.org-mXparser/issues/185
