### ISSUE TITLE
List argument

### ISSUE THREAD

**Issue by h-code** [mariuszgromada/MathParser.org-mXparser#22]
Hello,

It would be great to make some calculation on Java Collections or Arrays of Double

Expression e = new Expression("add(x)");
e.addArguments(new Argument("x", new Double[]{1.0, 2.0 , 3.0}));

PS: Thanks for making alive this great library

**Comment by mariuszgromada** [comment]
The idea is nice, especially thinking about vectors. But this requires a lot of changes in architecture,. Majority of functions are working only on one single value. Introducing new List argument would be pretty easy, but then the whole code for "one single value" needs to be redeveloped to handle this kind of situations - i.e. sin(x) when x is a list ...

**Comment by mariuszgromada** [comment]
And thanks for your "thanks" :-) It is really important to me!

**Comment by h-code** [comment]
I understand.
Could it be possible for me to add my custom function in the current release ?

**Comment by mariuszgromada** [comment]
Yes. Follow case nr 5
http://mathparser.org/mxparser-tutorial/user-defined-functions/

Regards

**Comment by h-code** [comment]
I read the tutorial but don't see how to handle an array of double as a parameter of a FunctionExtension

Regards,
(Thxs for maven repository)

**Comment by mariuszgromada** [comment]
I think I am not sure what you are trying to achieve. At the beginning you were asking about argument (i.e. 'X') containing array of doubles - this is not supported, you need to put all the parameters separated by comma. FunctionExtension interface provides possibility to implement your own function, but this function will still get comma separated list of parameters as parser expects functions of such kind... Can you give more details? Some code would be the best :-)

**Comment by h-code** [comment]
I have two needs, 

1/  We are measuring voltage on 3-phase device (v1, v2, v3) or 1-phase device (v1).
I need an average value. if v2 and v3 are not defined (Double.NaN) then the average = v1.
  
```java 
     Expression e = new Expression("mean(v1,v2,v3)");


        e.addArguments(new Argument("v1",200));
        e.addArguments(new Argument("v2",250));
        e.addArguments(new Argument("v3",220));
        System.out.println("Res 1: " + e.getExpressionString() + " = " + e.calculate());

```

```
Res 1: mean(v1,v2,v3) = 223.3333333333333
 ```
 If I have no v2 and v3 
  ```java 
       e.addArguments(new Argument("v2",Double.NaN));
        e.addArguments(new Argument("v3",Double.NaN));
 ```
then I got NaN instead of v1
 ```
Res 1: mean(v1,v2,v3) = NaN
 ```

 I tried to define a IsNan function and use an expression like : 
 ```
 if(IsNan(v2)=1,v1,mean(v1,v2,v3) 
 ```
but it failed because as v2 is not defined !
Any work around  ? 

2/ the second need  is to make the sum of an energy on variable list of devices (let's say 10 devices).  Depending on the timestamp I could have between 0 and 10 values to sum.  How could I define an expression ? As far as I understand I should calculate it on my own ?

**Comment by mariuszgromada** [comment]
Question 1: Great idea, I will add IsNaN function :-) Or even more - it would be good to add coalesce as well. This should be simple.

Question 2: Please correct me if I am wrong - you have
dev_1 .. dev_n - those are arguments

Here you can use
add(dev_1, ..., dev_n)
assuming that dev_i = 0 when there is no measurement for the device "i".

General remark: I think I have and idea how to introduce a proxy for lists - this could be done via function, which will be a sequence :-)

**Comment by mariuszgromada** [comment]
Check this proxy

class List implements FunctionExtension {
	double[] values;
	int index;
			
	List(int[] values) {
		if ( (values != null) && (values.length > 0) ) {
			this.values = new double[values.length];
			for (int i = 0; i < values.length; i++)
				this.values[i] = values[i];
		}
	}
			
	List(double[] values) {
		if ( (values != null) && (values.length > 0) ) {
			this.values = new double[values.length];
			for (int i = 0; i < values.length; i++)
				this.values[i] = values[i];
		}
	}
			
	public int getParametersNumber() {
		return 1;
	}
	public void setParameterValue(int argumentIndex, double argumentValue) {
		if (argumentIndex == 0) index = (int)MathFunctions.floor(argumentValue);
	}
	public double calculate(double... params) {
		if (index < 0) return Double.NaN;
		if (index >= values.length) return Double.NaN;
		return values[index];
	}
	public List clone() {
		return this;
	}
}

double[] values = {1, 2, 3, 4, 5};
List l = new List(values);
Function list = new Function("list", l);
Expression e = new Expression("sum(i, 0, 4, list(i) )", list);
mXparser.consolePrintln(e.getExpressionString() + " = " + e.calculate());

Result:
[mXparser-v.4.0.0] sum(i, 0, 4, list(i) ) = 15.0

**Comment by h-code** [comment]
Great for IsNaN !
I will test the proxy method and let you know

**Comment by mariuszgromada** [comment]
Remember to put 0 instead of Double.NaN

```
		if (index < 0) return Double.NaN;
		if (index >= values.length) return Double.NaN;
```

```
		if (index < 0) return 0;
		if (index >= values.length) return 0;
```

**Comment by mariuszgromada** [comment]
And give the star to the repo if you like it :-)

**Comment by mariuszgromada** [comment]
I just committed change for java - it covers NaN, isNAN, [true], [false], coalesce, you can work with expressions like this below:

```
"if( [true] && ([false] || ([false] && [true])) = [false], 1, 0)" = 1
"if( isNaN(3/0) = [true], 1, 0)" = 1
"if( isNaN(3/1) = [false], 1, 0)" = 1
"if( isNaN( [NaN] ) = [true], 1, 0)" = 1
"coalesce( 1, 2, 3 )" = 1
"coalesce( [NaN], 2, 3)" = 2
"coalesce( [NaN], [NaN], 3, 5, 6)" = 3
"coalesce( [NaN], 3/0, [NaN], 5, 6)" = 5
"coalesce( [NaN], 3/0, [NaN], 5/0, 6)" = 6
"if( isNaN( coalesce( [NaN], 3/0, [NaN], 5/0, [NaN]) ) = [true], 1, 0)" = 1
```

:-)

**Comment by h-code** [comment]
Great, Thanks.
I will hopefully have a try this week

**Comment by mariuszgromada** [comment]
Let me know if you need updated jar file :-) Release of 4.1 will have to wait for some other changes as well :-)

**Comment by h-code** [comment]
I downloaded the current branch. IsNan is Ok , but the FunctionExtension class is missing

**Comment by mariuszgromada** [comment]
This is interface you need to implement according to example I gave.

**Comment by h-code** [comment]
It was working with the maven release !

**Comment by mariuszgromada** [comment]
Strange... I have regression tests...

**Comment by mariuszgromada** [comment]
https://github.com/mariuszgromada/MathParser.org-mXparser/blob/master/CURRENT/java/src/org/mariuszgromada/math/mxparser/FunctionExtension.java

**Comment by h-code** [comment]
It's ok sorry. Don't know what happened.
