### ISSUE TITLE
AVG function not working for a series of specific values

### ISSUE THREAD

**Issue by duncanbatchelor** [mariuszgromada/MathParser.org-mXparser#220]
### Problems with evaluating the AVG function
- MathParser.org-mXparser verssion: v.4.4.2
- Framework: .net core

I am evaluating the expression parser and have run into a bit of a problem. I have a need to be able to parse the average or sum etc of a series of numbers such as:

```
            Expression e = new Expression("avg(1, 2, 3, 4, 5, 3)");
            double v = e.calculate();
```
However the above is not working with the latest codebase, 4.4.2.
```
            Expression e = new Expression("avg(i, 1, 5, i)");
            double v = e.calculate();
```
This does work so I can only assume that the default parsing is ignoring the number of types of parameters, or similar.

**Comment by mariuszgromada** [comment]
Hi,

Thanks for your question. Please always check the syntax - mXparser has a built-in help :-)

`mXparser.consolePrintHelp("average");`

**Result**

```
    #  key word            type                    syntax                                        since description
    -  --------            ----                    ------                                        ----- -----------
  195. mean                <Variadic Function>     mean(a1, ..., an)                             2.4   Mean / average value
  218. avg                 <Calculus Operator>     avg( i, from, to, expr , <by> )               2.4   Average operator

```

Use "mean" for a sequence, and "avg" for a function

Best regards

**Comment by mariuszgromada** [comment]
The same for the "sum"

`mXparser.consolePrintHelp("sum");`

**Result**

```
    #  key word            type                    syntax                                        since description
    -  --------            ----                    ------                                        ----- -----------
  193. add                 <Variadic Function>     add(a1, ..., an)                              2.4   Summation operator
  209. sum                 <Calculus Operator>     sum( i, from, to, expr , <by> )               1.0   Summation operator - SIGMA
```

Best regards

**Comment by mariuszgromada** [comment]
Dos this answer your question?

**Comment by duncanbatchelor** [comment]
Yes, that answers it. Thank you. 

I was looking at the code and it did also seem to mention that the avg function accepts an array of doubles which then calculates the average from there. 

https://github.com/mariuszgromada/MathParser.org-mXparser/blob/master/CURRENT/c-sharp/src/org/mariuszgromada/math/mxparser/mathcollection/Statistics.cs

`Line 177    public static double avg(params double[] numbers) {
`
This does provide the correct calculate and I would have expected it to be called as an overloaded function?

But thank you I will use the mean

Kind regards

Duncan
