### ISSUE TITLE
List Operations

### ISSUE THREAD

**Issue by xinnianli** [mariuszgromada/MathParser.org-mXparser#221]
### Issue title:
- List Operations ( Question )

### Issue content:
is it possible to use this parser on list operations? I have been trying to use the expression on each element of a list, for example, list a = a - (x^2 + y) where x, y are variables of type double. The outcome is that each element of the list a will be evaluated by the expression a[element] = a[element] - (x^2 + y).

#### If bug/question:
- MathParser.org-mXparser verssion: v.X.Y.Z
- Framework: java, .net, .net core, .net standard, Xamarin, Android, iOS ... + framework verssion
- Problem description
- Code example

#### If new feature
- Feature description
- Use case description

**Comment by mariuszgromada** [comment]
I think you are referring to recursion - am I right? Tutorial for recursive functions / recursive arguments below:

- http://mathparser.org/mxparser-tutorial/user-defined-recursion-not-limited/
- http://mathparser.org/mxparser-tutorial/fast-limited-user-defined-recursion/

Best regards

**Comment by xinnianli** [comment]
Hi,
Thank you for the quick response. I will look into it.
Xinnian
    On Friday, April 2, 2021, 11:54:30 AM EDT, Mariusz Gromada ***@***.***> wrote:  
 
 


I think you are referring to recursion - am I right? Tutorial for recursive functions / recursive arguments below:
   
   - http://mathparser.org/mxparser-tutorial/user-defined-recursion-not-limited/
   - http://mathparser.org/mxparser-tutorial/fast-limited-user-defined-recursion/

Best regards

**Comment by xinnianli** [comment]
My question is for a simple operation on a list ( on each member of a list ).
A use case, a single value (x) is subtracted from each member of a list {10,11,12,13,...,n};
Pseudo code below,

1. x = 42. list a = {10,11,12,13,...,n};3. Expression exp1 = expression("b = a - x")
4. list b = exp1.calculate()5. list b is {6,7,8,9,...n-4}
Let me know if I am not articulating my request clearly.
Xinnian
    On Friday, April 2, 2021, 11:54:30 AM EDT, Mariusz Gromada ***@***.***> wrote:  
 
 


I think you are referring to recursion - am I right? Tutorial for recursive functions / recursive arguments below:
   
   - http://mathparser.org/mxparser-tutorial/user-defined-recursion-not-limited/
   - http://mathparser.org/mxparser-tutorial/fast-limited-user-defined-recursion/

Best regards

**Comment by mariuszgromada** [comment]
So you want the result as a list? If yes then mXparser will not help. mXparser returns double value. List can be a parameter, but the results is always one number.

**Comment by xinnianli** [comment]
Yes, in this use case, the result is expected to be a list. Thanks for looking into it.
    On Friday, April 2, 2021, 12:40:34 PM EDT, Mariusz Gromada ***@***.***> wrote:  
 
 


So you want the result as a list? If yes then mXparser will not help. mXparser returns double value. List can be a parameter, but the results is always one number.
