### ISSUE TITLE
Why is the 'C' in this formula not considered to be an argument?

### ISSUE THREAD

**Issue by robcoughlan** [mariuszgromada/MathParser.org-mXparser#224]
mXparser v4.4.0
framework .NET 4.7.2

![image](https://user-images.githubusercontent.com/83942643/117618741-abb1b080-b16e-11eb-8034-27e5d26875c7.png)

Is 'C' a reserved symbol inside mXparser?

**Comment by mariuszgromada** [comment]
Yes, there are plenty of reserved keywords. You can change / manipulate this.

http://mathparser.org/mxparser-tutorial/built-in-tokens-key-words-manipulation/

Best regards

**Comment by robcoughlan** [comment]
Hi,

OK thanks.

Regards,

RobC
