### ISSUE TITLE
Arguments allowed names and/or escape characters for arguments with math symbols into name

### ISSUE THREAD

**Issue by dario-ca** [mariuszgromada/MathParser.org-mXparser#226]
Hello, where can I find documentation with the allowed symbols in a name of an argument? I cannot name arguments like this: "**my-input**" because "**-**" is considered a subtraction, but do we have a precise document? thanks

Also, is there any kind of escaping symbol to indicate an argument? something like this:
**[this-is-valid-argument-since-it-is-within-square-brackets] + this-is-a-series-of-subtractions + this_is_correct_since_there_are_no_math_symbols**

we built a formula engine for some production calculations, and I would like the users to freely decide the names of the arguments.

thanks

**Comment by mariuszgromada** [comment]
http://mathparser.org/api/org/mariuszgromada/math/mxparser/Argument.html
http://mathparser.org/api/constant-values.html#org.mariuszgromada.math.mxparser.parsertokens.ParserSymbol.constArgDefStrRegExp
