### ISSUE TITLE
round(1,2)=1 not 1.00

### ISSUE THREAD

**Issue by oneOrNothing** [mariuszgromada/MathParser.org-mXparser#227]
### Issue title:
- round(1,2)=1 not 1.00

#### If bug/question:
- MathParser.org-mXparser verssion: v.4.4.2
- Framework: .net
- Problem description :i want round(1,2)=1.00 not 1, Are there parameters to set ？

**Comment by mariuszgromada** [comment]
Round is a mathematical function, so round from 1 considering 2 digits is still 1. Or maybe I do not understand your question.

**Comment by oneOrNothing** [comment]
thank you very much.
I think that&nbsp; round will keep digital accuracy。
It cannot be omitted even if the end is zero。

For example, if two decimal places are required, then round(1.0005,2) should be 1.00 instead of 1.


Thanks again&nbsp;
From: "Mariusz ***@***.***&gt;
Date: Sat, Jun 19, 2021 02:06 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [mariuszgromada/MathParser.org-mXparser] round(1,2)=1 not 1.00 (#227)




 
Round is a mathematical function, so round from 1 considering 2 digits is still 1. Or maybe I do not understand your question.

**Comment by mariuszgromada** [comment]
I think your are confusing printing format with value. Round function works on value, not on printing format. To print two digits use a proper formatting depending on your framework.
