### ISSUE TITLE
Solve() doesn't find solution for x^2

### ISSUE THREAD

**Issue by ikvych** [mariuszgromada/MathParser.org-mXparser#229]
### Issue title:
- Solve() doesn't find solution for x^2

#### If bug/question:
- MathParser.org-mXparser verssion: v.4.4.0
- Framework: Android
- Solve() doesn't find solution for x^2
- 
-       val zeroOfFunctionExpression = Expression("solve(x^2, -5, 5)")
        val zeroXValue = zeroOfFunctionExpression.calculate()
        zeroXValue == NaN

**Comment by mariuszgromada** [comment]
Hi.
mXparser implements solve method according to Brent's algorithm - API specification is below:

- http://mathparser.org/api/org/mariuszgromada/math/mxparser/mathcollection/Calculus.html#solveBrent(org.mariuszgromada.math.mxparser.Expression,org.mariuszgromada.math.mxparser.Argument,double,double,double,double)
- https://en.wikipedia.org/wiki/Brent%27s_method
- solve( expr, arg, from, to )

Above mean that root can be found only in case where function at the ends of the intervals have different signs. In case of x^2 it has always "+" sign.

Best regards
