### ISSUE TITLE
Multiple solutions for f(x) = 0

### ISSUE THREAD

**Issue by NickyLogan** [mariuszgromada/MathParser.org-mXparser#23]
http://mathparser.org/mxparser-tutorial/solving-equation-fx-0/

In case 3, the code's output shows that the library supports multiple solutions for f(x) = 0

> Case 3: Solve cos(x) = 0 for x in [pi, pi] (root not bracketed)
> <pre>import org.mariuszgromada.math.mxparser.*;
> ...
> Expression e = new Expression("solve( cos(x), x, -pi, pi )");
> mXparser.consolePrintln("Res: " + e.getExpressionString() + " = " + e.calculate() );</pre>
> Output:
> <pre>[mXparser-v.4.0.0] Res: solve( cos(x), x, -pi, pi ) = -1.57079633
> [mXparser-v.4.0.0] Res: solve( cos(x), x, -pi, pi ) = 1.57079633</pre>

However, copying the exact code ***doesn't produce the same output***, i.e. only showing the first solution of cos(x) = 0

> Output:
> <pre>[mXparser-v.4.0.0] Res: solve( cos(x), x, -pi, pi ) = -1.57079633</pre>

So, how to make this work?

P.S. I really love your library!

**Comment by mariuszgromada** [comment]
If root is not bracketed then I apply random sampling to find left limit and right limit where f(left)*f(right) < 0. Do you want to have all possible solutions? If yes - then this is not supported.

And - thanks for your feedback on the lib. Can you say more about tour use case?

**Comment by mariuszgromada** [comment]
Additionally - case 3 was compiled 2 times, the output comes from 2 different sessions.

**Comment by mariuszgromada** [comment]
If you like the lin you can give a star :-)

**Comment by NickyLogan** [comment]
Ah I see, ***THANKS*** for the quick reply. 

Well, I am trying to use this new feature to find all points where the curve of a function f(x) intersects the x-axis for a function plotter I'm making.

By the way, support for solving quadratic and linear equations would be lovely!
e.g. 
> x+x+x-7+8+pi-pi = x+x-x
> x = -1/2
> 
> x^2-x+1+3+1=7
> x = 2 or x = -1

P.S. ⭐️ given! 😃

**Comment by mariuszgromada** [comment]
Are you thinking on computer algebra system that works on symbols?

**Comment by AlexByte** [comment]
You can your own equation solver method using for loop.

**Comment by mariuszgromada** [comment]
@NickyLogan thanks! :-)
