### ISSUE TITLE
how to improve performance for large amount of computation 

### ISSUE THREAD

**Issue by Jp1527** [mariuszgromada/MathParser.org-mXparser#232]
We are using mXparser for some heavy computation in C#. The expressions( there are several hundreds of them) are predefined and for every calculation the argument values are updated. We also defined some customized  3-arg functions and override the cos/sin. It seems the time consumption doubled compared with previous hard-coded formulas defined with lambda expressions. 
We used dottrace to check the performance and seems the checkSyntax is a hot spot. 

Curious if there is any way to maximize the performance?

This is how we call the mXparser
```
public void do_for_each_expression()
        {
            var expString = "((cos(a)*cos(b)-cos(a)*sin(b)*sin(b)))/((a*cos(c)))";
            var args = new List<string>() { "a", "b", "c" };
            var exp = new Expression(expString); 
            mXparser.setToOverrideBuiltinTokens();
            var functionList = new List<Function>() { new Function("cos", new Cos())};
            exp.addFunctions(functionList.ToArray());
            exp.defineArguments(args.ToArray());
            //also add some constants here

            for (int i = 0; i < iterNum; i++)
            {
                //update args value
                var ret = exp.calculate();
            }

        }
```

Best regards

**Comment by Jp1527** [comment]
Thanks for the reply. We checked own code and now reduced expression change. Seems checkSyntax reduces, but still calculate() takes a lot of time.

**Comment by mariuszgromada** [comment]
Try to switch off intelligent rounding - put below code at the begging of your code

```
mXparser.disableAlmostIntRounding();
mXparser.disableCanonicalRounding();
mXparser.disableUlpRounding();
```

http://mathparser.org/api/org/mariuszgromada/math/mxparser/mXparser.html#disableAlmostIntRounding()
http://mathparser.org/api/org/mariuszgromada/math/mxparser/mXparser.html#disableCanonicalRounding()
http://mathparser.org/api/org/mariuszgromada/math/mxparser/mXparser.html#disableUlpRounding()

Best regards

**Comment by mariuszgromada** [comment]
Was the hint helpful?
