### ISSUE TITLE
Incorrect value of arcctg

### ISSUE THREAD

**Issue by loggie0** [mariuszgromada/MathParser.org-mXparser#233]
Upgrading from 4.3.3 to 4.4.2 results in an incorrect value of the following expression:
arcctg(-10)

In 4.3.3 the value was -0.099668652491162
In 4.4.2 the valus is 3.04192400109863

**Comment by mariuszgromada** [comment]
Are you using java or .net version?

**Comment by loggie0** [comment]
.NET

**Comment by mariuszgromada** [comment]
Please share your code and details of the framework (.net core?).

**Comment by loggie0** [comment]
It's .NET Framework 4.8

The code:
var expression = new Expression("arcctg(-10)");
var result = expression.calculate();

Both MathParser versions pulled straight from NuGet and installed for an empty .NET Framework Console project.

**Comment by mariuszgromada** [comment]
Strange, I have executed the code using the .NET 4.8

**The code:**
```
Expression e = new Expression("arcctg(-10)");
mXparser.consolePrintln(e.calculate());
```

**Below is my result:**
```
[mXparser-v.4.4.2 bin .NET 4.8] 3.04192400109863
[mXparser-v.4.4.2 bin .NET 4.8] Press any key to continue . . .
```

**Can you please run below code and share the ruslt?**
```
Expression e = new Expression("arcctg(-10)");
mXparser.consolePrintln(e.calculate());
mXparser.consolePrintln(mXparser.VERSION);
mXparser.consolePrintln(mXparser.BUIT_FOR);

```

Best regards

**Comment by mariuszgromada** [comment]
@loggie0 - did you have a chance to run the code I provided above? Thanks!

**Comment by mariuszgromada** [comment]
Great article that explains this issue well. There are two alternative versions of the inverse cotangent function. The first "reflecting" domain from 0 to pi - gives a continuous inverted function, and the second "reflecting" domain from -pi / 2 to pi / 2 - gives an inverse function, which is not continuous. The first version is a widely accepted standard.

![image](https://user-images.githubusercontent.com/16277367/159116781-31e7c993-8ca7-4e17-ad63-8c908f2a5dea.png)
![image](https://user-images.githubusercontent.com/16277367/159116786-0b5a9ac7-5471-4848-a373-59a9a2ef9fb8.png)

- https://www.intmath.com/blog/mathematics/which-is-the-correct-graph-of-arccot-x-6009
- https://en.wikipedia.org/wiki/Inverse_trigonometric_functions

I replicated the below chart that from Wikipedia

- https://en.wikipedia.org/wiki/Inverse_trigonometric_functions#/media/File:Arctangent_Arccotangent.svg

![image](https://user-images.githubusercontent.com/16277367/159116514-a912bfc4-3719-4efc-972e-2d52065be109.png)

code to generate the data

- C#

```C#
Argument x = new Argument("x");
Expression arcctg = new Expression("arcctg(x)", x);
Expression arctg = new Expression("arctg(x)", x);
Console.WriteLine("x" + "\t" + "arcctg(x)" + "\t" + "arctg(x)");
for (double xx = -12; xx <= 12; xx += 0.2)
{
	xx = MathFunctions.round(xx, 10);
	x.setArgumentValue(xx);
	Console.WriteLine(xx + "\t" + arcctg.calculate() + "\t" + arctg.calculate());
}

```

- JAVA

```java
Argument x = new Argument("x");
Expression arcctg = new Expression("arcctg(x)", x);
Expression arctg = new Expression("arctg(x)", x);
System.out.println("x" + "\t" + "arcctg(x)" + "\t" + "arctg(x)");
for (double xx = -12; xx <= 12; xx+=0.2) {
	xx = MathFunctions.round(xx, 10);
	x.setArgumentValue(xx);
	System.out.println(xx + "\t" + arcctg.calculate() + "\t" + arctg.calculate());
}

```

![image](https://user-images.githubusercontent.com/16277367/159116530-e8fa89df-a607-49b7-841a-d4e9a53ced14.png)

![image](https://user-images.githubusercontent.com/16277367/159116546-ec00a054-ee1c-4ba9-8acb-5c013821ea8d.png)
