### ISSUE TITLE
Plan to upgrade the .Net framework to newer version V4.8

### ISSUE THREAD

**Issue by dava2788** [mariuszgromada/MathParser.org-mXparser#234]
### Issue title:
Plan to upgrade the .Net framework to newer version V4.8

#### If bug/question:
- MathParser.org-mXparser Version 4.4.2
- Framework: .net standard
Work with newer .net Frameworks
Currently the Dll is build under the .net Framework 4.5
- Code example

**Comment by mariuszgromada** [comment]
Thanks, I will do it soon in the next release.

**Comment by mariuszgromada** [comment]
Soon will be done, *.nuspec is already prepared. I am very close to release mXparser v.5.0
https://github.com/mariuszgromada/MathParser.org-mXparser/blob/master/CURRENT/c-sharp/mXparser.nuspec

Best regards

**Comment by mariuszgromada** [comment]
Done, check the latest Nuget package
