### ISSUE TITLE
calculate error on floor(1.2/0.1)

### ISSUE THREAD

**Issue by fanzf-git** [mariuszgromada/MathParser.org-mXparser#235]
### Issue title:
function div return error when dealing floor(1.2/0.1) return 11 instead of 12
#### question:
- MathParser.org-mXparser verssion: v.4.4.2
- Framework: .net, 
- Problem description: function div return error when dealing floor(1.2/0.1)
- Code example

 MathFunctions.div

**Comment by mariuszgromada** [comment]
mXparser follows .NET framework implementation - please check below code

```
double v = Math.Floor(1.2 / 0.1);
Console.WriteLine(v);
```

Best regards
