### ISSUE TITLE
Use of power()

### ISSUE THREAD

**Issue by gmseed** [mariuszgromada/MathParser.org-mXparser#237]
Hi

I couldn't see a forum for posting such questions, so apologies if this is the wrong place.

For the following code:

Argument ch1 = new Argument("ch1");
ch1.setArgumentValue(Math.PI/2);
Expression e1 = new Expression("sin(ch1)", ch1);
System.out.println(e1.getExpressionString() + " = " + e1.calculate());

Argument ch2 = new Argument("ch2");
ch2.setArgumentValue(2);
Expression e2 = new Expression("power(ch2,2)", ch2);
System.out.println(e2.getExpressionString() + " = " + e2.calculate());

why is the output:

sin(ch1) = 1.0
power(ch2,2) = NaN

and not:

sin(ch1) = 1.0
power(ch2,2) = 4

**Comment by mariuszgromada** [comment]
Pleas add this line of code
`System.out.println(e2.getErrorMessage());`

Then the results is:
```
[power(ch2,2)] checking ...
[power(ch2,2)] (power, 0) invalid <TOKEN>.
[power(ch2,2)] errors were found.
Problem with expression syntax
```

Simply "power" is not a pre-defined function in mXparser - exponentiation is done via "^" operator
`Expression e2 = new Expression("ch2^2", ch2);`

In case you would like to read more on keywords defined in mXparser just use built-in help
```
mXparser.consolePrintHelp();
mXparser.consolePrintHelp("expon");
```

**Comment by gmseed** [comment]
Thanks for your reply.

I first tried the standard named function pow() and when I got a NaN value and then looked up the documentation, and when I saw power() listed I assumed it was an error and why I posted my comment:

http://mathparser.org/api/org/mariuszgromada/math/mxparser/mathcollection/MathFunctions.html

But thanks for the tip of expression..getErrorMessage(), which looks really useful.

BTW. I was surprised not to find a clamp(val,min,max) function listed. In what I do, I use it extensively and so added it as a user-defined function.

**Comment by mariuszgromada** [comment]
Thanks. I will add "clamp" function. In case of need to debug you can also use verbose mode, example below:

```
Argument ch1 = new Argument("ch1");
ch1.setVerboseMode();
ch1.setArgumentValue(Math.PI/2);
Expression e1 = new Expression("sin(ch1)", ch1);
e1.setVerboseMode();
System.out.println(e1.getExpressionString() + " = " + e1.calculate());

Argument ch2 = new Argument("ch2");
ch2.setVerboseMode();
ch2.setArgumentValue(2);
Expression e2 = new Expression("power(ch2,2)", ch2);
e2.setVerboseMode();
System.out.println(e2.getExpressionString() + " = " + e2.calculate());
```

Best regards
