### ISSUE TITLE
Implementation of cumulative distribution function and the quantile function  of the t, F and chi-squared distributions.

### ISSUE THREAD

**Issue by jesusmmp** [mariuszgromada/MathParser.org-mXparser#238]
### Issue title:
- Implementation of cumulative distribution function and the quantile function (inverse cumulative distribution function) of the t, F and chi-squared distributions.

### Issue content:
Using acumulative distribution function and the quantile function (inverse cumulative distribution function) of the t, F and chi-squared distributions. These are the distributions related to the normal distribution and are important in statistical inference.

#### If bug/question:
- MathParser.org-mXparser verssion: v.4.4.2
- Framework: java

**Comment by mariuszgromada** [comment]
Thanks, in the next release I will try to include this.

**Comment by jesusmmp** [comment]
Great news @mariuszgromada! 
When the next version is planned to be released?

Thanks for all your work!

**Comment by mariuszgromada** [comment]
I am working on this now :-)

**Comment by mariuszgromada** [comment]
- `rFSned(d1, d2)` - Random variable - Snedecor's F distribution (F-distribution or F-ratio, also known as Fisher–Snedecor distribution)
- `pFSned(x, d1, d2)` - Probability distribution function - Snedecor's F distribution (F-distribution or F-ratio, also known as Fisher–Snedecor distribution)
- `cFSned(x, d1, d2)` - Cumulative distribution function - Snedecor's F distribution (F-distribution or F-ratio, also known as Fisher–Snedecor distribution)
- `qFSned(p, d1, d2)` - Quantile function (inverse cumulative distribution function) - Snedecor's F distribution (F-distribution or F-ratio, also known as Fisher–Snedecor distribution)

@jesusmmp done :-) Soon will be released in v.5.1

Enjoy :-)

**Comment by jesusmmp** [comment]
Great news!
Thanks @mariuszgromada! :)

**Comment by mariuszgromada** [comment]
@jesusmmp please let me know in case you have other needs related to the Sakai, I will be happy to support :-)

**Comment by mariuszgromada** [comment]
@jesusmmp v.5.1.0 has just been released :-)
