### ISSUE TITLE
Modify / Remove parser key words (tokens)

### ISSUE THREAD

**Issue by mariuszgromada** [mariuszgromada/MathParser.org-mXparser#24]
Enhancement requested by Saboureau vis email.

API extension to be able to:

- Modify existing tokens strings (i.e. Li(x) is a function, Saboureau has a need to use "Li" keyword as user defined argument)
- Remove given tokens to limit mXparser functionality

This will be added :-)

**Comment by LitteralSab** [comment]
Thank you.

**Comment by mariuszgromada** [comment]
Will be added in mXparser-v.4.1

**Comment by mariuszgromada** [comment]
Done :-)

**Comment by mariuszgromada** [comment]
JAVA:
mXparser.modifyBuiltinToken(String currentToken, String newToken)
mXparser.modifyBuiltinToken(String currentToken, String newToken, String newTokenDescription)
mXparser.unmodifyBuiltinTokens(String... currentOrNewTokens)
mXparser.unmodifyAllBuiltinTokens()
mXparser.getBuiltinTokensToModify()

mXparser.removeBuiltinTokens(String... tokens)
mXparser.unremoveBuiltinTokens(String... tokens)
mXparser.unremoveAllBuiltinTokens()
mXparser.getBuiltinTokensToRemove()

.NET:
mXparser.modifyBuiltinToken(String currentToken, String newToken)
mXparser.modifyBuiltinToken(String currentToken, String newToken, String newTokenDescription)
mXparser.unmodifyBuiltinTokens(params String[] currentOrNewTokens)
mXparser.unmodifyAllBuiltinTokens()
mXparser.getBuiltinTokensToModify()

mXparser.removeBuiltinTokens(params String[] tokens)
mXparser.unremoveBuiltinTokens(params String[] tokens)
mXparser.unremoveAllBuiltinTokens()
mXparser.getBuiltinTokensToRemove()
