### ISSUE TITLE
The result of 5^-25 is 0 while the real result is about 3.3554432e-18

### ISSUE THREAD

**Issue by NoaLeGeek68** [mariuszgromada/MathParser.org-mXparser#240]
Version : MathParser.org-mXparser verssion: v.4.4.2

Using : Java (Intellij Idea)

When I do !calc 5^-25 (!calc is the command that i use on Discord, there is no problem with that because it return always the result of the calculation), it return me 0.0 while the real result is about 3.3554432e-18.
It return the good result when I do 5^-20 but it return me 0 when I do 5^-21. And if we go higher than 21, it return always 0.
I don't know why it does that, is this a bug, is this normal?

Code example : System.out.println(new Expression("5^-25").calculate());

**Comment by mariuszgromada** [comment]
Solution is here - you have to switch off some intelligent rounding options
```
mXparser.disableAlmostIntRounding();
mXparser.disableCanonicalRounding();
mXparser.disableUlpRounding();
System.out.println(new Expression("5^-25").calculate());
```
Best regards

**Comment by NoaLeGeek68** [comment]
Thanks!
