### ISSUE TITLE
incorrect addition result

### ISSUE THREAD

**Issue by AlexByte** [mariuszgromada/MathParser.org-mXparser#242]
### Issue title:
- 10000000000000000+1 = 10000000000000000

### Issue content:
when added to a large number, the result is incorrect

#### If bug/question:
- MathParser.org-mXparser verssion: v.4.4.2
- Framework: .NET 5
- Problem description 
- Code example

`new Expression("10000000000000000+1").calculate().ToString()
`

**Comment by mariuszgromada** [comment]
Hi. The same result you will receive using the .net framework. Run below code and check the value of c.

double a = 10000000000000000.0;
double b = 1.0;
double c = a + b;

mXparser is fully based on double type.

Best regards

**Comment by AlexByte** [comment]
But in .net framework it displays as [1E+16](https://dotnetfiddle.net/aqa5H2)

**Comment by AlexByte** [comment]
.net 5 [now ](https://github.com/dotnet/runtime/issues/29157)uses [G17](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-numeric-format-strings) format for double instead of the default G15 in Double.ToString (). To do it as before, you need to use `.ToString ("G15")`
