### ISSUE TITLE
Getting token list of function arguments within FunctionExtention.

### ISSUE THREAD

**Issue by laurent-menten** [mariuszgromada/MathParser.org-mXparser#245]
Hi Mariusz.

First, mXparser is great, thanks for your work.

For one of my projects, I need to have functions working as a getter for java objects like the expression "size( myObject )" resulting in a call to myObject.size(). I have seen many people asking to be able to work with other data types in mXparser and I understand it may be a huge change to support calling objects methods directly from the expression so my idea is this one:

We need a new type of constant that simply maps a name to an arbitrary object and a new interface like FunctionExtention or FunctionExtentionVariadic where calculate would receive objects, either from the map or a Double if the argument was directly computable. I believe with this mXparser would support virtually any data type without having to know about it, the user code being responsible for the job of checking types etc.

Do you think it would be an interesting improvement, would you agree to add it?
Best regards
Laurent.

**Comment by laurent-menten** [comment]
FYI: As I was trying to find a workaround, I came to some kind of (temporary) solution:

https://github.com/laurent-menten/SeamstressPatternStudio/tree/master/src/be/lmenten/sps/math/mXparser

**Comment by mariuszgromada** [comment]
I believe mXparser already support your need via ArgumentExtension Interface
https://github.com/mariuszgromada/MathParser.org-mXparser/blob/master/CURRENT/java/src/org/mariuszgromada/math/mxparser/ArgumentExtension.java
http://mathparser.org/api/org/mariuszgromada/math/mxparser/ArgumentExtension.html

It works similarly to function extension, take a look on example

Argument x = new Argument("x", new PiMultArgExt());
Expression e = new Expression("x + x + x + x", x);

class PiMultArgExt implements ArgumentExtension {
   private int multiple = 0;
     public double getArgumentValue() {
          multiple++;
        return  MathConstants.PI * multiple;
     }
     public PiMultArgExt clone() {
        return new PiMultArgExt();
     }
}

Best regards



pt., 21 sty 2022 o 01:00 Laurent MENTEN ***@***.***>
napisał(a):

**Comment by laurent-menten** [comment]
Not exactly, my project is a parametric drawing program for drawing sewing patterns. Let's say I have several arbitrary objects representing lines all with a name, a length and an angle relative to horizontal, what I need is users being able to enter expressions containing things like "length( myLine1 )" or "angle( myLine1, myLine2 )".
As of now, we are bound to define several constants for each line like myLine1_length, myLine1_angle etc. which I find is totally unelegant! Using ArgumentExtension is not really different from doing that.

Best regards.
