### ISSUE TITLE
Dynamic invocation of objects methods

### ISSUE THREAD

**Issue by laurent-menten** [mariuszgromada/MathParser.org-mXparser#246]
I managed to extend mXparser to make it calculate expressions like `length( myline )` as an invocation of a method length() in an arbitrary object with argument(s) derived from the token in the expression. Of course, it is still at an early stage but it works pretty well and I think it is quite usable already. 

You can check my code there:
https://github.com/laurent-menten/Dynamic-mXparser-java

Its support requires ridiculously minor changes in the original Expression class and they are not altering the logic at all (I only added about 4 lines and changed a method from package private to protected, really!). I would be quite proud if you agree to check my idea and maybe merge the little changes I need to avoid having to distribute a modified version of your code with mine.

Best regards.

**Comment by mariuszgromada** [comment]
Thanks!

Can share here example of the code that uses mentioned functionality? Currently I am working strongly on mXparser 5.0 so it is good moment to add nice features, but I still struggle to understand fully your use case (I simply did not have time to analyze the implementation and simple example with the results would be awesome).

Best regards

**Comment by mariuszgromada** [comment]
Ok, I think I see the point. There is one significant problem - whjat will happen in the below case?

`DynamicExpression e = new DynamicExpression( "day( now + later )" );`

Best regards

**Comment by laurent-menten** [comment]
It is not what my extension is meant for. The expression `day( now )` will return the day number of the current day of a date stored in an object identified by the name 'now' to the DynamicExpression instance, i.e. 24.0 for today. It is to be used to produce a result from one or more objects. It is not the idea to make the calculation directly on objects.

To answer your question, you would rather write `day( now ) + day( later )` if it is what you want. As of now, `day( now + later )` is a syntax error, you can't have expression between the parenthesis, only Constant, Argument or my so-called NamedObject. The implementation of method `day()` is a method that receives a LocalDate object and returns a double (yet I may have a solution for that using level). Of course, you can write a function like `double day( LocalDate, LocalDate )`, that would internally extract the day number from both objects then return the sum as a double and use it in the expression `day( now, later )`. What the function really does is up to the user.

Internaly, I hooked right after the expression is tokenized and look through the list of tokens for NO_MATCHED "function" looksLike token then I try to build an array of objects (or Double if I find a Constant or an Argument) then invoke the method with the same name and signature. If this works without error, I patch the token list to replace the not matched token and its parameters with a number, otherwise, I just leave it as it is. Then mXparser does the rest of its job never knowing what happened to the token list.

The big difference with the usual user-defined function in mXparser is that they can manipulate things other than doubles but they do return double anyway. You write the function, add your bunch of NamedObject and that's it. What I wrote is the ability to extract data directly from objects rather than defining a constant for each and every data from each and every object. 

As I mentioned before, I am developing a parametric pattern drawing software (similar to Valentina if you heard of it). Every parameter of every point, line or curve is defined relative to other elements. Let's say I have an object representing a line known as the waistline [_conceptualy a line constraint to include the origin point A and at angle 0 from horizontal_], on this line I have a segment AB [_conceptualy a segment of line constraint to be on the line know as the waistline, with a starting point being point A and a length defined by the expression `waisline_measurement / 4`] that represents the waistline on the front piece of garment pattern and I want to define the point C [_conceptualy a point constraint to a be on segment AB and at a distance from A_] where a dart will be located, I may write an expression like `length( AB ) * 3/5` in the distanceExpression field of this point object. Of course, expressions are often much more complex, making calculations from several measurements etc.

I am not sure I made it clearer. I hope so!
Best regards

**Comment by mariuszgromada** [comment]
Thanks! This is certainly very interesting idea. I assume we need to add this directly to the Expression class as via inheritance we create a separate parser in fact. Then we need to really o well syntax checking etc.

I have just finished adding implied multiplication and soon I can think about it.

Would you be interested to co-create this with me? We will need a decent number of test scenarios etc.

Best regards

**Comment by mariuszgromada** [comment]
Dear Laurent,

Please let me know if you are still interested in adding this functionality to mXparser.

Best regards
