### ISSUE TITLE
Missing functions

### ISSUE THREAD

**Issue by NickyLogan** [mariuszgromada/MathParser.org-mXparser#25]
Hi, I was looking through all the available unary functions at http://mathparser.org/mxparser-math-collection/unary-functions/

I found that the inverse of the trigonometric secant and cosecant are missing, while the acot(x) exists.
Do you consider fixing this? Thanks

**Comment by mariuszgromada** [comment]
Hi,

Thanks for your request. Currently you can use formula such as sec^-1(x) = cos^-1( 1/x ), but you are right - I will add it directly to the math collection.

Best regards

**Comment by mariuszgromada** [comment]
done :-)

arcsec(x)
arccsc(x)
