### ISSUE TITLE
MOON_SEMI_MAJOR_AXIS Is Misspelt as MONN_SEMI_MAJOR_AXIS

### ISSUE THREAD

**Issue by Brittank88** [mariuszgromada/MathParser.org-mXparser#252]
- mXparser: `org.mariuszgromada.math:MathParser.org-mXparser:4.4.2`
- Framework: `OpenJDK Runtime Environment Temurin-17.0.1+12 (build 17.0.1+12)`

See:
![image](https://user-images.githubusercontent.com/24266948/155443200-f9db23a4-d12b-4784-b7a7-52db313a2fc1.png)

(I'm using this library in the development of a Minecraft chat-based calculation mod, hence the way the screenshot looks!)

_P.S. The issue template misspells "version" as "verssion" - just thought I'd let you know!_

_P.P.S I just want to say that this library is so cool, I truly love it!_

**Comment by mariuszgromada** [comment]
Thanks -  I will "fix" it :-)

**Comment by mariuszgromada** [comment]
Done
