### ISSUE TITLE
A Question

### ISSUE THREAD

**Issue by gmseed** [mariuszgromada/MathParser.org-mXparser#255]
Hi
This isn't really an issue but a question. I've used mXParser in Java code as detailed in the API and examples but curious if it supports the passing of a script file. So, we'd have a file containing several expressions, functions, user-defined functiins etc, pass it to an mXParser function, it reads the mathematical expressions line by line, does the calcs and places the result in an object.
Thanks
Graham

**Comment by mariuszgromada** [comment]
Script files are supported in the Scalar Calculator that is powered by mXparser. I am thinking of releasing a similar version of the scripting engine for .net and jdk.

https://scalarmath.org/
