### ISSUE TITLE
How do I switch angle / radian mode for trigonometric functions?

### ISSUE THREAD

**Issue by peterhoucll** [mariuszgromada/MathParser.org-mXparser#26]
default seems to be the radian mode, can switch to the angle mode?
the calculation results of the trigonometric functions are different  in the two modes.

such as:
angle mode:
sin(1) = 0.017452406437

radian mode:
sin(1) = 0.841470984808

**Comment by mariuszgromada** [comment]
You can use units functionality

sin( 1*[deg] ) = 0.017452406437283515
sin( 1*[rad] ) = 0.8414709848078965

**Comment by peterhoucll** [comment]
thank you very much!

**Comment by mariuszgromada** [comment]
Additionally you have the option to use built-in functions:

deg(x) - Radians to degrees
rad(x) - Degrees to radians

**Comment by mariuszgromada** [comment]
If you like :-) pls give a star to the repo :-)

**Comment by peterhoucll** [comment]
Ok. I have given a star :)

**Comment by mariuszgromada** [comment]
Thanks :-)

**Comment by mariuszgromada** [comment]
So - I am closing this issue :-)

**Comment by peterhoucll** [comment]
ok

**Comment by mariuszgromada** [comment]
Follow mXparser tutorial: http://mathparser.org/mxparser-tutorial/

**Comment by peterhoucll** [comment]
I have read the tutorial, but I did not find the results.

**Comment by mariuszgromada** [comment]
Yes, you are right. Tutorial does not cover all the functionality. Additionally you can read math colelction: http://mathparser.org/mxparser-math-collection/ especially units section http://mathparser.org/mxparser-math-collection/units/

**Comment by peterhoucll** [comment]
thank you.
