### ISSUE TITLE
BellNumber java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by SyrasX** [mariuszgromada/MathParser.org-mXparser#262]
MathParser.org-mXparser version: v.5.0.5
Framework: java

A big value n for the BellNumber Bell(n) leads to  an OutOfMemoryError.

```
public class Tester {

    public static void callApi(String input){
  
      Expression e = new Expression(input);
      e.setVerboseMode();
      if(e.checkSyntax()){
        e.calculate();
      }
    }
  
    public static void main(String[] args){

        callApi("Bell(999999*9999999)");
    }
}
```
Log:

[mXparser-v.5.0.5]
[][Bell(999999*9999999)]
[][Bell(999999*9999999)] Starting ...
[][Bell(999999*9999999)] Starting calculation loop
[][Bell(999999*9999999)] Parsing (1, 5)  ---> ( 999999.0 * 9999999.0 )  ...  ---> Bell ( 9.999989000001E12 )  ...  done
[][Bell(999999*9999999)] Parsing (1, 3)  ---> ( 9.999989000001E12 )  ...  ---> Bell 9.999989000001E12  ...  done
[][Bell(999999*9999999)] Parsing (0, 1)  ---> Bell 9.999989000001E12  ... Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at org.mariuszgromada.math.mxparser.mathcollection.MathFunctions.bellNumber(MathFunctions.java:300)
        at org.mariuszgromada.math.mxparser.mathcollection.MathFunctions.bellNumber(MathFunctions.java:328)
        at org.mariuszgromada.math.mxparser.Expression.BELL_NUMBER(Expression.java:3558)
        at org.mariuszgromada.math.mxparser.Expression.f1ArgCalc(Expression.java:6373)
        at org.mariuszgromada.math.mxparser.Expression.calculate(Expression.java:6179)
        at org.mariuszgromada.math.mxparser.Expression.calculate(Expression.java:5666)
        at Tester.callApi(Tester.java:11)
        at Tester.main(Tester.java:17)

I tried other java algorithms found on the web but they also had the same result. So probably should just catch the Exception.

**Comment by mariuszgromada** [comment]
:-) Thanks!

**Comment by mariuszgromada** [comment]
Depending on the system configuration - OutOfMemoryError can happen everywhere ... So I will try to catch it at the very beginning, not just to handle bell number.

I will deal with tomorrow :-)

**Comment by SyrasX** [comment]
That is true. Until now I did not find other functions where a short and fast input is enough to run into a OutOfMemoryError, but it would be better to catch it on a broader scale.

**Comment by mariuszgromada** [comment]
Should work now :-)

**Comment by mariuszgromada** [comment]
Can you contact me on email info@mathparser.org? I want to thank you for your contribution :-)
