### ISSUE TITLE
StackOverflow in recursive functions possible

### ISSUE THREAD

**Issue by SyrasX** [mariuszgromada/MathParser.org-mXparser#263]
MathParser.org-mXparser verssion: v.5.0.5
Framework: java

Functions such as:
- org.mariuszgromada.math.mxparser.mathcollection.MathFunctions#eulerNumber(int, int)
- org.mariuszgromada.math.mxparser.mathcollection.MathFunctions#lucasNumber(int)
- org.mariuszgromada.math.mxparser.mathcollection.MathFunctions#fibonacciNumber(int)
- and more

Have no max recursion depth and easily can lead to a Stackoverflow.
There seems to be a recursion counter set by org.mariuszgromada.math.mxparser.mXparser#setMaxAllowedRecursionDepth() which is only used for user defined Arguments. It needs to either be expanded to include these functions, or they just need to catch the exception.

**Comment by mariuszgromada** [comment]
Thanks. Yes! I will fix this today :-)

**Comment by mariuszgromada** [comment]
`mXparser.setMaxAllowedRecursionDepth()` already works on MathCollection
