### ISSUE TITLE
CheckSyntax () does not become false even if it ends with an operator

### ISSUE THREAD

**Issue by takiru** [mariuszgromada/MathParser.org-mXparser#264]
### Issue title:
- CheckSyntax () does not become false even if it ends with an operator

### Issue content:
```C#
var expression = new Expression("(width*height+(width-height)/2) * 2+10.56+");
var parameters = new List<Argument>()
{
    new Argument("width", 10),
    new Argument("height", 3)
};
expression.addArguments(parameters.ToArray());
if (!expression.checkSyntax())
{
    MessageBox.Show("error");
    return;
}
```

"(width * height + (width-height) / 2) * 2 + 10.56-" does not become false.
"(width * height + (width-height) / 2) * 2 + 10.56 *" and "(width * height + (width-height) / 2) * 2 + 10.56/" are false.

#### If bug/question:
- MathParser.org-mXparser verssion: v.5.0.6
- Framework: .NET Framework 4.8
- Problem description
- Code example

#### If new feature
- Feature description
- Use case description

**Comment by mariuszgromada** [comment]
Thanks. This is a [**feature**](https://github.com/mariuszgromada/MathParser.org-mXparser/issues/254), not a bug. In this case check syntax method will recognize lexical error on in the case when below option will be applied:

1. Before `Expression` object is created - global option - `mXparser.disableAttemptToFixExpStrMode()`
2. After `Expression e` object is created - local option - `e.disableAttemptToFixExpStrMode()`

- [**disableAttemptToFixExpStrMode**](https://mathparser.org/api/org/mariuszgromada/math/mxparser/Expression.html#disableAttemptToFixExpStrMode())
- [**enableAttemptToFixExpStrMode**](https://mathparser.org/api/org/mariuszgromada/math/mxparser/Expression.html#enableAttemptToFixExpStrMode())
- [**checkIfAttemptToFixExpStrMode**](https://mathparser.org/api/org/mariuszgromada/math/mxparser/Expression.html#checkIfAttemptToFixExpStrMode())
- [**getCanonicalExpressionString**](https://mathparser.org/api/org/mariuszgromada/math/mxparser/Expression.html#getCanonicalExpressionString())

Please let me know if this answers your question.

Best regards

**Comment by takiru** [comment]
e.disableAttemptToFixExpStrMode () did what I wanted!
Thank you.

**Comment by mariuszgromada** [comment]
Dedicated tutorial section addedInspecting calculation process ->
Case 5: An Attempt To Fix Expression String
https://mathparser.org/mxparser-tutorial/inspecting-calculation-process/

Best regards
