### ISSUE TITLE
Licensing Clarifications

### ISSUE THREAD

**Issue by Eddie-Hartman** [mariuszgromada/MathParser.org-mXparser#267]
Just looking to clarify on licensing.

We were using a 4.X version to develop a product that is unreleased. During development, it was noted that 5.X of mXparser was released. Previously, mXparser was licensed under a Simplified BSD License: https://github.com/mariuszgromada/MathParser.org-mXparser/blob/65928d1674cf9f80370fb6243ef6ada8164a899b/LICENSE.txt

Now there is a license for commercial use.  We were using mXparser 4.4.2, but that has been removed from NuGet. I can see a 4.4.3 version on NuGet, but do not see it as a release version in GitHub. What was changed in this release?
Update: I see from the NuGet page that the license was updated, so the free versions were removed. I'm guessing 4.4.3 is just 4.4.2 but with an updated license.

In addition, I believe you should make it more clear that the licensing has changed. Simply updating a version in NuGet would make someone break the license if they are developing a commercial product (I believe at least. I am not a lawyer). It took a bit of digging around to see what was new in the 5.X versions to realize that there is now a commercial licensing fee.

**Comment by mariuszgromada** [comment]
Thanks for your question. All the information on license change are clearly stated on the Nuget page README. There is more than just the license change.
- https://www.nuget.org/packages/MathParser.org-mXparser/4.4.3

![image](https://user-images.githubusercontent.com/16277367/179249911-6b585deb-f9bc-4e2f-9b11-f3c6fe4679cf.png)

I did not just update the package, information on changes is in the package readme.txt and also in the README on Nuget.

Best regards
