### ISSUE TITLE
Add integer division operator

### ISSUE THREAD

**Issue by gx56q** [mariuszgromada/MathParser.org-mXparser#285]
- We all need integer division operator

**Comment by mariuszgromada** [comment]
Ok, this will be easy :-) I will do that soon.

As of now you can do it like that:
```
Expression e = new Expression("floor(13/7)");
mXparser.consolePrintln(e.calculate());
```

Result:
`[mXparser-v.5.1.1] 1.0`

**Comment by mariuszgromada** [comment]
Done, example "\\" backslash as integer division operator
`"7\3"` = 2
