### ISSUE TITLE
Custom token for user defined binary functions

### ISSUE THREAD

**Issue by sadellie** [mariuszgromada/MathParser.org-mXparser#300]
I have defined a binary function:

```kotlin
val f: Function = Function("f", "a/b*1234", "a", "b")
```

I want to use it like:
```kotlin
val e: Expression = Expression("12f3 ", f)
```

Is it even possible in mXparser? I couldn't find it in the docs.

**Comment by mariuszgromada** [comment]
Hi,

User token name (function name, constant name, argument name) can not start with a digit, so 12f3 is not allowed here. Additionally please pay attention to default mode of implied multiplication as 12f3 might recognized as 12*f3.

Best regards
