### ISSUE TITLE
getMissingUserDefinedArguments() not working correctly with tokens containing a period when disabling implied Multiplication

### ISSUE THREAD

**Issue by matthis-ostfalia** [mariuszgromada/MathParser.org-mXparser#312]
Hello, this is my first ever Issue, so please be gentle. 
If I missed something or if I am using the Methods wrongly, please feel free to close this issue and tell me how.

I am running this code:
 

        Expression ex = new Expression(this.baseFormula);
        ex.disableImpliedMultiplicationMode();
        mXparser.removeBuiltinTokens(".");

        ex.checkSyntax();
        System.out.println(ex.getErrorMessage());
        System.out.println(Arrays.toString(ex.getMissingUserDefinedArguments()));`

which then leads to this console Output:

`
[if((Testat1.1 + Testat1.2 + Testat1.3 + Testat1.4) > 50, Klausur, -100)]: Starting syntax check...` 
`
[if((Testat1.1 + Testat1.2 + Testat1.3 + Testat1.4) > 50, Klausur, -100)]: Token 'Testat1.1', index 4: Invalid token. Possibly missing multiplication operator - try implied multiplication mode. `
`
[if((Testat1.1 + Testat1.2 + Testat1.3 + Testat1.4) > 50, Klausur, -100)]: Token 'Testat1.2', index 6: Invalid token. Possibly missing multiplication operator - try implied multiplication mode. `
`
[if((Testat1.1 + Testat1.2 + Testat1.3 + Testat1.4) > 50, Klausur, -100)]: Token 'Testat1.3', index 8: Invalid token. Possibly missing multiplication operator - try implied multiplication mode. `
`
[if((Testat1.1 + Testat1.2 + Testat1.3 + Testat1.4) > 50, Klausur, -100)]: Token 'Testat1.4', index 10: Invalid token. Possibly missing multiplication operator - try implied multiplication mode. `
`
[if((Testat1.1 + Testat1.2 + Testat1.3 + Testat1.4) > 50, Klausur, -100)]: Token 'Klausur', index 15: Invalid token.
[if((Testat1.1 + Testat1.2 + Testat1.3 + Testat1.4) > 50, Klausur, -100)]: Errors have been found.
`
`
[Klausur]
`

I hope it's clear to see. The "Testat" arguments are recognized as tokens, but are not returned in the list of missing user defined Arguments. In my project I use this list to add the missing values/arguments to the formula as constants. 

I have tried it with and without the removeBuiltinTokens(".") method call, but that makes no difference. 

Apart from not using tokens with built in periods I have not found a way around this.

**Comment by mariuszgromada** [comment]
Hi,

Thank you for your message. Variable names accepted by mxparser can not contain dot '.'

For 'Testat1.1' the parser recognizes the problem saying the token is invalid. Additionally the parser gives the advice that the token could be possibly interpreted as implied multiplication when implied multiplication mode is on, then Testat1.1 = Test1 x .1 = Test1 x 0.1

Simply instead of dot '.'  use underscore '_'

Best regards

**Comment by matthis-ostfalia** [comment]
Thank you a lot for quick your answer.

But that's a real bummer I must say! Seems like I will have to implement that functionality myself.

Anyway, thanks a lot for your work in this library, my project wouldn't be possible without it. 

Best regards
