### ISSUE TITLE
checkSyntax and checkLexSyntax throw SyntaxChecker+LookaheadSuccess exception

### ISSUE THREAD

**Issue by herme063** [mariuszgromada/MathParser.org-mXparser#315]
We have upgraded from 4.2.2 to 5.2.1. When we call `checkSyntax()` and `checkLexSyntax()` a `SyntaxChecker+LookaheadSuccess` is thrown. 

Is this normal and how do we handle it?

**Comment by mariuszgromada** [comment]
Hi. Thanks. Please provide the environment (Java, .NET) and its version.

**Comment by herme063** [comment]
Environment/Runtime: .net 6
Version: 5.2.1

Code:

     using org.mariuszgromada.math.mxparser;

     mXparser.removeBuiltinTokens("C");
     mXparser.modifyBuiltinToken("mean", "average");
     mXparser.modifyBuiltinToken("coalesce", "bav");
     mXparser.disableImpliedMultiplicationMode();

     var exprStr = "X_1 + bav(X_2, X_3) + average(A, B, C)";
     var expr = new Expression(exprStr);

     expr.checkLexSyntax();
     expr.checkSyntax();

     Console.WriteLine("Missing Variables/Arguments: ");
     foreach (var v in expr.getMissingUserDefinedArguments())
     {
          Console.WriteLine("- {0}", v);
     }

     Console.WriteLine("Done");
     Console.ReadLine();

The code above runs fine, but in the debug output window I see these:

     ...
     Exception thrown: 'org.mariuszgromada.math.mxparser.syntaxchecker.SyntaxChecker.LookaheadSuccess' in MathParser.org-mXparser.dll
     Exception thrown: 'org.mariuszgromada.math.mxparser.syntaxchecker.SyntaxChecker.LookaheadSuccess' in MathParser.org-mXparser.dll
     Exception thrown: 'org.mariuszgromada.math.mxparser.syntaxchecker.SyntaxChecker.LookaheadSuccess' in MathParser.org-mXparser.dll
     Exception thrown: 'org.mariuszgromada.math.mxparser.syntaxchecker.SyntaxChecker.LookaheadSuccess' in MathParser.org-mXparser.dll
     Exception thrown: 'org.mariuszgromada.math.mxparser.syntaxchecker.SyntaxChecker.LookaheadSuccess' in MathParser.org-mXparser.dll
     Exception thrown: 'System.IO.IOException' in MathParser.org-mXparser.dll
     Exception thrown: 'System.IO.IOException' in MathParser.org-mXparser.dll
     ...

I found that this behavior started in 5.0.0, before that we would only had the `IOException`.

**Comment by mariuszgromada** [comment]
https://github.com/mariuszgromada/MathParser.org-mXparser/issues/86

**Comment by mariuszgromada** [comment]
https://github.com/mariuszgromada/MathParser.org-mXparser/issues/11

**Comment by mariuszgromada** [comment]
This is not a bug, but a derivative of how JavaCC was ported to C#. When consuming tokens, JavaCC verifies consistency with the grammar, and if something does not match the definition, it throws an exception (in Java this does not cause the same problems as in .net). The creators of the port implemented the code almost "1-1", so CSJavaCC throws errors when the parser receives a string that is not compatible with the grammar. I won't change it, in a predictive launch it has minimal impact on operation. In the DEUBG case, I recommend the VS option
`**"Just My Code"**` in debugger options

**Comment by mariuszgromada** [comment]
When it comes to the `LookaheadSuccess` - lookahead is an option in the JavaCC, that I used recently to generate a parser with more complex grammar. This is the case of v5.x

**Comment by herme063** [comment]
Thank you for the explanation; makes sense.
