### ISSUE TITLE
Simplification/expansion support

### ISSUE THREAD

**Issue by erikha1501** [mariuszgromada/MathParser.org-mXparser#33]
Hi,
I recently came across your xXparser project while doing some research regarding calculus and algebra. It did just fine in evaluating expressions and ran reasonably fast. What I am now interested in is support for expression simplification/expansion. Here is some illustrations of that feature:
-  "(x+1)^2 + 3*x" could be expanded and simplified to "x^2 + 5*x + 1"
- "(x^2 + 3*x + 2) / (x+1)" could be simplified to "x+2"
[In here](http://www.numberempire.com/simplifyexpression.php) they managed to do it nicely.

It would be great if you could implement this on your project and I look forward to seeing it on action.

**Comment by mariuszgromada** [comment]
This is very nice idea, but I think for the future ...
