### ISSUE TITLE
Too many C# projects

### ISSUE THREAD

**Issue by AlexByte** [mariuszgromada/MathParser.org-mXparser#34]
Why did you create separate projects for different platforms if netstandard1.0 supports them all?
![image](https://cloud.githubusercontent.com/assets/25251772/25410863/f514feb8-2a21-11e7-933b-72471b74a3dd.png)

**Comment by mariuszgromada** [comment]
It was Console class issue for instance, some issues related also to CSharpCC project that generates grammar code in pure .net framework. And frankly speaking I do not understand this table as I am mainly java developer :-) So if you have any idea how to simplify I will consider.

**Comment by AlexByte** [comment]
This table is more understandable. It's mean that using .NET Standard 1.0 you can support all platforms in this table (started from .Net 4.5 and .NET Core 1.0 for ex).
What kind of mistakes are you talking about? The assembly targeting .NET Standard 1.0 not working on some platforms?

> ![image](https://cloud.githubusercontent.com/assets/25251772/25425511/db6cdb4a-2a74-11e7-814c-078c14c15594.png)
> 
> - The columns represent .NET Standard versions. Each header cell is a link to a document that shows which APIs got added in that version of .NET Standard.
> - The rows represent the different .NET platforms.
> - The version number in each cell indicates the minimum version of the platform you'll need to implement that .NET Standard version.
> 
> To find the highest version of .NET Standard that you can target, do the following:
> 
> 1. Find the row that indicate the .NET platform you want to run on.
> 2. Find the column in that row that indicates your version starting from right to left.
> 3. The column header indicates the .NET Standard version that your target supports (and **any lower .NET Standard versions will also support it)**.
> 4. Repeat this process for each platform you want to target. If you have more than one target platform, you should pick the smaller version among them. For example, **if you want to run on .NET Framework 4.5 and .NET Core 1.0, the highest .NET Standard version you can use is .NET Standard 1.1**.

**Comment by mariuszgromada** [comment]
I am referring to the PCL, as I understood that .NET Standard is a kind of emplacement to the PCL. I will check, but i am almost sure i needed to use #IF in some pieces of the coded when porting to.net standard.

**Comment by mariuszgromada** [comment]
For instance

			#if PCL || NETSTANDARD
				System.Diagnostics.Debug.WriteLine(o);
			#else
				Console.WriteLine(o);
			#endif

**Comment by mariuszgromada** [comment]
or that
```
#if PCL || NETSTANDARD
	public System.IO.TextWriter debugStream = new System.IO.StreamWriter(new System.IO.MemoryStream());
#else
	public  System.IO.TextWriter debugStream = new System.IO.StreamWriter(System.Console.OpenStandardError());
#endif
```

**Comment by AlexByte** [comment]
Yes, if .Net Standart doesn't support platform, you should create separate project for it and use preprocessor directives.

**Comment by mariuszgromada** [comment]
So I am doing that.,

**Comment by mariuszgromada** [comment]
Do you have additional suggestions, or should I close this issue?

**Comment by AlexByte** [comment]
Will you separate projects for platforms, which are supported by netstrandart1.0?

**Comment by mariuszgromada** [comment]
Can you give me the list? But those project are empty, src is only linked - is this a problem?

**Comment by mariuszgromada** [comment]
I would be happy if you could provide me the list of not needed projects + required nuspec modification? Can you do that?

**Comment by AlexByte** [comment]
The list of not needed projects, all of them are replaced by mXparser-dot.stand.1.0
![image](https://cloud.githubusercontent.com/assets/25251772/26080299/8aadb468-39ce-11e7-9f54-6edd6a6d3fd4.png)

mXparser-dot.net.3.0 targeting .Net Framework 3.0 can be run on any older .Net Framework.

**Comment by mariuszgromada** [comment]
thanks

**Comment by AlexByte** [comment]
mXparser-dot.net.2.0 targeting .Net Framework 2.0 can be run on any older .Net Framework, so projects highlighted in orange can be removed.

![image](https://cloud.githubusercontent.com/assets/25251772/26080660/478e84c6-39d0-11e7-8c37-a5c307331bb1.png)

**Comment by mariuszgromada** [comment]
But core is different than standard - yes? I.e. in standard there is no console class ... thus i need core projects. In terms of older .net frameworks - are you sure that i.e. compilation on 4.7 vs 2.0 has no performance improvements? Even for the same src?

**Comment by AlexByte** [comment]
You will use modern compiler, this is not relevant to targeting
https://stackoverflow.com/questions/66759/are-there-any-advantages-compiling-for-net-framework-3-5-instead-of-2-0

**Comment by mariuszgromada** [comment]
Interesting - thanks! It seems I do need to target only 2.0,. In case of standard / core I need both as for Core i use Console class.

**Comment by Happypig375** [comment]
If you need the Console class, it is included in .NET Standard 1.3. You can just target 1.0 and 1.3.

**Comment by Apollo3zehn** [comment]
Thank you for your great project. I was looking for a math parser and found yours to be the most suitable! 

But I must say I was suprised by the size of the NuGet package (4 MB) and the number of target frameworks. In my opinion, the number of platforms can be heavily reduced. Would you consider a PR that I create maybe tomorrow to clean up the number of projects? Things I would do are:

- creating a Directory.Build.props file
- removing .netcore, .net and .netstandard projects and leaving only .netstandard1.0, netstandard1.3 (for Console class) and .net 3.5 (because it is incompatible to .netstandard1.0). I will not touch PCL, Android and MacOS projects because I am not experienced with them
- converting projects to new .csproj format (e.g. the .NET 3.5 project)
- adapting the .nuspec file

I did not figure out all problems yet. Of course you know better where you encountered problems in the past and why so many projects where necessary. But in general you only need to target the lowest possible frameworks, which are listed above.

**Comment by mariuszgromada** [comment]
The truth is that that I am porting from java to C# and I do not know the dependencies here, thus I am creating all possible options :-) If you can help, I am happy to accept :-)
