### ISSUE TITLE
C# build problems

### ISSUE THREAD

**Issue by Cronan** [mariuszgromada/MathParser.org-mXparser#37]
I don't seem to be able to build using VS2015, it's complaining about:

Unable to get MD5 checksum for the key file "..\..\..\..\..\pfx-keys\mariuszgromada.org.pfx". Could not find a part of the path 'D:\git\pfx-keys\mariuszgromada.org.pfx'.	mXparser-30-PCL	C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets	2884

**Comment by mariuszgromada** [comment]
This is my private key file for assembly signing - I can not share that. You should generate you own key file and use it in dll signing. If you prefer, you can switch off dll signing option in c# project.

**Comment by mariuszgromada** [comment]
pfx files are in my git igonre :-)

**Comment by Cronan** [comment]
Thanks, do I switch it off in every project?

**Comment by mariuszgromada** [comment]
Separate projects are for separate .net frameworks. What framework are you targeting?

**Comment by Cronan** [comment]
.Net 4.5.2 currently - do I remove all the unused projects?

**Comment by mariuszgromada** [comment]
Please keep only mXparser-00-Current, change targeting framework to 4.5.2, switch off the signing option and you are done :-)

**Comment by mariuszgromada** [comment]
The other projects are just linking the source code to mXparser-00-Current.

**Comment by mariuszgromada** [comment]
If this works for you pls give a star to the repository :-)

**Comment by Cronan** [comment]
:-)

**Comment by mariuszgromada** [comment]
Thanks! :-)
