### ISSUE TITLE
Question: get arguments from expression

### ISSUE THREAD

**Issue by DrNickClarke** [mariuszgromada/MathParser.org-mXparser#38]
Hi I have just started using this for expression parsing and it looks great.

I would like to ask if it is possible to determine from an expression what the arguments are.

For example if the user types the expression "a\*x^2 +b\*x +c"

I would like to be able to run the parser and automatically determine that they need to supply values for "a", "b", "c" and "x" to get the expression to calculate.

Is there a way to do that?

Thank you
Nick

**Comment by mariuszgromada** [comment]
Hi,

Yes - there is an option for that :-)

1. First of all, if user inputted arguments, that are not known to the parser, then **checkSyntax()** will return false (invalid token). That is why you need to check whether lexical syntax is ok, for that please use **checkLexSyntax()**. If checkLexSyntax() is true and checkSyntax() is false it means the only things that are missing are: user defined arguments and / or user defined functions and / or user defined constants. 

**Lexical and general syntax checking**
```
Expression e = new Expression("a*x^2+b*x+c");
boolean lexSyntax = e.checkLexSyntax();
boolean genSyntax = e.checkSyntax();
mXparser.consolePrintln("lexSyntax = " + lexSyntax + ", genSyntax: " + genSyntax);
mXparser.consolePrintln();
mXparser.consolePrintln(e.getErrorMessage());
```
**Result**
```
lexSyntax = true, genSyntax: false

[a*x^2+b*x+c] checking ...
[a*x^2+b*x+c] (a, 0) invalid <TOKEN>.
[a*x^2+b*x+c] (x, 2) invalid <TOKEN>.
[a*x^2+b*x+c] (b, 6) invalid <TOKEN>.
[a*x^2+b*x+c] (x, 8) invalid <TOKEN>.
[a*x^2+b*x+c] (c, 10) invalid <TOKEN>.
[a*x^2+b*x+c] errors were found.
```
2. After that you can use **getCopyOfInitialTokens()** which returns a list of tokens (Token class elements). To get a bit more feeling on that try to print tokens using **mXparser.consolePrintTokens()**.

**Printing expression tokens**
```
Expression e = new Expression("a*x^2+b*x+c");
mXparser.consolePrintTokens( e.getCopyOfInitialTokens() );
```
**Result**
```
 --------------------
| Expression tokens: |
 ---------------------------------------------------------------------------------------------------------------
|    TokenIdx |       Token |        KeyW |     TokenId | TokenTypeId |  TokenLevel |  TokenValue |   LooksLike |
 ---------------------------------------------------------------------------------------------------------------
|           0 |           a |             |          -1 |          -1 |           0 |         NaN |    argument |
|           1 |           * |           * |           3 |           1 |           0 |         NaN |             |
|           2 |           x |             |          -1 |          -1 |           0 |         NaN |    argument |
|           3 |           ^ |           ^ |           5 |           1 |           0 |         NaN |             |
|           4 |           2 |       _num_ |           1 |           0 |           0 |         2.0 |             |
|           5 |           + |           + |           1 |           1 |           0 |         NaN |             |
|           6 |           b |             |          -1 |          -1 |           0 |         NaN |    argument |
|           7 |           * |           * |           3 |           1 |           0 |         NaN |             |
|           8 |           x |             |          -1 |          -1 |           0 |         NaN |    argument |
|           9 |           + |           + |           1 |           1 |           0 |         NaN |             |
|          10 |           c |             |          -1 |          -1 |           0 |         NaN |    argument |
 ---------------------------------------------------------------------------------------------------------------
```
3. Finally you cans use Token.looksLike hint :-)

**Token looks like hint**
```
Expression e = new Expression("a*x^2+b*x+c");
ArrayList<Token> tokensList = e.getCopyOfInitialTokens();
for (Token t : tokensList)
	if (t.tokenTypeId == Token.NOT_MATCHED)
		mXparser.consolePrintln("token = " + t.tokenStr + ", hint = " + t.looksLike);
```
**Result:**
```
token = a, hint = argument
token = x, hint = argument
token = b, hint = argument
token = x, hint = argument
token = c, hint = argument
```

I hope this helps :-)

Best regards

**Comment by mariuszgromada** [comment]
Please let me know whether this fits your needs?

**Comment by DrNickClarke** [comment]
Hi

Thanks for coming back to me. This looks like it should solve my use case.
I will test it and confirm back to you that it works.

Nick

**Comment by mariuszgromada** [comment]
If it solves then pls give a star to the repo :-)

**Comment by DrNickClarke** [comment]
Yes good idea will do. Thank you. Nick

**Comment by DrNickClarke** [comment]
Tested. Works perfectly. This is a great project. Thanks

**Comment by mariuszgromada** [comment]
Thanks. In the next release I will add better API  support for your use case :-)

**Comment by mariuszgromada** [comment]
I strongly suggest you to go through tutorial http://mathparser.org/mxparser-tutorial/
:-)

**Comment by prabhakarbcrec** [comment]
hi @mariuszgromada 
I am using this as a library, but I want to know about precedence rule whatever you followed.
I am able to validate, calculate my expression but I want to convert my expression in JSON format on the basis on precedence of these things   **-,+,/,().**
please help me out
Thanks in advance.

**Comment by mariuszgromada** [comment]
Hello @prabhakarbcrec

Can you give some example?

Best regards

**Comment by prabhakarbcrec** [comment]
expression:"a+b*c"

JSON suppose to bellow
{ 
   "var1":"a",
    "operator":"+",
   "var2":"{
            "var1":"b",
            "operator":"*",
            "var2":"c"
                }
}

**Comment by prabhakarbcrec** [comment]
Hi, and the next thing is how to access tokenId?

**Comment by mariuszgromada** [comment]
Hi @prabhakarbcrec

Unfortunately I am still having problem to understand your request. The operator precedence is as it is in the math rules.  Do you want to create a JSON from expression? Or maybe you want to create an expression from JSON? I will give you a piece of advice how to handle tokens - please follow below tutorial

http://mathparser.org/mxparser-tutorial/playing-with-expression-tokens/

Best regards
