### ISSUE TITLE
Not a number result when adding too many arguments

### ISSUE THREAD

**Issue by overzealus** [mariuszgromada/MathParser.org-mXparser#39]
Hello. I'm using mXparser with Xamarin.iOS, using latest stable Mono and here's my problem:
I'm creating a list of arguments, with names like A, B, C, D, E, F ... X, Y, Z, AA, AB, AC, AD .. AX, AY, AZ, BA, BB, BC .. etc.
Each argument has a value. Maximum number of arguments is about 150.
Expression string could be something simple like "A-50", so there could be 150 argument, but only 1, 2, 3 or 4 of them are used in expression string.
If I add just 2 arguments (example - A=65, B=0) and use expression string "A-50", I have correct result 15.
But, if I add more Arguments like A=65, B=0, C=0, D=0, E=95, ... etc, I get "not a number" result with the same expression string.
Inspecting debug, there is an error message, something connected with duplicate arguments. But I'm absolutely sure, that I have no duplicate arguments.

**Comment by mariuszgromada** [comment]
Hi,

Thx for your feedback. It is rather duplicated token. mXparser delivers a lot of built-in tokens. You can check this list via mXparser.getHelp() and verify arguments names against it.

Best regards

**Comment by overzealus** [comment]
Hello. Thank you for your reply.
Is there any way, I can exclude built in tokens, so they wouldn't duplicate my variable names (unfortunately, I have to use variables with names like I showed)?

**Comment by mariuszgromada** [comment]
The code is already on GitHub, but not yet released. Pls check #24 for more details. If you want I can send you a pre- release dla :-)

**Comment by overzealus** [comment]
It would be very kind of you.
My mail is john.nicolsone@outlook.com
PS. I need references for Xamarin.IOS platform.

PS. Your project is great.

**Comment by mariuszgromada** [comment]
I need few hours as I am not in front od my pc. Thx :-) If you like pls give a star :-)

**Comment by mariuszgromada** [comment]
Send - please let me know if it works :-)

**Comment by mariuszgromada** [comment]
Please let me know whether everything works fine?

**Comment by overzealus** [comment]
Hello. Yes, everything works fine.
Thank you very much.

-----Исходное сообщение-----
От: "Mariusz Gromada" <notifications@github.com>
Отправлено: ‎25.‎05.‎2017 22:12
Кому: "mariuszgromada/MathParser.org-mXparser" <MathParser.org-mXparser@noreply.github.com>
Копия: "overzealus" <stanislav.svist@gmail.com>; "Author" <author@noreply.github.com>
Тема: Re: [mariuszgromada/MathParser.org-mXparser] Not a number result whenadding too many arguments (#39)

Please let me know whether everything works fine?

**Comment by mariuszgromada** [comment]
Great :-)

**Comment by mariuszgromada** [comment]
There is also a new option :-)

- mXparser.setToOverrideBuiltinTokens();
- mXparser.setNotToOverrideBuiltinTokens();
- mXparser.checkIfEpsilonMode();
