### ISSUE TITLE
String support

### ISSUE THREAD

**Issue by BobDickinson** [mariuszgromada/MathParser.org-mXparser#4]
I think I already know the answer, but is there any way to work with strings as variables/constants and get a string result?  It looks like everything is converted to doubles and there's not a way to work with strings, but I just wanted to verify.

**Comment by mariuszgromada** [comment]
Thank you for your query. Can you provide more details on the use case? In next releases I plan to deliver nice API extension enabling working totally on strings, meaning you will be able to create & reuse arguments / constants using only String commands (currently you need to use object construction, and then object reuse in string expression definition). Please follow below example

**Currently:**
Argument x = new Argument("x = 5");
Function f = new Function("f(a,b) = 2*a + b");
Expression e = new Expression("2*x + f(1,2) - sin(pi)", x, f):

**Planned API extension **- I do not have the exact classes names, but let us assume it will be the "**Spreadsheet**" class
Spreadsheet s = new Spreadsheet();
s.add("x = 5");
s.add("f(a,b) = 2*a+b");
double v = s.calculate("2*x + f(1,2) - sin(pi)");
 
And many other :-)

So the Spreadsheet class will operate only on strings enabling end-user to define everything at a run-time.

Kind regards

**Comment by BobDickinson** [comment]
Thanks for getting back so quickly.

We have a cross platforms (iOS, Android, Windows, web) mobile platform with a data binding engine, and we'd like to add expression support to it.  It currently handles tokens of type boolean, double, and string.

Here is a common type of need:

    Argument replyCnt = new Argument("replyCnt = 5");
    Expression e = new Expression("replyCnt == 1 ? 'reply' : 'replies'", replyCnt):

The idea being that the user has a token representing the number of replies to a message, and they want to display the correct pluralized string.

In our application, we know in advance the type of the result that we're looking for (so, for example, we can easily coerce the double result to boolean to make the boolean support work).

The example above also uses the ternary operator.  I think we'd need either that or a c-function-like version of that (some kind of basic boolean logic support), ex: ```"if(reply == 1, 'reply', 'replies')"```.

In a perfect world, c-like functions that could be implemented to operate on evaluated params would be great (so we could implement things like min, max, etc.).

I know this is outside of what you support now.  We really like a lot of things about this project, especially the fact that it's cross platform, so I thought I'd ask.

**Comment by mariuszgromada** [comment]
Ok, now I fully understand your requirements. Fortunately I have this on my roadmap as many math operation requires string result.  For instance prime numbers factorization (pnf) of a given number, i.e. pnf(100) = '2^2 x 5^2’. So the result is more than one calculated number. I plan to extend Expression class with the new method: public String evaluate(). Currently in Expression there is only: public double calculate(). In general evaluate() will work the same as calculate() for typical expressions, the only difference will be that the final double result will be converted to string. However evaluate() will work differently for new set of functions returning string results (i.e. pnf mentioned above). If string function will be used in expression then calculate() will return NaN (as it make no sense to get double), but evaluate() will try to figure out if something different could be returned (for instance factorization, solution, description, etc.). This new feature is planned, should be delivered with weeks I think - this is pretty big change, but important. And, on your request, I will add new string function if( expression, 'str1’, 'str2’). It needs to be done well, split into phases i.e. any string function can use the result of any other function, or even can be defined by the user  Currently I am finishing development of double precision rounding, random numbers, random variables, probability distributions, and some special functions like upper, lower gamma, error function and so on).
Best regards

**Comment by cspurling** [comment]
I've been evaluating mxparser and I've been impressed so far. We would love to use this expression parser but we require string expression evaluation.  It would be great if you could add support for strings. Some built in string functions such as concat, substring, length, upper, lower would be very useful.

**Comment by mariuszgromada** [comment]
Hi,

Thanks a lot for your feedback. This is planned, but will take a while as now I am finishing random numbers and probability distributions support. String support is a bigger change, but will be implemented for sure!

Kind regards

**Comment by kleckajakub** [comment]
Hello Mariusz,

I have question about using string in condition. I would like to define expression like this:

`Expression e = new Expression("someString==anotherString ? 42 : 99");`

Its possible to define this kind of expression? (output of this expression should be number - double/int not string.

Thanks for your answer.

BR,
Jakub.

**Comment by hakamairi** [comment]
Hello Mariusz,
I have even more complicated need for strings in boolean expressions.
Some of the variables are just strings and I'm matching on their values, for example:
`Expression e = new Expression("deliveryType = deliver by tuk tuk");`

So matched string value could contain white spaces. Is something like that on the roadmap at all?

**Comment by mariuszgromada** [comment]
Hi,

This is math expression parser - string arguments are still not supported. This is quite a big change (grammar, tokenization, functions, etc...) Many users are asking about it, but there are a plenty of functions to be redeveloped... I am thinking on that, but not sure when (and If) this will be ready.

Bes regards

**Comment by dimonser147** [comment]
Hi,

Thanks a lot for a great package!

Do we have any chance to implement a custom function (or any workaround) like?
`"MyFunc1('column name 1','raw name 1','Table')"`

Almost 2 years passed, so any ETA will be useful. We decided to use your lib in on of our project, so we can contribute in free time.

Thanks,
Dmytro

**Comment by mariuszgromada** [comment]
This is mainly math parser, and string processing is out of its domain. It would be nice to have it, but this requires deep changes in the core of the lib. This is why this is not progressing...

**Comment by mariuszgromada** [comment]
I think now the most important thing to do is code refactoring - then maybe it would be possible to extend with strings.

**Comment by 111003022** [comment]
Is String equality check in if condition supported in latest release or not?

example:
Expression e = new Expression("if(name < maddy , yes ,  no )");

**Comment by juarezr** [comment]
## Workaround

Here a [hack](https://github.com/juarezr/mxparse-string) for working with strings and logic evaluation using mxparser.

**Comment by mariuszgromada** [comment]
@juarezr nice hack 👍

**Comment by 111003022** [comment]
@mariuszgromada hi...any target release/date for supporting string values? I have  a case where I want to check for string equality in if condition.
e.g. Expression e = new Expression("if(name == maddy , yes , no )");

And I realized that this is not supported as of today,

**Comment by brunosantosrhsenso** [comment]
FunctionExtension with string parameters, any chance?
