### ISSUE TITLE
Nuget Support

### ISSUE THREAD

**Issue by vvenegasv** [mariuszgromada/MathParser.org-mXparser#5]
Hi, nice work! It looks pretty good!!. 

i don't have any issue, only few questions:

1.- What license has? Can i use in commercial projects?
2.- Can you release this projects in Nuget? Maybe, if you don't have time, i can do it for you ;)

Regards!

**Comment by mariuszgromada** [comment]
Hello,

Thanks a lot for your feedback :-)

1. License - you can use it in commercial projects in any form. mXparser is distributed under Simplified BSD license, details are here: http://mathparser.org/mxparser-license/
2. Nuget - project is available as nuget package: https://www.nuget.org/packages/MathParser.org-mXparser/

Best regards

**Comment by vvenegasv** [comment]
Nice!! Thank you very much!!! :+1:

**Comment by mariuszgromada** [comment]
This was in 2016 and still applies to the versions available at the time.
