### ISSUE TITLE
Unary trigonometric functions not working properly.

### ISSUE THREAD

**Issue by kumailn** [mariuszgromada/MathParser.org-mXparser#53]
When I input the string "sin([rad]*pi)" I get 0.0548... instead of 0. Similarly when I input "cos([deg]*90)" I get -0.44807... instead of 0.

**Comment by mariuszgromada** [comment]
Hmm strange - what platform are you using? 
```
Expression e = new Expression("sin([rad]*pi)");
mXparser.consolePrintln(e.getExpressionString() + " = " + e.calculate())
```

Result:
`sin([rad]*pi) = 1.2246467991473532E-1`

And the other case:
```
Expression e = new Expression("cos([deg]*90)");
mXparser.consolePrintln(e.getExpressionString() + " = " + e.calculate());
```

Result:
`cos([deg]*90) = -3.8285686989269494E-16`

Can you share your code?

Best regards

**Comment by kumailn** [comment]
Oh I forgot I was rounding my decimals off to 12 decimal places, is there anyway to return the result as 0 instead of E-16?
Thanks.

**Comment by mariuszgromada** [comment]
You can user round function, i.e.  "round( sin([rad]*pi), 14 )"
