### ISSUE TITLE
Dependencies error

### ISSUE THREAD

**Issue by rfulton04** [mariuszgromada/MathParser.org-mXparser#54]
Error:Project :app declares a dependency from configuration 'androidTestCompile' to configuration 'default' which is not declared in the descriptor for project :libs:MathParser.

**Comment by mariuszgromada** [comment]
Hi. Can you share more info? Please describe your problem.

**Comment by rfulton04** [comment]
app/build.gradle has

  compile project(':libs:MathParser')

projectname/libs/mathparser

is where I put the library files.

projectname/settings.gradle contains
include ':libs:MathParser'

Should work, but doesn;t!

**Comment by mariuszgromada** [comment]
which jar are you sign? version compiled with jdk1.7?

**Comment by rfulton04** [comment]
Ah, didn't use a jar file, just pulled the directory from github. 

Fixed once I just threw in the .jar file, and right click add to library.

Learn something new every day i guess.

**Comment by mariuszgromada** [comment]
Great I could help :-)

**Comment by mariuszgromada** [comment]
DO not forget to star the repo if you like it :-)
