### ISSUE TITLE
Support for custom functions

### ISSUE THREAD

**Issue by nietha** [mariuszgromada/MathParser.org-mXparser#6]
Currently addFunction only support a string expression, would it be possible to extend it to take a .NET function as well?

Ex.

Expression e = new Expression("customfunc(var1+var2)");
e.addFunction("customfunc", CustomFunc);

public static decimal CustomFunc(decimal input) {..do what ever..}

**Comment by mariuszgromada** [comment]
This is on a roadmap as mXparser extension options, but will be based on passing object not function as java does not support delegates. The aim of mXparser project is to keep API the same for java and .net.

Additionally I recommend to used addDefinitions() instead of addFunctions(), I have plan to deprecate addFunctions().

Best regards

**Comment by eborn** [comment]
Hello Mariusz, do you have any ETA on this? Is it a matter of weeks, months, years? I couldn't find any math library close to this one regarding math functions, but this ability is quite common in others and unfortunately missing in mXparser.

**Comment by mariuszgromada** [comment]
This will be pretty fast - max 1-2 weeks - I was on vacations :-)

Best regards

**Comment by MartinSher** [comment]
Any update?
Martin

**Comment by mariuszgromada** [comment]
Dear Martin. I have paused development for some period - I was focus on some other project - but I'll be back very soon, maybe this weekend will prepare this change.

**Comment by mariuszgromada** [comment]
Added for java, now will be ported for .net. Release very soon.

**Comment by mariuszgromada** [comment]
Please implement FunctionExtension interface the use proper constructor from Function class.

**Comment by mariuszgromada** [comment]
Case nr 5:
http://mathparser.org/mxparser-tutorial/user-defined-functions/
