### ISSUE TITLE
Roots of negative number result in NaN error.

### ISSUE THREAD

**Issue by kumailn** [mariuszgromada/MathParser.org-mXparser#68]
Roots of negative numbers result to NaN instead of evaluating to a negative number, for example the string "(-216)^(1/3)" evaluates to NaN instead of -6.

**Comment by mariuszgromada** [comment]
(-216)^(1/3) - this is exponential function

I will consider adding root(x,n) function as then I have a control on the n parameter.

Bu usually root is considered for positive numbers

**Comment by mariuszgromada** [comment]
I found a nice workaround for that :-)

**Comment by mariuszgromada** [comment]
Done :-)
