### ISSUE TITLE
Add the Java library to Maven Central

### ISSUE THREAD

**Issue by olavgg** [mariuszgromada/MathParser.org-mXparser#7]
It would be awesome if you could add this library to Maven central. As this is the go to place for most Java developers for third party libraries.

**Comment by mariuszgromada** [comment]
Thank you for your feedback. I will prepare maven package - then let you know.

Best regards

**Comment by dorpsidioot** [comment]
Is there any news on this? I could help if needed?

**Comment by mariuszgromada** [comment]
Lets agree haw can you help :-)

**Comment by mariuszgromada** [comment]
I just promoted the first release to maven :-)

**Comment by mariuszgromada** [comment]
https://search.maven.org/#artifactdetails%7Corg.mariuszgromada.math%7CMathParser.org-mXparser%7C4.0.0%7Cjar
