### ISSUE TITLE
Add support for implied multiplication

### ISSUE THREAD

**Issue by kumailn** [mariuszgromada/MathParser.org-mXparser#72]
It would be great if mXparser could evaluate, for example, "3pi" to "3 x pi" or "5(4)" to "5 x 4" automatically

**Comment by mariuszgromada** [comment]
This is important and will be added, but not in the upcoming release.

**Comment by mariuszgromada** [comment]
Done https://github.com/mariuszgromada/MathParser.org-mXparser/issues/243
