### ISSUE TITLE
Add support for evaluating/solving algebraic equations

### ISSUE THREAD

**Issue by kumailn** [mariuszgromada/MathParser.org-mXparser#73]
It would be very helpful if the parser could solve for a variable with a given equation, for example, solve for x in "x + 1 * 7 = 34" or "x^2 + x + 12 = 2".

**Comment by mariuszgromada** [comment]
This is supported, check solve() function

**Comment by mariuszgromada** [comment]
Pls refer to the http://mathparser.org/mxparser-tutorial/solving-equation-fx-0/

**Comment by mariuszgromada** [comment]
Pls let me know if this solves your issue.

**Comment by mariuszgromada** [comment]
Is it ok for you?

**Comment by kumailn** [comment]
Yes, thanks

**Comment by mariuszgromada** [comment]
Great :-)
