### ISSUE TITLE
Zeros in front of number and decimal without 0 in front results in NaN

### ISSUE THREAD

**Issue by kumailn** [mariuszgromada/MathParser.org-mXparser#74]
For example the string "001 + 002" results in a NaN error instead of "3.0", secondly the string ".1 + .2" also evaluates to NaN.

**Comment by mariuszgromada** [comment]
Pls refer to "Leading zeros (i.e. 0002) are not recognized as numbers" #36

**Comment by kumailn** [comment]
@mariuszgromada and what about decimals without leading zeroes?

**Comment by mariuszgromada** [comment]
I am rather against as this is not clear...
