### ISSUE TITLE
Any change/thought regarding .Net Core?

### ISSUE THREAD

**Issue by bigteejay** [mariuszgromada/MathParser.org-mXparser#8]
`Package MathParser.org-mXparser 3.0.0 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package MathParser.org-mXparser 3.0.0 supports: net40-client (.NETFramework,Version=v4.0,Profile=Client)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.`

I wasn't expecting it to work just yet as .Net Core is still a WIP, but figured I would try... as well as inquire as to if there are any plans for a version that is supported?

**Comment by mariuszgromada** [comment]
Supported :-)
