### ISSUE TITLE
checksyntax has problem

### ISSUE THREAD

**Issue by MehdiPirmoradian** [mariuszgromada/MathParser.org-mXparser#80]
10*(350.0/5) + 60.0 +  +  (180/3)*5
 returns true "already checked no errors"
please check and modify it

**Comment by mariuszgromada** [comment]
Confirmed - this is a bug. Thx. Problem is also causing infinite loop while calculate()

**Comment by mariuszgromada** [comment]
The cause of the problem was identified. If '++' used instead of '+ +' the check syntax works ok returning false.  I need fix the grammar a bit :-) thx for contributing.

**Comment by MehdiPirmoradian** [comment]
Your welcome.
subject to your new release

**Comment by mariuszgromada** [comment]
fixed

**Comment by mariuszgromada** [comment]
Released - check nuget or maven :-)
