### ISSUE TITLE
Add support bitwise operator and formulas

### ISSUE THREAD

**Issue by KevinGerard** [mariuszgromada/MathParser.org-mXparser#81]
Hi, 
I'm trying your parser right now, and for now I'm pleased, but have some point to discuss.

Why do we need to add some '@' character in order to use all bitwise operators? like: 
1. `1 @& 1` instead of `1 & 1`
2. `10 @>> 4` instead of `10 >> 4`

**Comment by mariuszgromada** [comment]
Bitwise support was added in the v.4.0, at that time '&' was pointing to the 'and' logical operator. This is to keep backward compatibility. Anf ffinally i decided to start each bitwise operator with '@'.

Why this is a problem?

Best regards

**Comment by KevinGerard** [comment]
okay ... I anderstand ... the "problem" was if anyone need to update (in my case, more a switch) from a another evaluator to yours, it is required to update all functions. 

For example: `&` is more a bitwise operator and the logical operator `AND` is more `&&`.

**Comment by mariuszgromada** [comment]
In coding - I agree. But here the library evolved from pure mathematics... and I was not replicating the operators as it was - i.e. factorial is "!", but in coding this is negation. For sure I did not choose the best keywords. Maybe, in the future, I decide to cancel backward compatibility in order to clean keywords a bit.

**Comment by mariuszgromada** [comment]
Thx for giving the star :+1:

**Comment by KevinGerard** [comment]
Great ! Thanks you for the answers. 

I'll test your library performances now! ;)

**Comment by mariuszgromada** [comment]
Great :-) Library was designed to effectively calculate expressions with variables. Expression containing variables is pre-compiled on first checkSyntax. If only variables values were changed  (meaning no change to the expression string, etc) then calculation should be fast.

Additionally the main coding language for mXparser is Java, then code is ported to C#. Thss means that java version is more effective then .net in terms of performance.
