### ISSUE TITLE
Problem with percent

### ISSUE THREAD

**Issue by ambyte** [mariuszgromada/MathParser.org-mXparser#83]
Now result of expression 50+50% equals 50,5
But I would like to get the result is 75

How can I do it?

**Comment by mariuszgromada** [comment]
It seems the result is correct, indeed 50+50% = 50.5 as 50% = 0.5
If your goal is to get 50 + 50% of 50 then you need to use: 50 + 50%*50

**Comment by ambyte** [comment]
Result is correct but not is user frendly.
if you open standart windows calculator and enter the value 50+50% it will return answer 75
User enters a value 50% meaning a percentage of the number, not 0.5

**Comment by mariuszgromada** [comment]
This way of simplifying is confusing in my opinion. Try MS Excel for instance, it will return 50.5.

**Comment by mariuszgromada** [comment]
I am aware that some calculators are implementing this, but mXparser is not a simple calculator. This is advanced math parser - sorry for not handling your use case.

**Comment by ambyte** [comment]
Thanks for the answer, 
It is not difficult to implement for me, but I thought that maybe this is already implemented.
Thanks for a great library!

**Comment by mariuszgromada** [comment]
Thx
