### ISSUE TITLE
How to let mXparser calculate trigonometric functions in degrees by default?

### ISSUE THREAD

**Issue by R4SHOMON** [mariuszgromada/MathParser.org-mXparser#87]
By default mXparser uses radian mode to calculate trigonometric functions.
To get the calculations in degrees I have to use ***[deg]** as suggested in this question #26 .
Is there a way to set the mXparser to always use degrees or radians without adding the extra ***[deg]**.
I'm using this library to allow the user to enter formulas directly in a text box. 
The user should write **cos(90)** and get the results in degrees or radians, as configured from setting option.

**Comment by mariuszgromada** [comment]
Currently there is no such option. I will consider implementation in new release.

**Comment by mariuszgromada** [comment]
If degrees option is on then it should also affect inverse trigonometric function as well (i.e. arcus sinus should return values in degrees).

**Comment by R4SHOMON** [comment]
Ok thanks, meanwhile is there a proper way implemented in order to handle it from my side. checking for trigonometric functions and modifying the formula expression manually is ugly.

**Comment by mariuszgromada** [comment]
Better wait for my solution, I will commit code for this on GitHub in a few days. There will be an option, and then depending on the option, argument of trigonometric function will be changed accordingly.

**Comment by R4SHOMON** [comment]
Thank you, appreciate your efforts 👍

**Comment by mariuszgromada** [comment]
mXparser.setDegreesMode()
mXparser.setRadiansMode()
mXparser.checkIfDegreesMode()
mXparser.checkIfRadiansMode()

Default mode is radians mode

**Comment by mariuszgromada** [comment]
Pls let me know whether change is working properly?

**Comment by R4SHOMON** [comment]
Sorry to bother you, but how should I get the latest version, I couldn't find the version with the fix, I already have the latest version from nuget, and from github. https://github.com/mariuszgromada/MathParser.org-mXparser/releases/tag/v.4.1.1

**Comment by mariuszgromada** [comment]
This is still not released as I am working on v.4.2 Aquaria. I can send you a dll / jar file If you want. Pls let me know.

**Comment by R4SHOMON** [comment]
If you would send a dll to test it out, that would be great.

**Comment by mariuszgromada** [comment]
pls give me your email address - or send it to mariuszgromada.org@gmail.com

**Comment by R4SHOMON** [comment]
I have send you an e-mail

**Comment by mariuszgromada** [comment]
dll was sent.

**Comment by R4SHOMON** [comment]
I have tested the four new methods:
```
mXparser.setDegreesMode()
mXparser.setRadiansMode()
mXparser.checkIfDegreesMode()
mXparser.checkIfRadiansMode()
```
they work great, I will keep working with them, actually I replaced the old dll with the new one for the QA to test it out from their side as well. 
If any issue came up, I'll report it here ASAP.
Thank you.

**Comment by mariuszgromada** [comment]
Great thx :-)

**Comment by mariuszgromada** [comment]
The new dll contains also changes listed here - maybe you will find something beneficial:
https://github.com/mariuszgromada/MathParser.org-mXparser/milestone/2?closed=1

Best regards

**Comment by mariuszgromada** [comment]
Especiall fractions :-)
https://github.com/mariuszgromada/MathParser.org-mXparser/issues/90

**Comment by R4SHOMON** [comment]
You're awesome man, I really appreciate your efforts, and how quick your responses are.
keep up the good work :-)

**Comment by kaliprasad** [comment]
hi Mariuszgromada,

I appreciate your work. 

I want the updated dll too.

please send the dll to my emial id: **deepakkaliprasad@gmail.com**

Thanks
kaliprasad

**Comment by mariuszgromada** [comment]
Hi, dll was sent :-)

**Comment by mariuszgromada** [comment]
Released - check nuget or maven :-)
