### ISSUE TITLE
Add support for mathematical negation operator

### ISSUE THREAD

**Issue by sagikazarmark** [mariuszgromada/MathParser.org-mXparser#9]
This one: ¬

**Comment by mariuszgromada** [comment]
Currently negation is on: ~
I assume you want to add another token ¬ for negation?

**Comment by sagikazarmark** [comment]
Yes, that was the idea. Haven't checked the source code yet, but I guess it's just adding another token for negation into the token parser/token list.

**Comment by sagikazarmark** [comment]
I can try to open a PR if you like the idea.

**Comment by mariuszgromada** [comment]
This is very small change. I will add this token.

**Comment by sagikazarmark** [comment]
Awesome. Thanks.

**Comment by mariuszgromada** [comment]
Added in next version - will be released soon

**Comment by mariuszgromada** [comment]
This will not be added - sorry - there problem with this character in CSJavaCC. It works perfectly in JavaCC. mXparser is maintained in Java and C# - thus I need to have common grammar... For negation pls use "~".

**Comment by sagikazarmark** [comment]
Okay, no problem, thanks anyway.
