### ISSUE TITLE
Fraction Calculation

### ISSUE THREAD

**Issue by moliata** [mariuszgromada/MathParser.org-mXparser#90]
Hello, I am amazed by how powerful and simple this library is! I am currently stuck by this question, How to calculate fractions? Regards.

**Comment by mariuszgromada** [comment]
Hi,

Thx for your feedback. What do you mean to calculate fractions? You can write 3/4 or 5/2 - mXparser will perform division. But remember - the final number is always returned as double.

Best regards

**Comment by mariuszgromada** [comment]
I will introduce new method toFraction(double number) to convert double to fraction on request :-)

**Comment by moliata** [comment]
Thanks! When will v4.2 should be coming?

**Comment by mariuszgromada** [comment]
I do not plan to release v.4.2 any soon. But the code for will be on github in a few days.  Which platform do you use? Java//.net?

**Comment by mariuszgromada** [comment]
The only condition is that you will give a start to the repo :-)

**Comment by moliata** [comment]
Hello, O am using Java. Also, what do you mean I will give a start to the repo

**Comment by mariuszgromada** [comment]
:-) Star on github, that you like mXparser :-)

**Comment by mariuszgromada** [comment]
So I will build new jar just for you, containing this new feature. This feature will enable to convert the finals result, which si double, to twa integer numbers (numerator and denominator) or to one string "numerator/denominator". The methid will be in mXparser calls. Possible usage will be
Expression e = new Expression("3/2 * 5/7");
String s = mXparser.toFraction( e.calculate() );

s will be "15/14"

**Comment by moliata** [comment]
Cool! I am just thinking what if I have a mixed fraction (you can learn more about what I mean on Google), what should I do. Also, this custom jar, won't change how division works. So 3/2 * 5/7 result would be 1.0714285715 and if I use toFraction(e.calculate) then it would return fraction, right? Ps: I am working on a PhotoMath alternative & I am thinking about making  mXparser - a core calculator for app. So I need fractions and etc. support.

**Comment by mariuszgromada** [comment]
Currently this cannot be supported.

**Comment by mariuszgromada** [comment]
This could work as that:

5_2_3
10_5
2_4
3_5_4

But this is much bigger change as requires grammar modification.

**Comment by moliata** [comment]
Let me know what you can make, I usually check GitHub Notifications every 4-6h, thanks!

**Comment by mariuszgromada** [comment]
Decided - it will be possible to use number literals in fraction form directly in expression. Expample

Expression e = new Expression("2_3 + 2_1_2");

will evaluate to 3,16666666666667, and then using mXparser.tofraction( double ) it will be possible to convert it to a fraction again.

Bes regards

**Comment by moliata** [comment]
Oh ok! Thanks for the info.

**Comment by mariuszgromada** [comment]
So it is done :-)

**Fractions number literals support**
`
Expression e = new Expression("2_3_2 + 1_2");
`

**Double to fraction conversion**
```
double[] mXparser.toFraction(double value)
double[] mXparser.toMixedFraction(double value)
String mXparser.fractionToString(double[] fraction)
String mXparser.toFractionString(double value)
String mXparser.toMixedFractionString(double value)
mXparser.setToFractionInitSearchSize(long n)
long mXparser.getToFractionInitSearchSize()
```

:-)

**Comment by moliata** [comment]
Thank you so much, regards.

**Comment by mariuszgromada** [comment]
Please let me know your views in implemented changes. It required a lot of work :-) You should have jar on your email.

**Comment by mariuszgromada** [comment]
Aha - i decided to represent fraction as array of double, I did not wanted to introduce new Fraction class as majority of use case will be on strings.

normal fraction - double[3]
sign  - at index 0
numerator - at index 1
denominator at index 2

Mixed fraction - double[4]
sign - at index 0
whole number - at index 1
numerator - at index 2
denominator at index 3

Bes regards

**Comment by moliata** [comment]
Great idea, amazing!

**Comment by mariuszgromada** [comment]
Please let me know when you test it.

**Comment by moliata** [comment]
Did you use double arrays?

**Comment by mariuszgromada** [comment]
Yes, double has much bigger range. Long is limited to 2^64, double is something 10^307. All the mXparser is based on double. The method toFractionString formats double to nice integer, but allowing huger range. In this double array always integer is stored (not the int type, the value without decimals).

**Comment by mariuszgromada** [comment]
Did you manage to test it?

**Comment by moliata** [comment]
Hello, it works! Currently I am using my own custom instance of SympyGamma on App Engine, but this will be used for a normal calculator in my app.

**Comment by mariuszgromada** [comment]
Released - check nuget or maven :-)
