### ISSUE TITLE
Could this library able to be used in unity3D?

### ISSUE THREAD

**Issue by Thaina** [mariuszgromada/MathParser.org-mXparser#97]
If this library was not used `Expression.Compile()` or `Reflection.Emit` it might be able to be ported to unity. Is it possible?

**Comment by mariuszgromada** [comment]
This library is developed in java, then ported to C#. I do not use Reflection.Emit, Expression.Compile(). Unfortunately I do not know nothing about unity3d - so I can not answer the question - sorry.

**Comment by Thaina** [comment]
@mariuszgromada That's a good news because unity actually use mono 2.0 / 4.6. Almost all mono library that not use any feature unsupported by AoT (such as `Expression.Compile()` or `Reflection.Emit` as I mention) would be usable in unity

I will do experiment with this and report the result later

**Comment by mariuszgromada** [comment]
Great. Pls add some info on your use case :-)

**Comment by mariuszgromada** [comment]
Did you test it? Pls let us now :-)

**Comment by Thaina** [comment]
Sorry for the late

I just write a very basic test on android and it worked. Unfortunately I can't test it on iOS (I has no iOS device) but I was also test it on WebGL which has the same AoT limitation as iOS. So it has a very high chance to work on iOS too

This is screenshot I take from my android

![image](https://user-images.githubusercontent.com/1042507/32991428-294a3276-cd6e-11e7-9125-2051e16ea220.png)

**Comment by mariuszgromada** [comment]
thx :-)

**Comment by Thaina** [comment]
@mariuszgromada If you could test it on unity iOS I think you should also add unity to the supported framework too

**Comment by mariuszgromada** [comment]
So I asked for help, #113
